Resources/Private/JavaScript/Host/index.js
https://github.com/zalmoxisus/redux-devtools-extension
Note: for meaningful debugging, you need to:
- go to chrome://extensions/
- find "Redux DevTools" there and click "Options"
- Enable "Serialization" in these options.
(taken from https://github.com/zalmoxisus/redux-devtools-extension/issues/35)
=> FEATURE: Support Chrome Redux Dev Tools Extension

.travis.yml, Build/TravisCi/InstallScripts/IntegrationTests.sh
…to avoid errors with composer while removing/installing a lot of packages while being above the rate limit of the GitHub API - closes #60
=> TASK: Add the -n flag and the github oAuth token to the travis setup

.travis.yml, Build/TravisCi/AfterScripts/UnitTests.sh, Build/TravisCi/Scripts/IntegrationTests.sh, README.md, Resources/Private/JavaScript/Host/Containers/FlashMessageContainer/index.js
Use `it.only(() => {})` and `describe.only(() => {})` if you want to run a specific test and not the whole test suite.
=> DOCS: Update Readme "Filter tests" with "only"

.travis.yml, Build/Docker/run.sh, Build/TravisCi/Scripts/Docker.sh, Resources/Private/JavaScript/Host/Containers/FlashMessageContainer/index.js, docker-compose.yaml
Add a docker-compsoe.yaml and test execution in travis
=> FEATURE: Docker/Docker-Compose support

Build/check-dependencies, package.json
using https://www.npmjs.com/package/check-dependencies with prescript
=> FEATURE: check if all dependencies are fulfilled and install missing on "build" and "watch"

.gitignore, webpack.config.js
see https://github.com/webpack/docs/wiki/build-performance#sourcemaps for possible values
=> TASK: activate source maps

package.json, webpack.config.js
https://www.npmjs.com/package/webpack-livereload-plugin
=> FEATURE: Add live-reloading via webpack-livereload-plugin

Classes/PackageFactory/Guevara/Domain/Model/Changes/AbstractCreate.php, Classes/PackageFactory/Guevara/Domain/Model/Changes/Create.php, Classes/PackageFactory/Guevara/Domain/Model/Changes/CreateAfter.php, Classes/PackageFactory/Guevara/Domain/Model/Changes/CreateBefore.php, Classes/PackageFactory/Guevara/TypoScript/Helper/NodeInfoHelper.php, Configuration/Settings.yaml, Resources/Private/JavaScript/Host/Containers/AddNodeModal/index.js, Resources/Private/JavaScript/Host/Redux/Changes/index.js, Resources/Private/JavaScript/Host/Redux/Changes/index.spec.js, Resources/Private/JavaScript/Host/Redux/Sagas/Changes/index.js, Resources/Private/JavaScript/Host/Selectors/CR/NodeTypes/index.js, Resources/Private/JavaScript/Host/Selectors/CR/Nodes/index.js, Resources/Private/JavaScript/Host/Selectors/UI/AddNodeModal/index.js, Resources/Private/JavaScript/Host/index.js, Resources/Private/TypoScript/Backend/InitialState.ts2, Resources/Private/TypoScript/Backend/Node.ts2
=> WIP - Create nodes modal

webpack.config.js
See https://github.com/webpack/webpack/blob/master/lib/Stats.js#L26-L40
for possible options.
=> BUGFIX: reduce log output in Webpack console

Resources/Private/JavaScript/Guest/Redux/CKEditorToolbar/index.js, Resources/Private/JavaScript/Guest/Redux/EditorToolbar/index.js, Resources/Private/JavaScript/Guest/Redux/NodeToolbar/index.js, Resources/Private/JavaScript/Host/Redux/CR/Nodes/index.js, Resources/Private/JavaScript/Host/Redux/CR/Workspaces/index.js, Resources/Private/JavaScript/Host/Redux/Changes/index.js, Resources/Private/JavaScript/Host/Redux/System/index.js, Resources/Private/JavaScript/Host/Redux/UI/AddNodeModal/index.js, Resources/Private/JavaScript/Host/Redux/UI/ContentCanvas/index.js, Resources/Private/JavaScript/Host/Redux/UI/Drawer/index.js, Resources/Private/JavaScript/Host/Redux/UI/FlashMessages/index.js, Resources/Private/JavaScript/Host/Redux/UI/FullScreen/index.js, Resources/Private/JavaScript/Host/Redux/UI/LeftSideBar/index.js, Resources/Private/JavaScript/Host/Redux/UI/PageTree/index.js, Resources/Private/JavaScript/Host/Redux/UI/Remote/index.js, Resources/Private/JavaScript/Host/Redux/UI/RightSideBar/index.js, Resources/Private/JavaScript/Host/Redux/User/Settings/index.js, Resources/Private/JavaScript/Host/Sagas/UI/Plugin/index.js, composer.json, package.json
My regex somehow managed to miss these...
=> TASK: rename JS guevara constants

Resources/Private/JavaScript/Components/DropDown/index.js, Resources/Private/JavaScript/Guest/Containers/EditorToolbar/SubComponents/DropDown/index.js, Resources/Private/JavaScript/Host/Redux/CR/Workspaces/index.js, package.json
I have fixed a few bugs leading to an unstable UI after re-installing it. The most severe ones were the one about publishableNodes.count not found, as it was no Immutable object anymore; and I needed to downgrade Redux Saga a little as I could not find the root cause of the error yet.
All the best,
Sebastian
=> Various stability bugfixes

Resources/Private/JavaScript/Components/ToggablePanel/index.js, Resources/Private/JavaScript/Components/ToggablePanel/index.story.js, Resources/Private/JavaScript/Host/Containers/Modals/AddNode/index.js, Resources/Private/JavaScript/Host/Redux/UI/AddNodeModal/index.js, Resources/Private/JavaScript/Host/Redux/UI/AddNodeModal/index.spec.js
This would allow to the state of groups in browser local storage.
=> TASK: move addNodeModal state to redux

Resources/Private/JavaScript/Guest/CKEditorApi.js, Resources/Private/JavaScript/Host/Containers/ContentCanvas/index.js, Resources/Private/JavaScript/Host/Containers/RightSideBar/Inspector/EditorEnvelope/index.js, Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/EditorToolbar/StyleSelect.js, Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/EditorToolbar/index.js, Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/EditorToolbar/style.css, Resources/Private/JavaScript/Host/Extensibility/Registry/index.js, Resources/Private/JavaScript/Host/README.md, Resources/Private/JavaScript/Host/Redux/UI/ContentCanvas/index.js, Resources/Private/JavaScript/Host/manifest.inlineEditing.js, Resources/Private/JavaScript/Host/manifest.js
Fully-fledged CKEditor configuration, including:
- all styles supported by Aloha
- extensible 
- tables
=> Deep CKEditor integration

Classes/Neos/Neos/Ui/Controller/BackendController.php, Resources/Private/JavaScript/Host/Containers/LeftSideBar/PageTree/Node/index.js
Correct tree handlers and use correct node as site root.
=> BUGFIX: fix the broken tree

Classes/Neos/Neos/Ui/TYPO3CR/Service/WorkspaceService.php, Classes/Neos/Neos/Ui/TypoScript/AppendAllToCollectionImplementation.php, Classes/Neos/Neos/Ui/TypoScript/ArrayCollectionImplementation.php, Classes/Neos/Neos/Ui/TypoScript/Helper/ModulesHelper.php, Classes/Neos/Neos/Ui/TypoScript/Helper/SitesHelper.php, Configuration/Settings.yaml, Resources/Private/JavaScript/Host/Containers/Drawer/MenuItem/index.js, Resources/Private/JavaScript/Host/Containers/Drawer/MenuItemGroup/index.js, Resources/Private/JavaScript/Host/Containers/Drawer/index.js, Resources/Private/JavaScript/Host/Containers/Drawer/style.css, Resources/Private/JavaScript/Host/Sagas/System/index.js, Resources/Private/JavaScript/Host/Sagas/View/index.js, Resources/Private/Templates/Backend/Index.html, Resources/Private/TypoScript/Backend/Root.ts2, Resources/Private/TypoScript/Prototypes/AppendAllToCollection.ts2, Resources/Private/TypoScript/Prototypes/ArrayCollection.ts2
* Menu items are an additional json structure that lives outside the application state and configuration
* potentially to be fetched asynchronously later on
* Menu items are rendered via TypoScript
* Menu items can either target the window or the content canvas
TODOS:
solves: #6
=> FEATURE: Drawer (main) menu implemention

Resources/Private/JavaScript/Host/Containers/ContentCanvas/index.js, Resources/Private/JavaScript/Host/Containers/LeftSideBar/PageTree/Node/index.js, Resources/Private/JavaScript/Host/Containers/Modals/AddNode/nodeTypeGroupPanel.js, Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/DimensionSwitcher/index.js
=> BUGFIX: miscelleneous bugfixes and improvements

Resources/Private/JavaScript/Host/Containers/Root.js, Resources/Private/JavaScript/Host/Sagas/View/index.js
Currently it's very confusing, that the root component of our React
rendering is placed in as weird a place as a Saga. This may be difficult
for React developers to grasp, so I refactor it to be in a more expected
place.
=> TASK: refactor root react component out from View saga

Classes/Neos/Neos/Ui/Controller/BackendServiceController.php, Resources/Private/JavaScript/Host/Redux/User/Settings/index.js, Resources/Private/JavaScript/Host/Sagas/Changes/index.js, Resources/Private/JavaScript/Host/Sagas/Publish/index.js
=> FEATURE: Auto-Publishing

packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/index.js, packages/neos-ui-editors/src/Image/Components/Secondary/MediaDetailsScreen/index.js, packages/neos-ui-editors/src/Image/Components/Secondary/MediaSelectionScreen/index.js, packages/neos-ui-editors/src/Image/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/EditorEnvelope/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js, packages/neos-ui/src/manifest.js
This is done by introducing a new callback function which can be used to render the secondary
inspector.
=> FEATURE: Close secondary inspector when applying or cancelling the inspector

packages/neos-ui/src/Containers/ContentCanvas/InlineUI/AddEmptyContentCollectionOverlays/index.js, packages/neos-ui/src/Containers/ContentCanvas/InlineUI/AddEmptyContentCollectionOverlays/index.spec.js, packages/neos-ui/src/Containers/ContentCanvas/InlineUI/AddEmptyContentCollectionOverlays/style.css, packages/neos-ui/src/Containers/ContentCanvas/InlineUI/index.js
=> FEATURE: Add "empty content collection" overlay to allow selecting empty content collections

package.json, packages/neos-ui/package.json, packages/react-ui-components/package.json, packages/react-ui-components/src/DropDown/wrapper.js, packages/react-ui-components/src/DropDown/wrapper.spec.js, packages/react-ui-components/src/ToggablePanel/toggablePanel.js, packages/react-ui-components/src/ToggablePanel/toggablePanel.spec.js
Explanation: https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076
Fixes #374
=> BUGFIX: ensure Dropdowns / Togglable panels can be opened / closed again

Resources/Private/Templates/Backend/Index.html
=> BUGFIX: Remove leftover css

packages/neos-ui-ckeditor-bindings/src/guestFrameApi.js
=> BUGFIX: Fix CKEditor Event Listening "active" state

packages/utils-helpers/src/discover.js
=> TASK: Remove unneeded isthenable check

README.md
README update to get an running installation
=> FIX: composer dependencies

Classes/Neos/Neos/Ui/Domain/Model/AbstractChange.php, Classes/Neos/Neos/Ui/Domain/Model/Changes/Create.php, Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/DocumentNodeCreated.php, Classes/Neos/Neos/Ui/TYPO3CR/Service/NodeService.php, packages/neos-ui-redux-store/src/UI/PageTree/selectors.js, packages/neos-ui-redux-store/src/UI/Remote/index.js, packages/neos-ui/src/Sagas/UI/PageTree/index.js, packages/neos-ui/src/manifest.js
=> FEATURE: Reload the document tree if you create a new node #395

package.json, packages/build-essentials/src/webpack.config.js
This fixes the "watch" task for all other packages than Neos-UI
=> BUGFIX: Let the watch task work again

Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractCreate.php, Classes/Neos/Neos/Ui/Exception/InvalidNodeCreationHandlerException.php, Classes/Neos/Neos/Ui/NodeCreationHandler/DocumentTitleNodeCreationHandler.php, Classes/Neos/Neos/Ui/NodeCreationHandler/NodeCreationHandlerInterface.php, Configuration/NodeTypes.yaml, packages/neos-ui/src/Containers/Modals/AddNode/index.js
This feature allows abstractCreate change to receive an array of generic data coming from creation
dialog and passes it to registered NodeCreationHandlers.
=> FEATURE: NodeCreationHandlers

packages/neos-ui/src/Containers/LeftSideBar/PageTree/Node/index.js, packages/react-ui-components/src/Tree/node.css, packages/react-ui-components/src/Tree/node.js
Now it is possible to focus a node in the tree by clicking it in the same line.
So there is a active node and a focused one.
=> FEATURE: improve node focus in the tree

packages/neos-ui-editors/src/SelectBox/index.js, packages/neos-ui/src/Sagas/Changes/index.js, packages/neos-ui/src/Sagas/UI/Inspector/index.js, packages/react-ui-components/src/DropDown/style.css, packages/react-ui-components/src/SelectBox/index.story.js, packages/react-ui-components/src/SelectBox/selectBox.js, packages/react-ui-components/src/SelectBox/selectBox.spec.js, packages/react-ui-components/src/SelectBox/style.css
=> FEATURE: Allow select values to be reseted #442

Classes/Neos/Neos/Ui/TypoScript/Helper/NodeInfoHelper.php, packages/neos-ui-editors/src/NodeType/index.js, packages/neos-ui-editors/src/NodeType/style.css, packages/neos-ui-editors/src/manifest.js, packages/neos-ui-redux-store/src/CR/Nodes/helpers.js, packages/neos-ui-redux-store/src/CR/Nodes/selectors.js, packages/neos-ui-redux-store/src/UI/AddNodeModal/selectors.js
=> FEATURE: NodeType editor

Classes/Neos/Neos/Ui/Domain/Model/Changes/Remove.php, Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/RemoveNode.php, Configuration/Settings.yaml, packages/neos-ui-redux-store/src/CR/Nodes/index.js, packages/neos-ui-redux-store/src/CR/Nodes/index.spec.js, packages/neos-ui-redux-store/src/CR/Nodes/selectors.js, packages/neos-ui-redux-store/src/Changes/index.js, packages/neos-ui/src/Containers/ContentCanvas/Helpers/dom.js, packages/neos-ui/src/Containers/ContentCanvas/InlineUI/NodeToolbar/Buttons/DeleteSelectedNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/DeleteSelectedNode/index.js, packages/neos-ui/src/Containers/Modals/DeleteNode/index.js, packages/neos-ui/src/Containers/Modals/DeleteNode/style.css, packages/neos-ui/src/Containers/Modals/index.js, packages/neos-ui/src/Sagas/CR/NodeOperations/index.js, packages/neos-ui/src/Sagas/CR/NodeOperations/index.spec.js, packages/neos-ui/src/Sagas/CR/index.js, packages/neos-ui/src/manifest.js, packages/react-ui-components/src/Button/button.js, packages/react-ui-components/src/Button/style.css, packages/react-ui-components/src/Dialog/style.css
=> FEATURE: Delete node functionality in tree and content view

packages/neos-ui/src/Containers/Modals/AddNode/nodeTypeItem.js, packages/react-ui-components/src/_lib/fontAwesome.js
This removes some propTypes and fontAwesome complaints
=> CLEANUP: Minor fixes

packages/neos-ui/src/Sagas/UI/PageTree/index.js
Anytime the currently edited document changes, the page tree saga will
check on whether all parent documents of the next document are already
in the store and uncollapsed.
When they are not in the store, they are loaded immediately.
When the are collapsed they get uncollapsed immediately.
=> TASK: Load page tree rootline on document change

Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractMove.php, Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveAfter.php, Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveBefore.php, Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveInto.php, Configuration/Settings.yaml, packages/neos-ui-redux-store/src/CR/Nodes/index.js, packages/neos-ui-redux-store/src/CR/Nodes/index.spec.js, packages/neos-ui/src/Containers/ContentCanvas/InlineUI/NodeToolbar/Buttons/CutSelectedNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CutSelectedNode/index.js, packages/neos-ui/src/Sagas/CR/NodeOperations/index.js
=> FEATURE: Cut&Paste nodes

packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorEditorEnvelope/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorEditorEnvelope/style.css, packages/react-ui-components/src/TextArea/style.css, packages/react-ui-components/src/TextArea/textArea.js, packages/react-ui-components/src/TextInput/style.css, packages/react-ui-components/src/TextInput/textInput.js
A collection of tiny fixes and adjustments. Review on commit-by-commit basis.
=> TASK: misc. fixes

packages/neos-ui-editors/src/EditorEnvelope/index.js, packages/neos-ui-editors/src/NodeType/index.js, packages/neos-ui-i18n/src/i18nService.js, packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/neos-ui/src/Containers/EditModePanel/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/PasteClipBoardNode/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorEditorEnvelope/index.js
A few tiny unrelated fixes that makes console error free again. Review on commit-by-commit basis.
Please check your PRs for clean console output before merging!
=> BUGFIX: make console output clean again

Resources/Private/Translations/en/Main.xlf, packages/neos-ui-redux-store/src/UI/InsertionModeModal/index.js, packages/neos-ui/src/Containers/Modals/InsertMode/index.js, packages/neos-ui/src/Sagas/CR/NodeOperations/index.js
When moving nodes it should not say "copy".
=> TASK: customize InsertionModeModal text depending on the operation type

packages/neos-ui/src/Containers/ContentCanvas/InlineUI/NodeToolbar/Buttons/AddNode/index.js, packages/neos-ui/src/Containers/ContentCanvas/InlineUI/NodeToolbar/Buttons/PasteClipBoardNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/AddNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/PasteClipBoardNode/index.js, packages/react-ui-components/src/Button/index.story.js, packages/react-ui-components/src/Button/style.css
=> TASK: fix Button style combinations and fix the toolbars' hover styles

packages/neos-ui-editors/src/TextField/index.js, packages/neos-ui/src/Containers/Modals/AddNode/index.js, packages/neos-ui/src/Containers/Modals/AddNode/step1.js, packages/neos-ui/src/Containers/Modals/AddNode/step2.js, packages/neos-ui/src/Containers/Modals/AddNode/style.css
- fix close button
- autofocus on first input
- better styling
=> TASK: various AddNode modal improvements

packages/neos-ui-editors/src/TextArea/index.js, packages/neos-ui-editors/src/TextField/index.js, packages/neos-ui/src/Containers/Modals/AddNode/step2.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorEditorEnvelope/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js, packages/react-ui-components/src/TextArea/style.css, packages/react-ui-components/src/TextArea/textArea.js, packages/react-ui-components/src/TextInput/index.story.js, packages/react-ui-components/src/TextInput/style.css, packages/react-ui-components/src/TextInput/textInput.js
=> TASK: highlight transient inspector fields

Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php, Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php, Configuration/Settings.yaml, Resources/Private/Fusion/Prototypes/Page.fusion, packages/neos-ui/src/Containers/ContentCanvas/Helpers/dom.js, packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/neos-ui/src/Containers/Modals/AddNode/index.js, packages/neos-ui/src/Sagas/CR/NodeOperations/index.js
This implements a basic implementation of #328
A custom content element wrapping Fusion implementation will be implemented in a follow-up.
A more sophisticated implementation (serialized data per cache segment) needs more work and could be part of another follow-up.
=> FEATURE: Node serialization

packages/neos-ui/src/Containers/ContentCanvas/Helpers/calculateEnabledFormattingRulesForNodeType.js, packages/neos-ui/src/Containers/ContentCanvas/Helpers/dom.js, packages/neos-ui/src/Containers/ContentCanvas/Helpers/index.js, packages/neos-ui/src/Containers/ContentCanvas/Helpers/initializeCkEditorForDomNode.js, packages/neos-ui/src/Containers/ContentCanvas/Helpers/initializeHoverHandlersInIFrame.js, packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/EditorToolbar/StyleSelect.js, packages/neos-ui/src/Containers/SecondaryToolbar/EditorToolbar/index.js, packages/neos-ui/src/Sagas/ServerFeedback/index.js, packages/neos-ui/src/manifest.js
... the implementation is not really nice; but it's a start we can iterate on!
=> BUGFIX: initialize CKEditor for newly inserted content

packages/neos-ui-validators/src/NotEmpty/index.js, packages/neos-ui-validators/src/NumberRange/index.js, packages/neos-ui-validators/src/RegularExpression/index.js, packages/neos-ui-validators/src/StringLength/index.js
Use singlequotes instead of doublequotes and adjust comments
=> CLEANUP: validators

packages/neos-ui-backend-connector/src/FlowQuery/index.js, packages/neos-ui/src/Sagas/UI/Inspector/index.js, packages/neos-ui/src/Sagas/UI/PageTree/index.js
... fixes issues with publishing in inspector and node tree loading
=> BUGFIX: fix leftover direct access with Plow.js

packages/neos-ui/src/localStorageMiddleware.js
... we should use a Saga for storing and restoring!
=> BUGFIX: only store very specific state in LocalStorage

packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js, packages/neos-ui-views/.babelrc, packages/neos-ui-views/package.json, packages/neos-ui-views/src/NodeInfoView/index.js, packages/neos-ui-views/src/NodeInfoView/index.spec.js, packages/neos-ui-views/src/NodeInfoView/style.css, packages/neos-ui-views/src/ViewEnvelope/index.js, packages/neos-ui-views/src/manifest.js, packages/neos-ui/package.json, packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorViewEnvelope/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorViewEnvelope/index.spec.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorViewEnvelope/style.css, packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js, packages/neos-ui/src/index.js, packages/neos-ui/src/manifest.js
An approach for views in the inspector. Not finished yet. Suggestions and changes are very welcome
=> FEATURE: views for the inspector

Configuration/Settings.yaml, packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui-redux-store/src/UI/EditPreviewMode/index.js, packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/neos-ui/src/Containers/ContentCanvas/style.css, packages/neos-ui/src/Containers/EditModePanel/index.js, packages/neos-ui/src/Sagas/UI/EditPreviewMode/index.js, packages/neos-ui/src/Sagas/UI/index.js
This also includes a new feature, to be able to specify width
and height of the edit-preview-mode container.
=> FEATURE: support different edit/preview modes

Resources/Private/Fusion/Prototypes/Page.fusion, Resources/Private/Templates/Backend/GuestNotificationScript.html, packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/react-ui-components/src/Frame/frame.js
Changes timeouts to a signal triggered from inside the guest frame.
Additionally cleanup of code and adaption to current code standards.
=> BUGFIX: Refactor frame component

packages/neos-ui-editors/src/Image/Components/Secondary/MediaDetailsScreen/index.js
Show image preview when clicking the image in the ImageEditor within the inspector.
Fixes: #614
=> BUGFIX: Show image preview panel on click

Classes/Neos/Neos/Ui/Domain/Model/Changes/Property.php
Before it tried to set nodetype as a string, which caused exception
=> BUGFIX: fix changing node's nodetype

packages/neos-ui/src/Containers/SecondaryToolbar/style.css
=> TASK: Fix right alignment for SecondaryToolbar

packages/neos-ui/src/Containers/RightSideBar/style.css
=> TASK: Adjust width of rightsidebar toggle button to publish button

Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
Causes memory leaks currently.
=> BUGFIX: fix typo in Document nodetype name

packages/neos-ui/src/Sagas/UI/ContentCanvas/index.js
=> TASK: Update browser title to the title of the content frame

packages/neos-ui-editors/src/Reference/index.js
=> FEATURE: add options from documentation to reference editor

packages/neos-ui/src/Containers/ContentCanvas/Helpers/initializeCkEditorForDomNode.js
=> BUGFIX: Avoid undefined placeholder

package.json, packages/neos-ui/package.json, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js, yarn.lock
=> TASK: Strip html tags from nodename labels

packages/neos-ui-editors/src/CodeMirror/CodeMirrorWrap/codemirror.vanilla-css, packages/neos-ui-editors/src/CodeMirror/CodeMirrorWrap/index.js
=> BUGFIX: increase height of codemirror editor

packages/neos-ui-editors/src/TextArea/index.js, packages/neos-ui-editors/src/manifest.js
Still a long way to a proper implementation, but at least it works now.
=> BUGFIX: make TextArea work

package.json, packages/neos-ui/package.json, packages/neos-ui/src/Containers/ContentCanvas/Helpers/initializeCkEditorForDomNode.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js, packages/utils-helpers/src/index.js, packages/utils-helpers/src/stripTags.js, packages/utils-helpers/src/stripTags.spec.js, packages/utils-helpers/src/striptags.js, packages/utils-helpers/src/striptags.spec.js, yarn.lock
=> TASK: Remove tags from placeholder

packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
=> TASK: Do not show inspector editor tabs if  tab have no properties

packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
=> BUGFIX: add whitespace between "Create New" and Node Type name in Create Node Dialog

packages/react-ui-components/src/TextInput/textInput.js
no clue why this was limited in the first place. Twitter generation ;)
=> BUGFIX: allow text inputs longer than 140 characters

Configuration/Settings.yaml, packages/build-essentials/package.json, packages/build-essentials/src/webpack.config.js, packages/build-essentials/yarn.lock, packages/neos-ui/package.json, packages/neos-ui/src/index.js
instead of loading it via google
closes #690
=> TASK: Use webfont directly

packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/style.css, packages/neos-ui/src/Containers/LeftSideBar/index.js
remove unneeded hr
closes #588
=> BUGFIX: Adjust borders to correct width

Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php, packages/neos-ui-redux-store/src/CR/Nodes/index.js, packages/neos-ui/src/Sagas/UI/PageTree/index.js
=> BUGFIX: ensure the tree state does not override the current node state

README.md
The Docker image is unmaintained, so I removed the reference to it. Might make sense to make one at some point.
=> TASK: update installation instructions in the README

packages/neos-ui-editors/src/DateTime/index.js, packages/react-ui-components/src/DateInput/dateInput.js
=> TASK: Correctly show and format datepicker value

packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/AspectRatioDropDown/index.js, packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/AspectRatioDropDown/style.css, packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/index.js, packages/react-ui-components/src/DropDown/header.js, packages/react-ui-components/src/IconButton/iconButton.js, packages/react-ui-components/src/IconButton/style.css, packages/react-ui-components/src/TextInput/style.css, packages/react-ui-components/src/TextInput/textInput.js
=> TASK: Support locked aspect ratio

packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js, packages/neos-ui-redux-store/src/UI/ContentCanvas/index.spec.js, packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/neos-ui/src/Sagas/UI/ContentCanvas/index.js
This PR includes a mechanism for displaying the orange progress bar when the user creates a new document.
Closes #727
=> TASK: Set loading flag when the document creation is processing

packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/style.css, packages/neos-ui/src/Containers/LeftSideBar/index.js, packages/neos-ui/src/Containers/LeftSideBar/style.css
**How to test**: click on a node inside content canvas that is not yet visible inside the content tree. The tree should scroll to reveal it. If the tree node is already in view the tree shouldn't scroll.
=> TASK: scroll the tree to focused node

packages/react-ui-components/src/Button/index.story.js, packages/react-ui-components/src/Button/style.css
One way to test is to hover over toolbar icons, they should be blue when enabled and stay the same color when disabled.
=> BUGFIX: fix hover colors on Button

packages/.vscode/settings.json
If you need this, you should .gitignore the file in your
personal gitignore and put it there in your local installation.
This should never end up in the repository.
=> TASK: Remove vscode settings from project repository

packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
=> TASK: Dont render empty inspector groups

README.md
I was starting the storybook server and didn't know where to access it so I thought it would be a good idea to mention the port :)
=> TAKS: Document storybook port

Resources/Private/Fusion/Backend/Root.fusion, packages/neos-ui/src/Containers/Drawer/MenuItem/index.js, packages/neos-ui/src/Containers/Drawer/MenuItemGroup/index.js, packages/neos-ui/src/Containers/Drawer/style.css, packages/react-ui-components/src/Icon/icon.js, packages/react-ui-components/src/Icon/index.story.js, packages/react-ui-components/src/Icon/style.css, packages/react-ui-components/src/ToggablePanel/style.css, packages/react-ui-components/src/ToggablePanel/toggablePanel.js
=> BUGFIX: Adjust the appearance of the main menu to match the one of the old ui

packages/react-ui-components/src/Button/style.css
=> BUGFIX: Remove button icon background

packages/react-ui-components/src/TextArea/index.story.js, packages/react-ui-components/src/TextArea/textArea.js, packages/react-ui-components/src/TextArea/textArea.spec.js
=> BUGFIX: TextArea expand

.travis.yml, packages/neos-ui/src/Sagas/UI/PageTree/index.js
=> BUGFIX: set pagetree focus when navigating from inline

packages/neos-ui-editors/src/DateTime/index.js, packages/react-ui-components/src/DateInput/dateInput.js, packages/react-ui-components/src/DateInput/dateInput.spec.js, packages/react-ui-components/src/DateInput/index.js, packages/react-ui-components/src/DateInput/style.css
The styles of the component are pretty messy, but since they are isolated in scope I didn't spend too much time cleaning it up.
I think UX-wise solution is OK, I somehow even like it better than what we had in the old UI.
Thoughts?
=> TASK: add support for selecting time to DateInput

packages/neos-ui-editors/src/TextField/index.js, packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CopySelectedNode/index.js, packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CutSelectedNode/index.js, packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/DeleteSelectedNode/index.js, packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/HideSelectedNode/index.js, packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js, packages/neos-ui-guest-frame/src/InlineUI/index.js, packages/neos-ui-redux-store/src/CR/Nodes/selectors.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CopySelectedNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
=> BUGFIX: disable copy of contentcollections

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/style.css
=> TASK: Remove border-bottom from ck-editor toolbar

packages/neos-ui-redux-store/src/CR/Workspaces/selectors.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js, packages/react-ui-components/src/Tree/index.story.js, packages/react-ui-components/src/Tree/node.css, packages/react-ui-components/src/Tree/node.js
=> TASK: mark "dirty" nodes in the trees

packages/neos-ui-redux-store/src/CR/Nodes/helpers.js, packages/neos-ui/src/Sagas/UI/ContentTree/index.js
=> BUGFIX: Editing a property from another page causes browser tab to freeze and crash

packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js, packages/neos-ui-guest-frame/src/initializeGuestFrame.js
Fixes: #815
Also add it focused class.
=> BUGFIX: scroll focused node into view after canvas reload

packages/neos-ui/src/Containers/style.css
=> BUGFIX: don't override scrollbar styles of contentcanvas

packages/react-ui-components/src/DateInput/dateInput.js, packages/react-ui-components/src/DateInput/dateInput.spec.js
Otherwise it's not possible to update a date once it's set.
=> BUGFIX: set defaultValue on date component instead of value

package.json, packages/neos-ui-redux-store/src/CR/Nodes/index.js, packages/neos-ui-redux-store/src/CR/Nodes/index.spec.js, packages/neos-ui/src/Sagas/UI/Inspector/index.js, yarn.lock
=> BUGFIX: update previewUrl and uris in state after editing uriPathSegment

packages/react-ui-components/src/DropDown/contents.js, packages/react-ui-components/src/DropDown/index.story.js, packages/react-ui-components/src/DropDown/style.css, packages/react-ui-components/src/SelectBox/selectBox.js
=> TASK: make SelectBox scrollable

packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/index.js, packages/react-ui-components/src/DropDown/header.js, packages/react-ui-components/src/DropDown/wrapper.js
=> BUGFIX: fix ImageCroper custom ratio controls

packages/neos-ui-guest-frame/src/initializePropertyDomNode.js, packages/neos-ui-redux-store/src/Changes/index.js, packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeItem.js, packages/neos-ui/src/Sagas/CR/NodeOperations/addNode.js, packages/neos-ui/src/Sagas/CR/NodeOperations/copyAndPasteNode.js, packages/neos-ui/src/Sagas/CR/NodeOperations/cutAndPasteNode.js, packages/neos-ui/src/Sagas/CR/NodeOperations/hideNode.js, packages/neos-ui/src/Sagas/CR/NodeOperations/moveDroppedNode.js, packages/neos-ui/src/Sagas/CR/NodeOperations/removeNodeIfConfirmed.js, packages/neos-ui/src/Sagas/CR/NodeOperations/showNode.js, packages/neos-ui/src/Sagas/Changes/index.js, packages/neos-ui/src/Sagas/UI/Inspector/index.js, packages/neos-ui/src/manifest.js
=> TASK: persist all changes from inspector in one request

packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui-backend-connector/src/FetchWithErrorHandling/index.js, packages/neos-ui-backend-connector/src/FlowQuery/index.js, packages/neos-ui-backend-connector/src/FlowQuery/index.spec.js, packages/neos-ui-backend-connector/src/index.js, packages/neos-ui-redux-store/src/System/index.js, packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js, packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js, packages/neos-ui/src/Containers/Modals/ReloginDialog/style.css, packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js, packages/neos-ui/src/Containers/Modals/index.js, packages/neos-ui/src/System/index.js, packages/neos-ui/src/index.js, packages/neos-ui/src/manifest.containers.js, packages/react-ui-components/src/Dialog/dialog.js, packages/react-ui-components/src/Dialog/dialog.spec.js, packages/react-ui-components/src/Dialog/index.story.js, packages/react-ui-components/src/Dialog/style.css
Resolves #901 
To test, run `rm -Rf Data/Temporary/Development/Cache/Data/Flow_Session_*` while having the UI open
=> FEATURE: Relogin on authentication error

packages/neos-ui-views/src/NodeInfoView/index.js, packages/neos-ui-views/src/NodeInfoView/style.css
This change add a line break between the title and the content and
display the current Node Type of the selected node.
=> TASK: Improve NodeInfoView

packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
Sorry, scrolling was totally broken.
=> BUGFIX: fix contentCanvas scrolling into view

packages/neos-ui/src/manifest.js
=> BUGFIX: focus content node on creation

Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
=> BUGFIX: don't respect baseNodeType during search

packages/react-ui-components/src/Button/style.css
=> BUGFIX: fix hover background on icons

package.json, packages/react-ui-components/package.json, packages/react-ui-components/src/Dialog/dialog.js, packages/react-ui-components/src/Dialog/dialog.spec.js, yarn.lock
=> BUGFIX: close modals on ESC

packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui-editors/src/Reference/index.js, packages/neos-ui-editors/src/References/index.js, packages/react-ui-components/src/SelectBox/selectBox.js, packages/react-ui-components/src/SelectBox/style.css
=> BUGFIX: Set correct icon in Reference(s)Editor

packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/react_crop.vanilla-css
=> TASK: Make the crop border more visible

packages/neos-ui-editors/src/Boolean/index.js, packages/neos-ui-editors/src/DateTime/index.js, packages/neos-ui-editors/src/Image/Components/PreviewScreen/index.js, packages/neos-ui-editors/src/Image/Components/PreviewScreen/style.css, packages/neos-ui-editors/src/Image/index.js, packages/neos-ui-editors/src/Link/index.js, packages/neos-ui-editors/src/NodeType/index.js, packages/neos-ui-editors/src/Reference/index.js, packages/neos-ui-editors/src/References/index.js, packages/neos-ui-editors/src/SelectBox/DataSourceBasedSelectBoxEditor.js, packages/neos-ui-editors/src/SelectBox/SimpleSelectBoxEditor.js, packages/neos-ui-editors/src/SelectBox/index.js, packages/react-ui-components/src/CheckBox/checkBox.js, packages/react-ui-components/src/CheckBox/style.css, packages/react-ui-components/src/DateInput/dateInput.js, packages/react-ui-components/src/DateInput/style.css, packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js, packages/react-ui-components/src/MultiSelectBox/style.css, packages/react-ui-components/src/SelectBox/selectBox.js, packages/react-ui-components/src/SelectBox/style.css
=> TASK: Show highlight status on Editors if a property is changed

packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
Fixes: #971 
This fix is a bit dirty, since I get the `csrfToken` in a kind of hard-coded ugly way, but on the other hand all actions urls in there are also hardcoded and are begging for refactoring...
=> BUGFIX: send csrf token with logout action

packages/react-ui-components/src/_lib/fontAwesome.js
=> BUGFIX: Allow the use of multiple classes in icons

packages/neos-ui-guest-frame/src/initializeGuestFrame.js
=> TASK: Listen to click on guest frame document rather than body

packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
This is broken since 9ca09aa6d80bfd2b45ca61684dc5f15bbe585a48 - but
fortunately easy to fix :)
Fixes #932
=> BUGFIX: fix constraints with auto-created child nodes

packages/neos-ui-editors/src/Image/Components/Controls/index.js, packages/neos-ui-editors/src/Image/index.js
This removes the crop button if no image is present and disables the remove button.
fixes #1013
=> TASK: Dont show crop and diasble remove if no image is present

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js
=> BUGFIX: Allow for mailto: and tel: protocols in Linkeditor (CKEditor)

Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
=> BUGFIX: Use user-configured locale for node augmentation

packages/neos-ui-editors/src/NodeType/index.js
=> BUGFIX: Disable Change Type editor for auto created child nodes

packages/react-ui-components/src/_lib/fontAwesome.js
This adds the following icons to the backward-compatible list:
* icon-calendar-empty
* icon-flag-alt
* icon-upload-alt
=> TASK: Add some icons to the backward-compatible list

packages/neos-ui/src/manifest.js
=> BUGFIX: scroll newly created content node into view

packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js, packages/neos-ui-guest-frame/src/dom.js, packages/neos-ui-guest-frame/src/initializeContentDomNode.js, packages/neos-ui-guest-frame/src/style.css
=> FEATURE: Re-create the not-inline-editable overlay

packages/neos-ui-editors/src/DateTime/helpers.js, packages/neos-ui-editors/src/DateTime/index.js, packages/react-ui-components/src/DateInput/dateInput.js, packages/react-ui-components/src/DateInput/index.story.js
=> TASK: add support for `format` option in the date editor

packages/react-ui-components/src/Tabs/tabs.js
=> TASK: fix tab fallback logic

packages/react-ui-components/src/DateInput/style.css
=> BUGFIX: removed fixed width from the datetime editor

packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/index.js, packages/react-ui-components/src/DropDown/wrapper.js
=> BUGFIX: close DimensionSwitcher on select

packages/neos-ui-redux-store/src/CR/Nodes/selectors.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/style.css, packages/neos-ui/src/Containers/RightSideBar/Inspector/SelectedElement/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/SelectedElement/style.css, packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
=> FEATURE: Implement "Selected Element" for inspector

packages/neos-ui-ckeditor-bindings/src/ckeditor/neosPlaceholder.js, packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
=> BUGFIX: Fix placeholder plugin for CKEditor to respect the autoParagraph option

packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/index.js, packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/model.js
=> BUGFIX: Fix handling of initial aspect ratio strategy in image cropper

packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/AddNode/index.js, packages/neos-ui-redux-store/src/CR/Nodes/selectors.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/AddNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
=> FEATURE: Disable "Add" button, if no node type options are available

packages/neos-ui/src/Containers/RightSideBar/Inspector/SelectedElement/style.css
=> TASK: Add horizontal padding to SelectedElement.content

packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css
=> BUGFIX: Adjust min-width of the publish button to match the old ui

Tests/IntegrationTests/contentModule.js, package.json, packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui/src/Containers/Modals/NodeVariantCreationDialog/index.js, packages/neos-ui/src/Sagas/CR/ContentDimensions/index.js
Steps to reproduce: try to switch dimensions on the demo site and watch the console.
TODO:
=> BUGFIX: fix dimension switching

Build/TravisCi/InstallScripts/IntegrationTests.sh, Tests/IntegrationTests/contentModule.js
This bug causes us some pain sometimes, so let's find a way around it:
DevExpress/testcafe#1842
=> TASK: make e2e tests more structured and robust

Build/TravisCi/InstallScripts/IntegrationTests.sh, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js, packages/react-ui-components/src/Tree/node.css, packages/react-ui-components/src/Tree/node.js, packages/react-ui-components/src/Tree/tree.css
=> BUGFIX:  Orange change indicator should be aligned left

Classes/Neos/Neos/Ui/Fusion/Helper/ModulesHelper.php, Resources/Private/Fusion/Backend/Root.fusion
Fixes: #1109 
Adjust to ModulePrivilege change
http://neos.readthedocs.io/en/stable/Appendixes/ReleaseNotes/320.html#add-moduleprivilege-to-protect-neos-backend-modules
=> BUGFIX: fix menu permissions

Classes/Neos/Neos/Ui/Fusion/Helper/PositionalArraySorterHelper.php, Configuration/Settings.yaml, Resources/Private/Fusion/Backend/Root.fusion
=> BUGFIX: sort nodetype groups

packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui-backend-connector/src/FetchWithErrorHandling/index.js, packages/neos-ui/src/index.js
=> TASK: catch errors and display flash message for failed endpoint requests

packages/neos-ui/src/Containers/Modals/NodeVariantCreationDialog/index.js, packages/neos-ui/src/Containers/Modals/NodeVariantCreationDialog/style.css
=> TASK: fix styling of NodeVariantCreationDialog

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js, packages/react-ui-components/src/SelectBox/selectBox.js
=> TASK: automatically focus the insert link dialog

packages/neos-ui-ckeditor-bindings/src/ckeditor/neosPlaceholder.js
we had a null pointer error in the console without this check in some cases
=> BUGFIX: make placeholder handling more robust

packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
=> TASK: Reset state of NodeCreationDialog on back

packages/neos-ui/src/Sagas/CR/NodeOperations/addNode.js, packages/neos-ui/src/Sagas/UI/ContentCanvas/index.js
=> BUGFIX: trigger ContentCanvas.startLoading only when creating document nodes

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js, packages/neos-ui-editors/src/Editors/Reference/ReferenceOption.js, packages/neos-ui-editors/src/Editors/Reference/index.js, packages/neos-ui-editors/src/Editors/Reference/style.css
=> FEATURE: Display Node Path in reference editor

packages/neos-ui-editors/src/EditorEnvelope/index.js, packages/neos-ui-editors/src/Editors/TextField/index.js, packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js, yarn.lock
=> FEATURE: Submit NodeCreationDialog on Enter

packages/neos-ui/src/Containers/ContentCanvas/index.js
Forms (e.g. search form) should be allowed inside the iframe.
=> TASK: Allow forms in content canvas

packages/react-ui-components/src/CheckBox/style.css, packages/react-ui-components/src/DateInput/style.css
adresses #1166 
Fixes the first and third mentioned issue there.
I can't reproduce the second one so it's hard to fix this.
=> BUGFIX: Various UX glitches

packages/neos-ui/src/Containers/LeftSideBar/NodeTree/style.css, yarn.lock
=> BUGFIX: set pageTree height explicit

packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/style.css
=> BUGFIX: Set border-right of DimensionSwitcher

packages/neos-ui/src/styleHostOnly.css
Quick reset for button border-radius until normalize.css is updated #1180
=> BUGFIX: Reset border-radius for button

packages/neos-ui/src/Containers/LeftSideBar/NodeTree/style.css
=> BUGFIX: fix PageTree expand

packages/react-ui-components/src/SelectBox/style.css
=> TASK: Set text-overflow mode for selectbox

packages/neos-ui-editors/src/Editors/Image/Components/Controls/index.js
=> BUGFIX: Correct translation for choose image

packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
=> TASK: Set sensible tooltip title to CKE instances

packages/neos-ui-editors/src/Editors/References/index.js, packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js
=> FEATURE: use ReferenceOption in References Editor

packages/neos-ui-decorators/src/neos.js, packages/react-ui-components/src/_lib/injectProps.js
Here is an example how the changes in here can be used:
https://github.com/sandstorm/NodeTreeStyling
=> TASK: Improve unplanned extensibility

Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php, Classes/Neos/Neos/Ui/Domain/Service/UserLocaleService.php, Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
=> TASK: Respect language set in user settings

packages/neos-ui-ckeditor-bindings/src/guestFrameApi.js
=> TASK: Disable ckeditor context menu

packages/react-ui-components/src/Dialog/dialog.js
=> TASK: Only show the close button in a dialog if it is set

packages/neos-ui-editors/src/Editors/Image/index.js
=> BUGFIX: ImageEditor does not respect feature settings

Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php, packages/neos-ui-guest-frame/src/initializeGuestFrame.js
=> TASK: Remove inline script tags after initialization

README.md
Use also yarn command for starting the watcher like in the section Development commands
=> TASK: Use yarn instead of npm

packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/style.css
I don't think we have to fix the dot-replacement. the correct key helps here ;)
For issue #1216
=> TASK: Fixing translationkeys in usersettings dropdown

packages/neos-ui-editors/src/Editors/Reference/createNew.js, packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js
=> BUGFIX: Make createNew optional in all selects

packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/index.js, packages/neos-ui-editors/src/manifest.js, packages/neos-ui/src/manifest.dataloaders.js
Adds the AssetEditor for the inspector.
Resolves: #876
=> FEATURE: AssetEditor

packages/react-ui-components/src/reset.css
=> BUGFIX: Default browser styles should be reset

Configuration/Routes.Backend.yaml
=> TASK: Append exceeding arguments for host frame route

packages/neos-ui-editors/src/Editors/AssetEditor/Components/Controls/index.js, packages/neos-ui-editors/src/Editors/AssetEditor/Components/Controls/style.css, packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/AssetEditor/style.css
This adds asset selection and file upload to the asset list editor.
It's also possible to just drag files onto the asset list.
#resolves: #1304 #1306
=> FEATURE: Add file upload and asset selection in asset list editor

packages/neos-ui-editors/src/Editors/Reference/style.css
Adjust color scheme to the old UI.
Fixes: #1330
=> TASK: Improve text color contrast for reference options

packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/Reference/referenceDataLoader.js
Fixes: #1331
Fixes a few bugs:
- handle single asset uploads
- fix Image uploads
- fix loading indicator
Not fixed:
=> BUGFIX: fix AssetEditor to support single assets

Configuration/Routes.Service.yaml, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js, packages/react-ui-components/src/Icon/__snapshots__/icon.spec.js.snap, packages/react-ui-components/src/Icon/icon.js, packages/react-ui-components/src/Tree/node.css
TODO for later: find out how come the tests pass with warnings in the console.
=> TASK: various small fixes

packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js, packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js, packages/neos-ui/src/Sagas/UI/ContentCanvas/index.js
=> BUGFIX: Display Re-login dialog, if iframe is about to load login page

packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css, packages/react-ui-components/src/DropDown/style.css
- Border between items
- Shadow under the dropdown
=> TASK: adjust styles of the publish menu

packages/neos-ui-editors/src/Editors/NodeType/index.js
Not the cleanest fix, but I think it's good enough workaround for this edge case.
Fixes: #1351
=> BUGFIX: fix changing nodetype of a site node

packages/react-ui-components/src/Tree/node.css, packages/react-ui-components/src/Tree/node.js
=> BUGFIX: fix horizontal scrolling in the tree

packages/build-essentials/src/styleConfig.js, packages/neos-ui/src/Containers/FlashMessages/style.css
=> BUGFIX: fix z-index of flashMessage

packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/style.css, packages/neos-ui/src/Containers/FullScreen/style.css
=> BUGFIX: fix various z-index regressions

Resources/Private/Fusion/Backend/Root.fusion, packages/neos-ui-decorators/src/neos.js, packages/neos-ui-editors/src/SecondaryEditors/MediaDetailsScreen/index.js, packages/neos-ui-editors/src/SecondaryEditors/MediaSelectionScreen/index.js, packages/neos-ui/src/Containers/Neos/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js, packages/neos-ui/src/Containers/Root.js, packages/neos-ui/src/index.js
Resolves: #1379 
Resolves: #1372
=> TASK: replace hardcoded urls and add link to workspace review

Resources/Private/Translations/en/Main.xlf, packages/build-essentials/src/styles/styleConstants.js, packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js, packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/Link/index.js, packages/neos-ui-editors/src/Editors/Reference/index.js, packages/neos-ui-editors/src/Editors/Reference/referenceDataLoader.js, packages/neos-ui-editors/src/Editors/References/index.js, packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js, packages/neos-ui-editors/src/Editors/SelectBox/SimpleSelectBoxEditor.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeFilter/index.js, packages/react-ui-components/src/SelectBox/selectBox.js, packages/react-ui-components/src/SelectBox/selectBox.spec.js, packages/react-ui-components/src/SelectBox_ListPreview/selectBox_ListPreview.js
Also fix some bugs along the way.
=> FEATURE: add "not found" and "left to type" to SelectBox

README.md
=> TASK: Add integration test command to README

packages/neos-ui-editors/src/Editors/NodeType/index.js, packages/react-ui-components/src/SelectBox/style.css, packages/react-ui-components/src/SelectBox_ListPreviewGrouped/selectBox_ListPreviewGrouped.js, packages/react-ui-components/src/reset.css
=> TASK: implement groups in SelectBox

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/style.css, packages/react-ui-components/src/SelectBox/style.css, packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js, packages/react-ui-components/src/SelectBox_Header/style.css
references #1408 
Before:
After:
Before:
After:
Before:
After:
=> TASK: Various tiny visual regressions

packages/neos-ui/src/Containers/PrimaryToolbar/EditModePanelToggler/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/EditModePanelToggler/style.css, packages/neos-ui/src/Containers/PrimaryToolbar/LeftSideBarToggler/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/LeftSideBarToggler/style.css
=> BUGFIX: fix bottom border of toolbar toggles

packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/AspectRatioDropDown/index.js, packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js, packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/model.js
=> BUGFIX: fix locked aspect ratio in ImageCropper

packages/neos-ui-editors/src/Editors/AssetEditor/Components/Controls/index.js, packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/Image/Components/Controls/index.js, packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/index.js, packages/neos-ui-editors/src/Editors/Image/index.js, packages/neos-ui-editors/src/Library/AssetUpload.js
=> TASK: Implement new ImageEditor and AssetEditor features

packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/AssetEditor/style.css, packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/index.js, packages/neos-ui-editors/src/Library/AssetUpload.js
The ``AssetList`` component now wrapped within the ``AssetUpload`` component which now supports drag & drop for multiple files.
This is a refactoring following https://github.com/neos/neos-ui/pull/1316 where drag & drop for the ``AssetList`` was introduced. Now the code is much more streamlined with other components that use drag & drop for assets like https://github.com/neos/neos-ui/blob/master/packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/index.js#L41-L55
=> TASK: Utilize ``AssetUpload`` component

packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
=> BUGFIX: CKE placeholder is rendered as undefined when not set

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js, packages/neos-ui-ckeditor-bindings/src/manifest.formattingRules.js, packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/Link/index.js, packages/neos-ui-editors/src/Editors/Reference/index.js, packages/neos-ui-editors/src/Editors/References/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js, packages/react-ui-components/src/SelectBox/selectBox.js
Fixes: #1431 and many other issues, see commits
=> BUGFIX: fix all sorts of SelectBox-related regressions

packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
=> BUGFIX: Show information about target workspace in Publish Button

packages/neos-ui-editors/src/Editors/AssetEditor/index.js
Also accidentally Fixes: #1435
=> BUGFIX: fix single AssetEditor

Classes/Neos/Neos/Ui/Domain/Model/Changes/Property.php
=> BUGFIX: Let NodeType change clean properties and childNodes

packages/neos-ui-editors/src/Editors/AssetEditor/Components/Controls/index.js, packages/neos-ui-editors/src/Editors/AssetEditor/Components/Controls/style.css, packages/neos-ui-editors/src/Editors/Image/Components/Controls/style.css
=> BUGFIX: Overwrite styling to have margin in control buttons

packages/react-ui-components/src/ListPreviewElement/style.css
on isHighlighted state
closes #1476
=> BUGFIX: Set the color of every containing span to white

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js, packages/neos-ui-editors/src/Editors/Link/index.js
=> BUGFIX: allow anchors in Link Editor

packages/neos-ui-validators/src/RegularExpression/index.js
=> BUGFIX: make RegularExpression validator more close to old behavior and more robust

Configuration/Settings.yaml, packages/neos-ui-redux-store/src/UI/LeftSideBar/index.js
=> BUGFIX: Remember collapse state of content tree

packages/react-ui-components/src/SelectBox_ListPreviewFlat/selectBox_ListPreviewFlat.js, packages/react-ui-components/src/SelectBox_ListPreviewGrouped/selectBox_ListPreviewGrouped.js
=> BUGFIX: Let selectbox scroll when navigating via keyboard

Build/createVersionFile.sh, Build/fillVersion.sh, package.json, packages/neos-ui/src/Containers/Drawer/index.js, packages/neos-ui/src/Containers/Drawer/style.css, packages/utils-helpers/src/getVersion.js, packages/utils-helpers/src/getVersion.spec.js, packages/utils-helpers/src/index.js
I'm not entirly sure if this is the correct place to call this script.
Otherwise I think it's working fine.
closes #1478
=> FEATURE: Version Information

packages/neos-ui-editors/src/Library/AssetUpload.js
=> BUGFIX: upload files in direct order in AssetUpload

packages/neos-ui-editors/src/Editors/Reference/referenceDataLoader.js
=> TASK: Respect `startingPoint` in ReferenceDataLoader

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js, packages/neos-ui-containers/src/InsertModeSelector/index.js, packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/Link/index.js, packages/neos-ui-editors/src/Editors/Reference/index.js, packages/neos-ui-editors/src/Editors/References/index.js, packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js, packages/neos-ui-editors/src/Editors/SelectBox/SimpleSelectBoxEditor.js, packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeFilter/index.js, packages/neos-ui/src/Containers/Modals/InsertMode/index.js
Depends on https://github.com/neos/neos-development-collection/pull/1829
=> TASK: move labels back to Neos.Neos package

package.json, yarn.lock
Upgrading to normalize.css version 7.0.0
Fixes: #1513
=> TASK: Update normalize.css to version 7

.travis.yml
Try to fix the connection to chrome while using xvfb.
Fixes: #1543
=> TASK: Add xvfb service and start webserver

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
I copied the ones from neos-development-collection and
adjusted them when I thought it was helpful.
I removed the checklist in ISSUE_TEMPLATE, especially the test part because I think we shouldn't bother our nice contributors to write tests if we didn't do it ourselves consequently (ofc this have/should be added later)
I didn't copied over the CONTRIBUTING.md because I think
this need a bit more adjustment.
I will try to add/adjust more documentation soonish to make contributing for outsiders as easy as possible.
=> TASK: Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

packages/react-ui-components/package.json
=> TASK: Cleanup the react-ui-components package.json

package.json, yarn.lock
=> TASK: Remove unused package lolex

package.json, yarn.lock
=> TASK: Remove unused skin-deep package

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/style.css
I'm sure this isn't the best possible solution but I didn't came up with anything else working.
So if you have an idea which might work let me know :)
closes #1528
=> BUGFIX: Add 10px in order to fit the SelectBoxHeader inside the box

package.json, packages/build-essentials/package.json, packages/build-essentials/yarn.lock, packages/react-ui-components/package.json, packages/react-ui-components/yarn.lock, yarn.lock
=> TASK: Update cross-env to version 5.1.3

package.json, yarn.lock
=> TASK: Update browser-env to the latest version

packages/neos-ui/src/Containers/EditModePanel/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/EditModePanelToggler/index.js
**What I did**
Duplicate of https://github.com/neos/neos-ui/pull/1515
=> BUGFIX: Render Preview/Editing mode panel with at least one mode

packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js
=> BUGFIX: Make external Links in CKEditor possible

packages/react-ui-components/src/Button/style.css, packages/react-ui-components/src/DropDown/style.css
=> TASK: Enable focus indicator

packages/neos-ui/src/Containers/FullScreen/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/ToggleContentTree/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/FullScreenButton/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/PreviewButton/index.js
- add aria-label to PreviewButton and FullScreenButton
**What I did**
Added aria-label information to buttons
Buttons should have an aria-label and screenreader should announce it on focus
Refs: #1592
=> TASK: Add labels to Buttons

Tests/IntegrationTests/contentModule.js, packages/neos-ui-redux-store/src/CR/Workspaces/index.js, packages/neos-ui/src/Containers/Modals/DiscardDialog/index.js, packages/neos-ui/src/Containers/Modals/DiscardDialog/style.css, packages/neos-ui/src/Containers/Modals/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js, packages/neos-ui/src/Sagas/Publish/index.js, packages/neos-ui/src/manifest.containers.js, packages/neos-ui/src/manifest.sagas.js
Resolves: #1387
It prompts for discard confirmation both for discard and discard all.
=> FEATURE: ask for confirmation before discarding

packages/neos-ui/src/Containers/Modals/DiscardDialog/index.js
Sorry, forgot to push before merge
=> TASK: add I18n fallback to discard dialog

Resources/Private/Fusion/Backend/Root.fusion, package.json, packages/neos-ui-backend-connector/src/Endpoints/Helpers.js, packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui-redux-store/src/CR/ContentDimensions/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/index.js, packages/react-ui-components/src/ListPreviewElement/listPreviewElement.js, packages/react-ui-components/src/ListPreviewElement/style.css, packages/react-ui-components/src/SelectBox/selectBox.js, packages/react-ui-components/src/SelectBox_Option_SingleLine/selectBox_Option_SingleLine.js
Fixes: #1611
See issue for ways to test.
=> FEATURE: dynamic updating of dimension constraints

Classes/Neos/Neos/Ui/Domain/Model/Changes/Property.php, Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php, packages/neos-ui/src/Sagas/UI/Inspector/index.js, packages/neos-ui/src/manifest.js
=> FEATURE: handle `reloadIfChanged` correctly, without full page reload

packages/neos-ui-guest-frame/src/initializeGuestFrame.js
=> TASK: Handle tab key as well as a mouse click to focus the selected node

packages/build-essentials/src/styles/styleConstants.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeFilter/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/style.css, packages/react-ui-components/src/SelectBox/style.css
=> TASK: Make NodeTreeFilter more robust

packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/style.css, packages/neos-ui/src/Containers/LeftSideBar/index.js
=> TASK: Small css hacks for various styling issues

package.json, yarn.lock
This introduces many new warnings like 'no-unused-vars' for React (see
Travis output). I'm not sure if we should go this way because that
would mean all no-unused-vars errors will be overseen more likely in the
future.
=> TASK: Update eslint config

packages/neos-ui/src/Containers/ContentCanvas/index.js
=> BUGFIX: correct jsx in ContentCanvas

Resources/Private/Templates/Backend/GuestNotificationScript.html, package.json, packages/neos-ui/src/index.js, polyfills.js, webpack.config.js, yarn.lock
=> BUGFIX: fix IE11 support

Classes/Neos/Neos/Ui/Controller/BackendServiceController.php, Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/Redirect.php
... some bigger customers still run PHP 7.0; so we can help them a little ;)
=> BUGFIX: remove PHP7.0-incompatible return types

Configuration/Settings.yaml
Adds positional sorting to the `editPreviewModes` frontend configuration.
Fixes #1658
=> BUGFIX: Add positional sorting to edit / preview modes

packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/react-ui-components/src/Frame/frame.js
The preview height/width will now be correctly set to the
HTML tag of the iframe
closes #1642
=> BUGFIX: Show scrollbars if previewmode is bigger than screen

Classes/Neos/Neos/Ui/ContentRepository/Service/WorkspaceService.php
=> (Event Sourced CR) TASK: Get Changes from ChangesProjection

Classes/Neos/Neos/Ui/Controller/BackendController.php, Classes/Neos/Neos/Ui/Fusion/Helper/SitesHelper.php, Configuration/Settings.yaml, packages/neos-ui-guest-frame/src/initializeGuestFrame.js, packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js, packages/neos-ui/src/Sagas/Browser/index.js
=> (Event Sourced CR) BUGFIX: fix URL handling in Neos UI

packages/build-essentials/src/webpack.config.js
=> BUGFIX: Fix if no webpack config is available

.gitignore, README.md, packages/build-essentials/src/webpack.config.js
Someone needed this at the sprint while working on the UI and I thought it is might be needed for othes too.
=> TASK: Make webpack livereload options configurable

Classes/Neos/Neos/Ui/ContentRepository/Service/WorkspaceService.php, Classes/Neos/Neos/Ui/Controller/BackendServiceController.php, Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php, Classes/Neos/Neos/Ui/Fusion/Helper/WorkspaceHelper.php, Configuration/Routes.Service.yaml, Resources/Private/Fusion/Backend/Root.fusion, packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui/src/Sagas/Publish/index.js
=> (Event Sourced CR) TASK: Introduce publishAll for workspaces

Classes/Neos/Neos/Ui/Domain/Service/CommandOverviewService.php
This service should return an array with the unpublished changes of the current workspace.
This service will be extended with needed features in the futue.
=> TASK: Add CommandOverviewService

package.json, packages/react-ui-components/package.json, packages/react-ui-components/src/SelectBox/selectBox.js
=> BUGFIX: make SelectBox work with non-string values

Makefile
to prevent MacOS errors while testing
@markusguenther Could you test this? :)
=> BUGFIX: Add Lerna alias to Makefile

packages/neos-ui-guest-frame/src/initializeGuestFrame.js
=> BUGFIX: retain url params in urls

packages/neos-ui/src/Containers/ContentCanvas/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js, packages/react-ui-components/src/Frame/frame.js
=> BUGFIX: fix loading indicator when navigating inline

packages/neos-ui-guest-frame/src/InlineUI/index.js
=> BUGFIX: don't show NodeToolbar for document nodes

Resources/Private/Fusion/Backend/Root.fusion
=> BUGFIX: Fix hideInMenu setting for submodules

Tests/IntegrationTests/contentModule.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeFilter/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeSearchInput/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/AddNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CopySelectedNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CutSelectedNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/DeleteSelectedNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/HideSelectedNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/PasteClipBoardNode/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/RefreshPageTree/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/ToggleContentTree/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js, packages/neos-ui/src/Containers/Modals/DeleteNode/index.js, packages/neos-ui/src/Containers/Modals/DiscardDialog/index.js, packages/neos-ui/src/Containers/Modals/InsertMode/index.js, packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js, packages/neos-ui/src/Containers/Modals/NodeVariantCreationDialog/index.js, packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js, packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js, packages/neos-ui/src/Containers/Modals/UnappliedChangesDialog/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/EditModePanelToggler/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/LeftSideBarToggler/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/MenuToggler/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js, packages/neos-ui/src/Containers/RightSideBar/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/FullScreenButton/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/PreviewButton/index.js
Add ids to most elements. Would help to simplify E2E tests. Also needed for some 3rd-party integrations.
=> TASK: add ids

packages/neos-ui-guest-frame/src/initializeGuestFrame.js, packages/neos-ui-redux-store/src/CR/Nodes/index.js, packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/index.js
=> BUGFIX: fix CKE toolbar for properties of documentNode

packages/neos-ui-guest-frame/src/initializeGuestFrame.js
Fixes https://github.com/neos/neos-ui/pull/1712#issuecomment-375562925
=> BUGFIX: only re-focust when selecting a different node

packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
=> BUGFIX: keep toggled state of inspector panels in state

packages/neos-ui-editors/src/Editors/MasterPlugin/index.js, packages/neos-ui-editors/src/Editors/PluginView/index.js
=> BUGFIX: fix plugin editors

packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
=> BUGFIX: correctly position toolbar on narrow elements

packages/neos-ui-decorators/src/index.js, packages/neos-ui-decorators/src/withDragDropContext.js, packages/neos-ui/src/Containers/Root.js
E.g. it's needed to make MultiSelectBox work in the strucutred editing
package.
=> TASK: put dnd context into a decorator, so it could also be used from external packages

packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js, packages/neos-ui/src/Sagas/UI/ContentCanvas/index.js, packages/neos-ui/src/manifest.js, packages/neos-ui/src/manifest.sagas.js
=> TASK: reload contentcanvas when clicking on current document node

package.json, yarn.lock
=> TASK: Update to normalize.css version 8

packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
=> BUGFIX: make inspector loading more robust with no focusedNode

packages/neos-ui-editors/src/SecondaryEditors/MediaDetailsScreen/index.js
=> BUGFIX: fix saving asset information in MediaDetailsScreen

Classes/Neos/Neos/Ui/Controller/BackendServiceController.php, Classes/Neos/Neos/Ui/Domain/Model/AbstractChange.php, Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractStructuralChange.php, Classes/Neos/Neos/Ui/Domain/Model/Changes/Property.php, Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/ReloadDocument.php, packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js, packages/neos-ui/src/Sagas/UI/ContentCanvas/index.js, packages/neos-ui/src/manifest.js
Fixes: #1612 
Resolves: #1818 
Fixes: #1819
=> BUGFIX: fix 404 on uriPathSegment change

Tests/IntegrationTests/contentModule.js, packages/neos-ui-guest-frame/src/dom.js, packages/neos-ui-guest-frame/src/initializeGuestFrame.js, packages/neos-ui/src/Sagas/UI/ContentTree/index.js, packages/neos-ui/src/manifest.js
Resolves: #754 
Docs update: https://github.com/neos/neos-development-collection/pull/2046
=> FEATURE: implement backwards-compatible guest frame events API

packages/positional-array-sorter/src/positionalArraySorter.js
=> BUGFIX: make positionalArraySorter more robust

Configuration/Settings.yaml, packages/neos-ui/src/Registry/HotkeyRegistry.js, packages/neos-ui/src/Registry/index.js, packages/neos-ui/src/manifest.hotkeys.js
This was an alternative try to #1835 for solving #1823
=> FEATURE: Make keyboard shortcuts configurable via Settings.yaml

packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
=> TASK: Show the NodeType Title on Tree-Hover

Resources/Private/Fusion/Prototypes/Page.fusion
Those elements are not needed in the frontend.
=> Render additional elements for UI only in backend

Classes/Neos/Neos/Ui/Fusion/Helper/ActivationHelper.php, Classes/Neos/Neos/Ui/TypeConverter/UiDependentImageSerializer.php, Resources/Private/Fusion/Prototypes/GlobalCacheIdentifiers.fusion, Resources/Private/Fusion/Prototypes/Page.fusion, Resources/Private/Fusion/Prototypes/Shortcut.fusion
Simply because it does not enable anything.
=> TASK: Change enableNewBackend() to isLegacyBackendEnabled()

packages/react-ui-components/src/SelectBox_Option_SingleLine/selectBox_Option_SingleLine.js
=> BUGFIX: fix disabled state in DimensionSelector

packages/react-ui-components/src/SelectBox/selectBox.js, packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js
nothing happened when resetting a selecbox
=> BUGFIXING: SelectBox onReset call function

package.json, packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/index.js
Sort the options in the dimension menu for better user experience with many dimension values (more then 50 languages for example).
=> FEATURE: sort options in dimension menu

packages/neos-ui/src/Containers/SecondaryToolbar/PreviewButton/index.js
I don't know about security here, if someone has an opinion about
that let me know :)
closes #1749
=> BUGFIX: Open preview in same tab

packages/neos-ui-editors/src/Editors/AssetEditor/index.js
=> BUGFIX: Fix object traversal in AssetEditor (#1885)

packages/react-ui-components/src/CheckBox/checkBox.js
`disabled` is not used in the code and should be removed.
=> TASK: Remove unused property disabled

packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css, packages/react-ui-components/src/DropDown/header.js, packages/react-ui-components/src/Icon/icon.js, packages/react-ui-components/src/Icon/style.css
=> Tweak UX-Issues on PublishDropDown

package.json, packages/neos-ui-decorators/package.json, yarn.lock
=> TASK: Update reselect to 3.0.1

Build/Jenkins/release-neos-ui.sh
I'm not sure if we should do that as this should already be done via travis and so would extend the actual release time with tasks that are already done.
Any thoughts on this?
=> TASK: Let jenkins test before releasing

package.json, packages/react-ui-components/package.json, yarn.lock
Updating the libray to version 4.0.3.
Resolves: #1920
=> TASK: Update react-collapse to version 4.0.3

packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/index.js, packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/style.css, packages/neos-ui-editors/src/Library/AssetUpload.js, packages/neos-ui/src/Containers/Drawer/MenuItem/index.js, packages/neos-ui/src/Containers/Drawer/MenuItemGroup/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js, packages/neos-ui/src/index.js, packages/react-ui-components/src/Icon/icon.js, packages/react-ui-components/src/Icon/style.css
=> TASK: Add Hover to PreviewScreen

packages/react-ui-components/src/Tabs/style.css
=> TASK: Add hover styles to inspector tabs

Classes/Aspects/AugmentationAspect.php, Classes/Controller/BackendController.php, Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php, Classes/Fusion/Helper/NodeInfoHelper.php, Configuration/Routes.Backend.yaml, Configuration/Settings.yaml, packages/neos-ui/src/Sagas/Publish/index.js, packages/neos-ui/src/Sagas/UI/PageTree/index.js
Refactors the NodeInfoHelper for better readability and
at the same time improves loading speed by removing
previewUris and adapting the uris to use a "jump url"
which is generated very cheaply.
Related: #1579
=> TASK: Improve NodeInfoHelper and loading speed

README.md
=> DOCS: Document new and better release process

packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/style.css
=> TASK: Add transition to previewscreen overlay

packages/react-ui-components/src/ButtonGroup/buttonGroup.js, packages/react-ui-components/src/ButtonGroup/buttonGroupItem.js, packages/react-ui-components/src/CheckBox/checkBox.js, packages/react-ui-components/src/IconButtonDropDown/dropDownItem.js, packages/react-ui-components/src/ListPreviewElement/listPreviewElement.js, packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js, packages/react-ui-components/src/Tree/tree.js
Convert a bunch of components to stateless components whenever possible.
=> TASK: Use stateless compoents

package.json, yarn.lock
=> TASK: Remove imports-loader

package.json, packages/react-ui-components/package.json, yarn.lock
=> TASK: Remove object-assign library

package.json, yarn.lock
=> TASK: Remove lolex package

package.json, yarn.lock
=> TASK: Update regenerator-runtime to version 0.12.0

packages/neos-ui/src/Containers/LeftSideBar/style.css
=> BUGFIX: Fix flex behavior for document and structure tree

packages/react-ui-components/src/SelectBox_CreateNew/selectBox_CreateNew.js, packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js, packages/react-ui-components/src/SelectBox_HeaderWithSearchInput/selectBox_HeaderWithSearchInput.js, packages/react-ui-components/src/SelectBox_ListPreview/selectBox_ListPreview.js, packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/selectBox_Option_MultiLineWithThumbnail.js, packages/react-ui-components/src/SelectBox_Option_SingleLine/selectBox_Option_SingleLine.js, packages/react-ui-components/src/Tree/node.js
Convert the remaining possible classes to stateless components
=> TASK: Convert to Stateless components

packages/neos-ui/src/Sagas/CR/Policies/index.js
The policies saga needs to catch all relevant events and shouldn't
be blocking, therefore refactoring while making sure that no nodes
are requested twice.
Resolves: #1985
=> BUGFIX: Do no load policies blocking

packages/neos-ui-editors/src/Editors/CodeMirror/index.js
=> BUGFIX: Remove unsupported style attribute from Icon component

Classes/Domain/Service/ConfigurationRenderingService.php, Classes/Fusion/RenderConfigurationImplementation.php
Found while trying to figure out how the config is being processed
=> TASK: Add typeHints and comments to configuration rendering classes

packages/react-ui-components/src/Badge/badge.js, packages/react-ui-components/src/Bar/bar.js, packages/react-ui-components/src/Button/button.js, packages/react-ui-components/src/ButtonGroup/buttonGroup.js, packages/react-ui-components/src/ButtonGroup/buttonGroupItem.js, packages/react-ui-components/src/CheckBox/checkBox.js, packages/react-ui-components/src/Dialog/dialog.js, packages/react-ui-components/src/DropDown/contents.js, packages/react-ui-components/src/DropDown/header.js, packages/react-ui-components/src/Headline/headline.js, packages/react-ui-components/src/Icon/icon.js, packages/react-ui-components/src/IconButton/iconButton.js, packages/react-ui-components/src/IconButtonDropDown/dropDownItem.js, packages/react-ui-components/src/Label/label.js, packages/react-ui-components/src/ListPreviewElement/listPreviewElement.js, packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js, packages/react-ui-components/src/SelectBox_CreateNew/selectBox_CreateNew.js, packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js, packages/react-ui-components/src/SelectBox_HeaderWithSearchInput/selectBox_HeaderWithSearchInput.js, packages/react-ui-components/src/SelectBox_ListPreview/selectBox_ListPreview.js, packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/selectBox_Option_MultiLineWithThumbnail.js, packages/react-ui-components/src/SelectBox_Option_SingleLine/selectBox_Option_SingleLine.js, packages/react-ui-components/src/SideBar/sideBar.js, packages/react-ui-components/src/Tabs/panel.js, packages/react-ui-components/src/Tooltip/tooltip.js, packages/react-ui-components/src/Tree/tree.js
Reconvert components to PureComponents.
See: https://neos-project.slack.com/archives/C0U0KEGDQ/p1531651056000027
=> TASK: Convert components to pure components

packages/neos-ui/src/Containers/SecondaryToolbar/KeyboardShortcutButton/index.js, packages/neos-ui/src/Containers/SecondaryToolbar/index.js, packages/neos-ui/src/manifest.hotkeys.js
This gives the ability to deactivate Keyboardshortcuts via `Settings.yaml` correctly.
e.g:
```
Neos:
Neos:
Ui:
frontendConfiguration:
hotkeys: ~
```
closes #2014
=> BUGFIX: Deactivate Keyboardshortcuts

packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/LinkButton.js, packages/neos-ui-ckeditor5-bindings/src/manifest.richtextToolbar.js, packages/utils-helpers/src/index.js, packages/utils-helpers/src/isEmail.js
What this PR does:
- cog icon instead of dots
- suggestions for email and http links
- don't create empty link on first link icon click
=> TASK: improve link editor

packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/LinkButton.js
=> TASK: Unlink a link if no value is set after apply

packages/neos-ui-guest-frame/src/initializePropertyDomNode.js
=> BUGFIX: prevent double init of inline editables

packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js, packages/neos-ui-extensibility/scripts/helpers/webpack.config.js, packages/neos-ui-extensibility/src/shims/neosProjectPackages/neos-ui-ckeditor5-bindings/index.js, packages/neos-ui/src/apiExposureMap.js
Also it attaches some useful information about the current editable property to its DOM node.
=> TASK: expose CKE5 bindings package

composer.json
For the last time we need to do it manually.
=> TASK: adjust neos-ui-compiled version

packages/neos-ui-ckeditor-bindings/src/guestFrameApi.js, packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js, packages/neos-ui/src/Sagas/Changes/index.js
Way to test: type a letter, wait 350ms for the request to start saving, type another letter while it's saving. The second request would not get triggered without this change.
=> BUGFIX: fix changes saga again

packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
=> BUGFIX: respect collapsed setting of nodetype group

packages/neos-ui-redux-store/src/CR/Nodes/index.js
=> BUGFIX: merge node children information correctly

packages/neos-ui-redux-store/src/UI/AddNodeModal/index.js, packages/neos-ui-redux-store/src/UI/AddNodeModal/index.spec.js, packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
Fix a comment by @bwaidelich https://github.com/neos/neos-ui/pull/2068#discussion_r209833603
=> TASK: rename collapsedGroups into toggledGroups

.travis.yml
This should solve your problem that `nvm` isn't correctly used in your PR #2079 @dimaip
=> TASK: Let travis use make

Classes/Domain/Model/Changes/AbstractCopy.php, Classes/Domain/Model/Changes/CopyAfter.php, Classes/Domain/Model/Changes/CopyBefore.php, Classes/Domain/Model/Changes/CopyInto.php
Addressing issue https://github.com/neos/neos-development-collection/issues/2089
=> BUGFIX: Force re generation of copied node names

packages/neos-ui/src/Containers/PrimaryToolbar/MenuToggler/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/MenuToggler/style.css
**What I did**
Add missing title to button and center menu icon to be in sync with old UI.
Before:
After:
=> TASK: Add title to menu button and fix styling

Classes/Domain/Model/Changes/AbstractCopy.php, Classes/Domain/Model/Changes/CopyAfter.php, Classes/Domain/Model/Changes/CopyBefore.php, Classes/Domain/Model/Changes/CopyInto.php
Make https://github.com/neos/neos-ui/pull/2078 permanent but without backward compatibility.
This change is _hypothetically_ braking, but definitely not critical.
=> TASK: Force re generation of copied node names - Cleanup

packages/neos-ui-redux-store/src/CR/ContentDimensions/index.js, packages/neos-ui-redux-store/src/CR/Images/index.js, packages/neos-ui-redux-store/src/CR/Nodes/index.js, packages/neos-ui-redux-store/src/CR/Nodes/selectors.js, packages/neos-ui-redux-store/src/CR/Workspaces/index.js, packages/neos-ui-redux-store/src/UI/Drawer/index.js, packages/neos-ui-redux-store/src/UI/EditModePanel/index.js, packages/neos-ui-redux-store/src/UI/FlashMessages/index.js, packages/neos-ui-redux-store/src/UI/FullScreen/index.js, packages/neos-ui-redux-store/src/UI/Inspector/index.js, packages/neos-ui-redux-store/src/UI/KeyboardShortcutModal/index.js, packages/neos-ui-redux-store/src/UI/NodeLinking/index.js, packages/neos-ui-redux-store/src/UI/RightSideBar/index.js, packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js, packages/utils-helpers/src/fromJSOrdered.js, packages/utils-helpers/src/index.js
Fixes: #2071
See: https://stackoverflow.com/questions/42617701/fromjs-to-nested-ordered-maps-with-immutable-js
=> BUGFIX: use ordered maps in immutable js

packages/neos-ui-redux-store/src/CR/Nodes/selectors.js, packages/react-ui-components/src/Icon/mapper.js
=> BUGFIX: display Invalid nodetypes in the tree

packages/neos-ui-editors/src/Editors/DateTime/index.js, packages/react-ui-components/src/DateInput/dateInput.js
Resolves: #1503
Fixes support for placeholder and minuteStep.
=> TASK: fix support for editorOptions of DateTime editor

packages/utils-helpers/src/isThenable.ts
Added typehints to `isThenable` function.
=> TASK: Convert isThenable to Typescript

packages/neos-ui-editors/src/Library/LinkInput.js
This is a regression after the recent refactoring.
=> BUGFIX: fix linking options

packages/build-essentials/src/styles/styleConstants.js, packages/neos-ui/src/Containers/Modals/UnappliedChangesDialog/style.css, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/AbstractButton/style.css, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css, packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/style.css, packages/neos-ui/src/Containers/RightSideBar/Inspector/style.css, packages/react-ui-components/src/DropDown/style.css
Added some important hover states for publish dropdown and publish button bottom right, see:
https://github.com/neos/neos-ui/issues/1471
=> Add missing hover states (#1471)

packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
The Button component has the property isDisabled and disabled
has been used.
Fix: #2195
=> BUGFIX: Adjust button property

Resources/Private/Fusion/Backend/Root.fusion, packages/neos-ui-backend-connector/src/Endpoints/index.js, packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui/src/manifest.dataloaders.js
This change adds asset sources support to the Asset Editor, which
allows for searching and importing remote assets on the fly.
This change relies on the new Asset Proxies web service endpoint in Neos.Neos.
https://github.com/neos/neos-development-collection/issues/2198
=> FEATURE: Add support for asset sources in asset editor

packages/build-essentials/src/styles/styleConstants.js, packages/neos-ui/src/Containers/PrimaryToolbar/style.css
=> TASK: Adjust PrimaryToolbar z-index

packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
Skip "new element" dialog if there is only one (allowed) Node Type
Issue https://github.com/neos/neos-development-collection/issues/2174
=> FEATURE: Skip 'new element' dialog if there is only one

packages/neos-ui-sagas/src/Publish/index.js
=> BUGFIX: fix previewUrl after publish

Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php, Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php, packages/neos-ui/src/manifest.js
=> BUGFIX: fix out of band rendering when creating new nodes

packages/neos-ui-guest-frame/src/dom.js, packages/neos-ui-redux-store/src/CR/Nodes/index.ts, packages/react-ui-components/src/Frame/frame.tsx
Fixes: #2114 
So far only tested in Edge, need to test with IE11 too.
=> BUGFIX: fix navigation in Edge

Tests/IntegrationTests/contentModule.js, packages/neos-ui-editors/src/Library/LinkInput.js
=> BUGFIX: safer way to access startingPoint in LinkEditor

packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
Apply this bugfix immediately, would cause loss of content if at least one emptish paragraph present in text!!!
=> BUGFIX: fix disasterous trimming of content URGENT!!!

packages/react-ui-components/src/TextArea/textArea.tsx
=> BUGFIX: fix value in TextArea element

packages/neos-ui-extensibility/scripts/helpers/webpack.config.js, packages/neos-ui-extensibility/src/shims/vendor/react-dnd-html5-backend/index.js, packages/neos-ui-extensibility/src/shims/vendor/react-dnd/index.js, packages/neos-ui/src/apiExposureMap.js
Needed for things like https://github.com/Flowpack/Flowpack.StructuredEditing/commit/89a1f52f122b7d4781ab8c0ae6ec6c3c320b9091
=> TASK: expose react-dnd packages

packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
Change logout icon in user dropdown to the real "sign-out" icon.
=> TASK: Change logout icon in user dropdown to the real "sign-out" icon

packages/react-ui-components/src/SelectBox_HeaderWithSearchInput/selectBox_HeaderWithSearchInput.js
Pass placeholderIcon down to SelectBox_HeaderWithSearchInput component, closes #2363
=> BUGFIX: Filter on top of page tree has search icon

packages/neos-ui-editors/src/Editors/MasterPlugin/index.js, packages/neos-ui-editors/src/Editors/PluginView/index.js
Fix issue https://github.com/neos/neos-ui/issues/2384
=> BUGFIX: Fix PluginView Editor

packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/index.js
Make option labels translatable
=> BUGFIX: Make DimensionSwitcher fully translatable

packages/neos-ui/src/manifest.js
This tweaks the error messages to "include their source".
=> TASK: Tweak error messages emitted by OoB rendering

packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/index.js
=> FEATURE: Search in dimension switcher

Configuration/Settings.yaml
=> BUGFIX: Remove SelectNodeTypeModal shortcuts

Classes/Fusion/Helper/NodeInfoHelper.php, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Rollback of https://github.com/neos/neos-ui/pull/2374 and re-implementation as colored clock-icon.
Fixes https://github.com/neos/neos-ui/issues/2387
=> BUGFIX: Show the hide before and after icon always

packages/neos-ui/src/manifest.js
=> BUGFIX: Don't remove still needed Empty-Collection overlays

.circleci/config.yml
=> Remoce CircleCi leftovers

package.json, yarn.lock
=> TASK: Update monet to version 0.9.0

packages/react-ui-components/src/Tabs/__snapshots__/tabs.spec.tsx.snap, packages/react-ui-components/src/Tabs/tabs.spec.tsx, packages/react-ui-components/src/Tabs/tabs.tsx
In order to fix https://github.com/psmb/Psmb.FlatNav/issues/2, we need to add styles to `<div role="tabpanel" …>`.
=> TASK: Added 'tabs__panel' class to TabsTheme

packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeFilter/style.css, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeSearchInput/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeSearchInput/style.css, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/style.css
=> BUGFIX: fix search field without icons and some jumping issues

Resources/Private/Templates/Backend/Partials/SplashScreen.html
Fixes https://github.com/neos/neos-development-collection/issues/2479
=> BUGFIX: Avoid PHP exception in NamespaceDetectionTemplateProcessor

packages/neos-ui-validators/src/Float/index.spec.js, packages/neos-ui-validators/src/Float/index.tsx
=> TASK: Correct float validation

packages/neos-ui-editors/src/Editors/AssetEditor/index.js
=> FIX: Correct dataLoader and add new asset

package.json, yarn.lock
Upgrading hashlru to new minor version
=> TASK: Upgrade hashlru to version 2.3.0

package.json, yarn.lock
=> TASK: Upgrade typesafe-actions to version 4.3.0

Resources/Private/Templates/Backend/Index.html, packages/neos-ui-containers/src/InsertModeSelector/index.js, packages/neos-ui-containers/src/InsertModeSelector/style.css, packages/neos-ui/src/Containers/EditModePanel/style.css, packages/neos-ui/src/Containers/LeftSideBar/style.css, packages/neos-ui/src/Containers/PrimaryToolbar/EditModePanelToggler/style.css, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css, packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/style.css, packages/neos-ui/src/Containers/RightSideBar/Inspector/style.css, packages/neos-ui/src/Containers/RightSideBar/style.css, packages/neos-ui/src/Containers/SecondaryToolbar/style.css, packages/react-ui-components/src/Bar/style.css, packages/react-ui-components/src/Dialog/style.css, packages/react-ui-components/src/SideBar/style.css
Make the backend responsive – finally. Starting by supporting tablets like the iPad.
=> FEATURE: Responsive Backend

Tests/IntegrationTests/e2e.sh
The end two end tests on master are broken.
The site pruning for the test-site fails.
=> BUGFIX: Fix end to end test on master

packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
fixes https://github.com/neos/neos-ui/issues/2444
=> TASK: Disable copy button in content tree if selected node is in page tree 

README.md
This should help newcomers (and everyone else) to write more meaningful PR and commit messages.
=> TASK: Link commit message guideline in readme

.github/stale.yml
Add Stalebot configuration.
See https://discuss.neos.io/t/rfc-introduce-stale-bot-on-dev-collections/4371
=> TASK: Add StaleBot configuration file

package.json, packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/model.js, packages/neos-ui/src/Containers/EditModePanel/index.js, packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js, packages/neos-ui/src/Registry/RichTextToolbarRegistry.js, yarn.lock
Just updates the currently outdated ramda dependency to version 0.26.1
=> TASK: Upgrade ramda to version 0.26.1

Classes/Controller/BackendServiceController.php
=> BUGFIX: Safeguard against missing parent node in discardAction()

Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js, Tests/IntegrationTests/Fixtures/1Dimension/richTextEditor.e2e.js, Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Document.Page.yaml, Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Document/Page/Page.fusion, packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/EditorToolbar.js, packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/Helpers/renderToolbarComponents.js, packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/LinkButton.js, packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/StyleSelect.js, packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/TableButton.js, packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/TableDropDown.js, packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/index.js, packages/neos-ui-ckeditor5-bindings/src/manifest.js, packages/neos-ui-ckeditor5-bindings/src/manifest.richtextToolbar.js, packages/neos-ui-editors/src/Editors/CKEditor/index.js, packages/neos-ui-editors/src/Editors/index.js, packages/neos-ui-editors/src/SecondaryEditors/CKEditorWrap/index.css, packages/neos-ui-editors/src/SecondaryEditors/CKEditorWrap/index.js, packages/neos-ui-editors/src/SecondaryEditors/index.js, packages/neos-ui-editors/src/index.js, packages/neos-ui-editors/src/manifest.js
Docs: https://github.com/neos/neos-development-collection/pull/2662
TODO:
Sample config for testing:
```
"Neos.NodeTypes.Html:Html":
properties:
source:
ui:
inspector:
editor: "Neos.Neos/Inspector/Editors/RichTextEditor"
editorOptions:
buttonLabel: i18n
placeholder: "<p>placeholder</p>"
autoparagraph: true
linking:
anchor: true
title: true
relNofollow: true
targetBlank: true
formatting:
strong: true
em: true
u: true
sub: true
sup: true
del: true
p: true
h1: true
h2: true
h3: true
h4: true
h5: true
h6: true
pre: true
underline: true
strikethrough: true
removeFormat: true
left: true
right: true
center: true
justify: true
table: true
ol: true
ul: true
a: true
```
=> FEATURE: CKE5 secondary inspector

.ecrc, .ecrc.json, .editorconfig, Makefile, package.json, yarn.lock
This uses the "new" editorconfig-checker with some more features :)
=> TASK: Use new editorconfig-checker

Tests/IntegrationTests/TestDistribution/composer.json
=> TASK: remove unneeded dependencies from the test distribution

packages/neos-ui-editors/src/Editors/Image/index.js
=> BUGFIX: Don't render cropping button for `svg`-files

packages/neos-ui/src/Containers/Drawer/VersionPanel/index.js, packages/neos-ui/src/Containers/Drawer/index.js, packages/neos-ui/src/Containers/Drawer/style.css, packages/neos-ui/src/manifest.containers.js
With this change additional components can be added via
the container registry. For example to provide application
specific version information or an agency logo.
=> FEATURE: Extensibility of version area in drawer

packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
=> BUGFIX: disable submiting inspector in invalid state with <enter>

README.md
**What I did**
Updated to correct install command for `dev-master`.
=> [TASK] Update install command for dev-master

Classes/Controller/BackendController.php
The correct preview of a hidden document is not showing it, after all…
See #2500
=> TASK: Remove showInvisible query parameter

Classes/Controller/BackendController.php, Classes/Fusion/Helper/NodeInfoHelper.php
Depends on neos/neos-development-collection#2654
Related: neos/neos-development-collection#2653
=> FEATURE: Custom Route for node preview

packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/index.js
=> BUGFIX: Trim search value for document search

packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
We have removed ramda as dependency and while doing
upmerges the changes collides somehow.
The commit:
https://github.com/neos/neos-ui/commit/c138b961444e9d80ba2afb56b840f0d50eb4f33d#diff-a7ae28cc7ab235343fc04fe7203f0b82R101
and the PR for removing ramda lead to that issue.
https://github.com/neos/neos-ui/pull/2578/files#
I compared the changes and fixed that somehow merge conflict.
=> BUGFIX: Reolve mistake while upmerging

packages/neos-ui-editors/src/Editors/AssetEditor/index.js
=> BUGFIX: AssetEditor selects are rendered without upload enabled

README.md, Tests/IntegrationTests/TestDistribution/composer.json, composer.json
Limit dependencies to 5.1 but don`t merge befor release of ui.
Otherwise the CircleCI will fail
=> TASK: Update dependencies to 5.1

packages/neos-ui-redux-store/src/UI/PageTree/selectors.ts
Resolves: #2620 
See the issue description how to test.
=> BUGFIX: disable deleting auto-created document nodes

packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
=> BUGFIX: Read the is hidden flag for content tree

Resources/Private/Fusion/Backend/Root.fusion, Tests/IntegrationTests/Fixtures/1Dimension/SitePackage/Resources/Private/Content/Sites.xml, Tests/IntegrationTests/Fixtures/1Dimension/treeMultiselect.e2e.js, packages/neos-ui/src/Containers/Modals/InsertMode/index.js
A number of things related to this feature: https://github.com/neos/neos-ui/pull/2568
- fix the InsertionModeModal label
- fix clipboardNodes session storage
- E2E tests
=> BUGFIX: follow-up on "batch operations on tree nodes" feature

packages/babel-preset-neos-ui/package.json, packages/build-essentials/package.json, packages/jest-preset-neos-ui/package.json, packages/neos-ui-extensibility/package.json, yarn.lock
Updates dependencies of babel-cli and babel-core to 6.26
=> TASK: Update babel core and babel-cli

packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js, packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/ToggleContentTree/index.js, packages/neos-ui/src/Containers/LeftSideBar/index.js, packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js, packages/react-ui-components/src/Tree/dragLayer.css, packages/react-ui-components/src/Tree/dragLayer.js, packages/react-ui-components/src/Tree/index.js, packages/react-ui-components/src/Tree/node.css, packages/react-ui-components/src/Tree/node.js, packages/react-ui-components/src/identifiers.ts
Based on feedback from guild-ux made the pointer arrow smaller and added transparency.
Also the drag preview is better positioned now beside the cursor.
=> FEATURE: custom DND animation for Tree

packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
=> BUGFIX: Only recalculate insertMode if allowed siblings or children really changed

README.md
Some steps on how to find out why a test is failing.
=> TASK: Add integration test debugging hints to readme

package.json, packages/build-essentials/package.json, packages/debug-reason-for-rendering/package.json, packages/neos-ui-extensibility/package.json, packages/positional-array-sorter/package.json, packages/react-ui-components/package.json
This helps to get more information when using npm or when searching on npmjs.com
=> TASK: Link repos in package.json files

packages/neos-ui-editors/src/Editors/Reference/referenceDataLoader.js
=> BUGFIX: Evaluate ClientEval also on load

package.json, yarn.lock
Upgrade the terser webpack plugin for security reasons.
For more information follow https://snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-570062
=> TASK: Upgrades terser-webpack-plugin

package.json, yarn.lock
Upgrading the codemirror package for security reasons and also upgrade the related react package.
=> TASK: Security upgrade codemirror

packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
=> BUGFIX: Apply default values in creation dialog

packages/neos-ui-backend-connector/src/Endpoints/Helpers.ts, packages/neos-ui-backend-connector/src/Endpoints/index.ts, packages/neos-ui-editors/src/Editors/AssetEditor/index.js, packages/neos-ui-editors/src/Editors/Image/index.js, packages/neos-ui-editors/src/SecondaryEditors/MediaSelectionScreen/index.js, packages/neos-ui/src/manifest.dataloaders.js, packages/utils-helpers/src/urlWithParams.spec.js, packages/utils-helpers/src/urlWithParams.ts
See neos/neos-development-collection#2984
=> FEATURE: Configurable Asset Constraints

packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/style.css
Followup to #2782, targeting 5.1
=> BUGFIX: Fix spacing on dimension-switcher dropdown

package.json, packages/react-ui-components/package.json, packages/react-ui-components/src/DateInput/__snapshots__/dateInput.spec.tsx.snap, packages/react-ui-components/src/ToggablePanel/__snapshots__/toggablePanel.spec.js.snap, yarn.lock
Upgrading react-collapse to the latest version for security reasons.
=> TASK: Upgrade react-collapse to version 5

Classes/Controller/BackendController.php
Adjusts the `BackendController::redirectToAction()` signature
Fixes: #2807
=> BUGFIX: Fix preview link behavior

Classes/ContentRepository/Service/NodeService.php, Classes/Controller/BackendController.php, Classes/Domain/Service/NodeTreeBuilder.php
I think the upmerge went wrong and we need this.
=> BUGFIX: pass presetBaseNodeType when redirecting

Classes/ContentRepository/Service/NodeService.php, Classes/Domain/Service/NodeTreeBuilder.php
**What I did**
Apply the style ci patch.
=> TASK: Apply to new style ci baseline

package.json, yarn.lock
**What I did**
Upgraded slugify to the latest version
Change the page title to a for instance Cyrillic name and update the uri path segment.
We also have a test for that in out end to end tests ;)
=> TASK: Upgrade slugify to version 1.1.0

package.json, packages/build-essentials/package.json, yarn.lock
To resolve a vulnerability issue we need to upgrade stylelint minimal to version 11
=> TASK: Upgrade stylelint to version 13.7.x

Makefile
When developing for the neos-ui it is maybe helpful to know what the commands are dooing and which commands exists.
**What I did**
Adding little comment to the makefile and render them.
Just enter `make` and or `make help`
=> TASK: Render little command explainations for make

Build/Jenkins/update-neos-ui-compiled.sh, README.md, Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestSite/composer.json, Tests/IntegrationTests/TestDistribution/composer.json
**What I did**
Added the new 7.0 branch to the ReadMe and the Jenkins scripts. Also nail the test distribution to the 7.0 version.
=> TASK: Prepare neos-ui for next major version

README.md
**What I did**
I have added a new environment variable to be able to invalidate circle ci caches manually.
Add some docs.
Just follow the docs ;)
=> TASK: Add docs for CircleCI cache invalidation

Build/Docker/run.sh, docker-compose.yaml
This change switch from Node 8 to 14 and fix the `run.sh` script.
=> TASK: Fix Docker setup for development

package.json, packages/neos-ui-validators/src/EmailAddress/index.spec.js, packages/neos-ui-validators/src/EmailAddress/index.tsx, yarn.lock
=> BUGFIX: Allow more domains in the email address validator

package.json, packages/neos-ui-redux-store/src/CR/Nodes/index.ts, yarn.lock
**What I did**
Upgraded immerjs to version 9 as the version we used has numerous vulnerabilities.
Upgrade and resolve issues.
Just use the UI and
=> TASK: Upgrade immer js to version 9.0

Classes/ContentRepository/Service/NodeService.php, Classes/ContentRepository/Service/WorkspaceService.php, Classes/Controller/BackendController.php, Classes/Controller/BackendServiceController.php, Classes/Domain/Model/AbstractChange.php, Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php, Classes/Domain/Service/NodeTreeBuilder.php, Classes/Fusion/Helper/ContentDimensionsHelper.php, Classes/Fusion/Helper/WorkspaceHelper.php, Classes/TypeConverter/ChangeCollectionConverter.php, Configuration/Settings.yaml, Resources/Private/Fusion/Backend/Root.fusion
Follow-up to 5f80a56210ba903e484e79a99d82b457a226198f
=> BUGFIX: Adjust code to "identifier" => "id" renamings
