neos/neos-ui

- README.md
Make sure the NeosDemoTypo3Org and its dependency FrontendLogin are removed including all leftovers.
+ remove PackageStates.php
+ remove NeosDemoTypo3Org package or "composer remove flowpack/neos-frontendlogin" will fail if NeosDemoTypo3Org is installed.
> DOCS: Update cleanup Command for FrontendLogin

- Classes/PackageFactory/Guevara/Aspects/FlowpackFrontendLoginCompatibilityAspect.php
- README.md
This PR introduces an Aspect to (temporarily) get rid of the issues with Flowpack.Neos.FrontendLogin.
The background is a RequestPattern that is applied via the FrontendLogin package.
This request pattern tries to distinguish between frontend and backend routes, but only matches backend routes that start with '/neos'.
With this aspect the behavior is enhanced to consider routes starting with '/che!' as well.
It is important to find a better way to support Flowpack.Neos.FrontendLogin, since PackageFactory.Guevara should not have a dependency to it. Therefore this aspect avoids a direct dependency, it is still implicit though.
Imho this issue even needs to be solved in Flowpack.Neos.FrontendLogin itself, since it makes the assumption, that the neos backend will always be available via …
> Apply Workaround to achieve compatibility with Flowpack.Neos.FrontendLogin

- Resources/Private/JavaScript/Host/Containers/LeftSideBar/index.js
- Resources/Private/JavaScript/Host/Containers/Neos/index.js
- Resources/Private/JavaScript/Host/Containers/index.js
- Resources/Private/JavaScript/Host/Decorators/Neos/index.js
- Resources/Private/JavaScript/Host/index.js
- Resources/Private/Templates/Backend/Index.html
- Resources/Private/TypoScript/Backend/Root.ts2
This PR introduces a higher order Component, that can be used as a decorator for various Containers. The idea is to spread global configuration, that is obtained during initialization.
It will also enable us to pass a central api around, instead of accessing action creators directly. This will help to keep Host/Guest functionality in sync.
Here's a usage example:
```
@neos()
class MyComponent extends Component {
static propTypes = {
neos: PropTypes.object.isRequired
};
render() {
const {configuration} = this.props.neos;
return (<div>{configuration.someConfiguredValue}</div>);
}
}
```
A configuration object is currently passed via TypoScript in `Resources/Private/TypoScript/Backend/Root.ts2`.
> Feature: Neos Decorator

- .storybook/config.js
- .storybook/webpack.config.js
- Build/Utilities/Environment.js
- Resources/Private/JavaScript/Components/Bar/index.story.js
- Resources/Private/JavaScript/Components/Button/index.js
- Resources/Private/JavaScript/Components/Button/index.story.js
- Resources/Private/JavaScript/Components/CheckBox/index.story.js
- Resources/Private/JavaScript/Components/Dialog/index.story.js
- Resources/Private/JavaScript/Components/DropDown/index.story.js
- Resources/Private/JavaScript/Components/Grid/index.story.js
- Resources/Private/JavaScript/Components/Headline/index.story.js
- Resources/Private/JavaScript/Components/Icon/index.story.js
- Resources/Private/JavaScript/Components/IconButton/index.story.js
- Resources/Private/JavaScript/Components/IconButtonDropDown/index.story.js
- Resources/Private/JavaScript/Components/Label/index.story.js
- Resources/Private/JavaScript/Components/Portal/index.story.js
- Resources/Private/JavaScript/Components/SideBar/index.story.js
- Resources/Private/JavaScript/Components/Tabs/index.story.js
- Resources/Private/JavaScript/Components/TextInput/index.story.js
- Resources/Private/JavaScript/Components/ToggablePanel/index.story.js
- Resources/Private/JavaScript/Components/Tree/index.story.js
- karma.entry.js
- package.json
- webpack.config.js
[Storybook](https://github.com/kadirahq/react-storybook) allows running each UI component in isolation from the rest of UI. It even allows developing UI components without even setting up Neos installation itself!
We can also integrate http://storybooks.io/ when it's launched, so we'd be able to have an online reference and reviewing of UI code, without needing to test the pull request locally.
> TASK: Storybook integration

- Resources/Private/JavaScript/Host/Sagas/Changes/index.js
- package.json
The method feedbackManager.handleFeedback() has never returned
anything; that's why we are not allowed to create an action from
it using put().
> BUGFIX: Update Redux-Saga to 0.11.0

- Resources/Private/JavaScript/Guest/Containers/NodeToolbar/Buttons/AddNode/index.js
- Resources/Private/JavaScript/Guest/Containers/NodeToolbar/index.js
- Resources/Private/JavaScript/Guest/Process/Synchronization.js
- Resources/Private/JavaScript/Guest/Redux/NodeToolbar/index.js
- Resources/Private/JavaScript/Host/Plugins/UI/Methods/OpenAddNodeModal/index.js
- Resources/Private/JavaScript/Host/Plugins/UI/Methods/index.js
- Resources/Private/JavaScript/Host/Selectors/CR/Constraints/index.js
> FEATURE: inline creation of nodes

- Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/EditorToolbar/StyleSelect.js
- Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/EditorToolbar/index.js
- Resources/Private/JavaScript/Host/Redux/Guest/index.js
We cannot store references to DOM nodes or Window in the store; as this will
break Redux-Devtools. However, we can store functions returning these values
:-)
> BUGFIX: allow Redux-Devtools to work again

- Resources/Private/JavaScript/Host/Containers/ContentCanvas/index.js
This fixes an issue where switching dimensions when navigating
causes an error because the context path was set before nodes were added
from the document information.
This needs a refactoring (e.g. single action) but fixes the issue for now.
> BUGFIX: Switch order of dispatched actions in content canvas

- Classes/Neos/Neos/Ui/TypoScript/Helper/ContentDimensionsHelper.php
- Classes/Neos/Neos/Ui/TypoScript/Helper/NodeInfoHelper.php
- Configuration/Settings.yaml
- Resources/Private/JavaScript/API/FlowQuery/Operations/Context/index.js
- Resources/Private/JavaScript/API/FlowQuery/Operations/index.js
- Resources/Private/JavaScript/Host/Containers/ContentCanvas/index.js
- Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/DimensionSwitcher/index.js
- Resources/Private/JavaScript/Host/Redux/CR/ContentDimensions/index.js
- Resources/Private/JavaScript/Host/Redux/CR/index.js
- Resources/Private/JavaScript/Host/Sagas/CR/ContentDimensions/index.js
- Resources/Private/JavaScript/Host/Sagas/CR/index.js
- Resources/Private/JavaScript/Host/Sagas/index.js
> FEATURE: Dimension switcher

- Resources/Private/JavaScript/Host/Sagas/Browser/index.js
- Resources/Private/JavaScript/Host/Sagas/index.js
This adds a `history.pushState` call when the `SET_CONTEXT_PATH` action of the ContentCanvas is performed. This way, the change of the document node is reflected in the address bar and calling the resulting URI already leads to the expecteded result.
solves #88
> FEATURE: Add history pushstate calls for whenever the document node changes

- Resources/Private/JavaScript/Host/Containers/LeftSideBar/NodeTreeToolBar/style.css
This fixes the page tree toolbar breaking, due to varying button sizes within.
> BUGFIX: Apply fixed height to toolbar buttons

- Resources/Private/JavaScript/Host/Containers/ContentCanvas/InlineUI/NodeToolbar/index.js
Whenever the guest frame resizes, the inline node toolbars position will be adjusted accordingly.
> BUGFIX: Adjust position of inline node toolbar

- Resources/Private/JavaScript/Host/Containers/SecondaryToolbar/DimensionSwitcher/style.css
Right now the DimensionSwitcher takes up the whole width:
> BUGFIX: correct DimensionSwitcher width

- Resources/Private/JavaScript/Host/Containers/ContentCanvas/InlineUI/NodeToolbar/index.js
- Resources/Private/JavaScript/Host/Containers/ContentCanvas/index.js
* Add a default for `enabledFormattingRuleIds`, so that it doesn't get undefined and break the subsequext `.forEach` call
* Wrap the `forceUpdate` call in the NodeToolbar component, so that it doesn't get called with unexpected actual parameters
> BUGFIX: Fix several exceptions thrown in the content canvas component

- Resources/Private/JavaScript/InspectorEditors/Image/Components/PreviewScreen/index.js
- Resources/Private/JavaScript/InspectorEditors/Image/Components/PreviewScreen/style.css
- Resources/Private/JavaScript/InspectorEditors/Image/Components/Secondary/ImageCropper/index.js
- Resources/Private/JavaScript/InspectorEditors/Image/index.js
The image editor preview did not change when repositioning the crop area.
> BUGFIX: Image Editor preview screen not reflecting crop configuration

- Resources/Private/JavaScript/Host/Containers/RightSideBar/Inspector/PropertyGroup/index.js
- Resources/Private/JavaScript/Host/Containers/RightSideBar/Inspector/PropertyGroup/style.css
- Resources/Private/JavaScript/Host/Containers/RightSideBar/Inspector/TabPanel/index.js
- Resources/Private/JavaScript/Host/Containers/RightSideBar/Inspector/TabPanel/style.css
- Resources/Private/JavaScript/Host/Containers/RightSideBar/Inspector/style.css
- webpack.testing.config.js
This prevents horizontal scrollbars in the inspector and gives a soft character limit to property group labels (via `text-overflow: ellipsis;`).
> BUGFIX: Limit width of inspector panel to dimensions of right side bar

- package.json
- packages/build-essentials/src/webpack.config.js
- packages/react-ui-components/.storybook/webpack.config.js
- packages/react-ui-components/package.json
We intentionally leave storybooks inside react-ui-components, as it
would hardly ever be needed anywhere outside.
From root of the project run `npm run start-storybook`
> TASK: make storybooks work again

- Resources/Private/Templates/Backend/Guest.html
The vendor.css in the Guest.html was still there
> BUGFIX: Remove leftover CSS

- packages/neos-ui/src/Containers/ContentCanvas/InlineUI/NodeToolbar/style.css
to prevent focusing underlying inline editable element on click
> TASK: set z-index for nodeToolbar

- packages/neos-ui/src/Containers/Modals/AddNode/index.js
If `elementValues` becomes a new object each time, React decides to
recreate all editors from scratch, thus they loose focus.
> BUGFIX: fix elements loosing focus in creation dialog

- packages/neos-ui/src/Containers/LeftSideBar/PageTree/Node/index.js
As edtiting the title of a node should only be possible in the inspector right now, there is no use for the doubleclick handling right now
> TASK: remove double-click from the tree

- packages/neos-ui-editors/src/Boolean/index.js
- packages/neos-ui-editors/src/DateTime/index.js
- packages/neos-ui-editors/src/SelectBox/index.js
- packages/neos-ui-editors/src/TextArea/index.js
- packages/neos-ui-editors/src/TextField/index.js
- packages/neos-ui/src/Containers/Modals/AddNode/index.js
- packages/react-ui-components/src/SelectBox/selectBox.js
For the fix we have to make `value` not a required prop.
Require `react-ui-components` to be rebuilt obviously.
> BUGFIX: fix creation dialog inputs

- Classes/Neos/Neos/Ui/TypoScript/Helper/StaticResourcesHelper.php
- composer.json
I had troubles setting the UI up after this merge:
https://github.com/neos/neos-ui/commit/3410810d2b1b319d194015c4ab24b5d9bf3202a4
I think this should work now.
> BUGFIX: Correct typo for packages and version constraint of compiled ui package

- packages/neos-ui/src/Containers/LeftSideBar/PageTree/Node/index.js
There was a trailing comma which the linter doesn't like :)
> BUGFIX: Remove trailing comma to satisfy linter

- packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/style.css
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/style.css
Previously, if the content of a inspector tab did not cover the
entire height of the inspector, it would cut off overflowing
elements (like select boxes) on y-axis.
This fix will let inspector tabs always occupy the entire height of
the inspector.
> BUGFIX: Fix overflowing in inspector

- packages/neos-ui-editors/src/Image/index.js
Previously to this commit plow-js threw an error stating that it couldnt set the  property on a string, which is the current value for new media nodes. Due to the error the image wasnt being applied correctly to the store, and therefore noe change from the initial placeholder image was possible
> BUGFIX: Fix the selection of a new media asset.

- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.spec.js
- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
As previously stated, it doesn't make sense to fire actions for each and every discovered node. So now, we'll add them in bulk by default.
> TASK: Turn CR.Nodes.add into a bulk action

- Classes/Neos/Neos/Ui/Aspects/ActivationAspect.php
- Classes/Neos/Neos/Ui/Controller/BackendServiceController.php
- Configuration/Settings.yaml
- Resources/Private/Fusion/Backend/Root.fusion
- packages/neos-ui-backend-connector/src/FlowQuery/index.spec.js
- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.spec.js
- packages/neos-ui-editors/src/Image/Components/Controls/index.js
- packages/neos-ui-editors/src/Image/Components/PreviewScreen/index.js
- packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/index.js
- packages/neos-ui-editors/src/Image/Components/Secondary/MediaDetailsScreen/index.js
- packages/neos-ui-editors/src/Image/Components/Secondary/MediaSelectionScreen/index.js
- packages/neos-ui-i18n/src/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
- packages/neos-ui/src/Containers/LeftSideBar/PageTree/Node/index.js
- packages/neos-ui/src/Containers/LeftSideBar/PageTree/index.js
- packages/neos-ui/src/Containers/Modals/AddNode/nodeTypeItem.js
- packages/neos-ui/src/Containers/Modals/AddNode/step1.js
- packages/neos-ui/src/Containers/Modals/AddNode/step2.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
- packages/neos-ui/src/index.js
- packages/neos-ui/src/manifest.js
Proposed configuration structure for node type roles:
```yaml
nodeTypeRoles:
document: 'Neos.Neos:Document'
content: 'Neos.Neos:Content'
contentCollection: 'Neos.Neos:ContentCollection'
```
> Fix remaining issues after namespace change

- Classes/Neos/Neos/Ui/Domain/Model/Changes/Property.php
- Classes/Neos/Neos/Ui/Domain/Service/NodePropertyConversionService.php
- Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui-redux-store/src/UI/PageTree/selectors.js
- packages/neos-ui/src/Containers/ContentCanvas/InlineUI/NodeToolbar/Buttons/HideSelectedNode/index.js
- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/neos-ui/src/Containers/ContentCanvas/style.css
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/HideSelectedNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/PageTree/Node/index.js
- packages/neos-ui/src/Sagas/CR/NodeOperations/index.js
- packages/react-ui-components/src/Tree/index.story.js
- packages/react-ui-components/src/Tree/node.css
- packages/react-ui-components/src/Tree/node.js
TODOs:
Description:
This comes with a different idea for styling the "hidden" state in the tree. Formerly, we had a small red icon indicating, that the node was hidden.
I replaced that with a strikethrough style on the node label, since I always felt, that the little red icon is a bit misleading.
So please, take this decision as a suggestion. I will gladly restore the known behavior if anything speaks against such a change.
> FEATURE: Hide nodes

- packages/neos-ui/src/Containers/ContentCanvas/InlineUI/NodeToolbar/Buttons/PasteClipBoardNode/index.js
Merging as a no-brainer, forgot to include it in the previous clean-up PR.
> BUGFIX: correct propType for canBePasted

- packages/neos-ui-editors/src/Image/Components/Controls/index.js
- packages/neos-ui-editors/src/Image/Components/Controls/style.css
- packages/neos-ui-editors/src/Image/index.js
- packages/react-ui-components/src/Button/index.story.js
- packages/react-ui-components/src/IconButton/iconButton.js
- packages/react-ui-components/src/IconButton/index.story.js
- packages/react-ui-components/src/IconButton/style.css
This follows the design descision taken in the current UI.
> TASK: adjust Image editor to use icons instead of buttons for controls

- Resources/Private/Translations/en/Main.xlf
- packages/neos-ui-containers/src/InsertModeSelector/index.js
- packages/neos-ui-containers/src/InsertModeSelector/style.css
- packages/react-ui-components/src/Button/index.story.js
- packages/react-ui-components/src/ButtonGroup/buttonGroup.js
- packages/react-ui-components/src/ButtonGroup/buttonGroupItem.js
- packages/react-ui-components/src/ButtonGroup/index.js
- packages/react-ui-components/src/ButtonGroup/index.story.js
- packages/react-ui-components/src/ButtonGroup/style.css
- packages/react-ui-components/src/identifiers.js
I propose to use a button group instead of SelectBox for selecting new element's position.
Why? -- It saves one click, which is quite a lot!
The final styling could be improved with the help of a designer.
What are your thoughts?
New behaviour:
> TASK: use ButtonGroup component in InsertModeSelector

- Configuration/NodeTypes.yaml
- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.spec.js
It's important to preserve the ordering of `this._groups` as we can't
sort them again by position in JS (sorting logic is too complex).
To avoid adding special condition for filtering for `Neos.Neos:Content`
nodes when inserting content, let's add a default group of "general" to
`Neos.Neos:Document` and assume that nodetypes without a group are a
system nodetypes that don't need to be listed.
> BUGFIX: preserve ordering of nodetype groups and don't fallback to 'general'

- packages/neos-ui-redux-store/src/UI/AddNodeModal/index.js
- packages/neos-ui-redux-store/src/UI/Drawer/index.js
- packages/neos-ui-redux-store/src/UI/EditModePanel/index.js
- packages/neos-ui-redux-store/src/UI/FullScreen/index.js
- packages/neos-ui-redux-store/src/UI/LeftSideBar/index.js
- packages/neos-ui-redux-store/src/UI/RightSideBar/index.js
- packages/neos-ui/src/Containers/ContentCanvas/style.css
- packages/neos-ui/src/index.js
- packages/neos-ui/src/localStorageMiddleware.js
Saves the `ui` part of the state to local storage on every action that
matches the `persistentActionsPattern`.
TODO:
Closes: #13
> TASK: persist ui state to local storage

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
Script tag with nodeType information is added
below the current node and not inside. Now the 
html argument does not add a new wrapping around the
current node.
> [FIXUP] Fixed content wrapping

- packages/neos-ui-validators/src/Count/index.js
- packages/neos-ui/src/Containers/ContentCanvas/Helpers/initializeCkEditorForDomNode.js
- packages/neos-ui/src/Containers/ContentCanvas/style.css
This removes the outline from focused editables, to not interfere with
the Neos styling.
> TASK: Remove outline from focused editables

- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractMove.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveAfter.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveBefore.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveInto.php
- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
- packages/neos-ui/src/Containers/LeftSideBar/PageTree/Node/index.js
- packages/neos-ui/src/Containers/LeftSideBar/PageTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/PageTree/style.css
- packages/neos-ui/src/Containers/LeftSideBar/style.css
- packages/neos-ui/src/Containers/Modals/InsertMode/index.js
- packages/neos-ui/src/Sagas/CR/NodeOperations/index.js
- packages/react-ui-components/src/Tree/index.story.js
- packages/react-ui-components/src/Tree/node.css
- packages/react-ui-components/src/Tree/node.js
Though not a full rewrite, this PR introduces still some changes:
- Retrieve nodes directry from the CR part of the store, without further conversion
- More flat prop structure for the tree component
- Add drag and drop functionality
> Pagetree rewrite

- packages/neos-ui/src/Containers/ContentCanvas/style.css
On pages with transparent body gray bg shines through:
> BUGFIX: ContentCanvas' iframe is transparent

- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
* Ensure you have a content constraint for Auto Created Child nodes (e.g. "Main") set up.
* you will see ALL node types are displayed, not just the correct ones in the "add node" dialog.
I am not sure if the solution above is actually correct or has weird side-effects. @grebaldi would be great to have some more docs on the selectors :)
All the best,
Sebastian
> WIP: fix "insert into" constraints for auto-created child nodes

- package.json
This reverts commit 78833d7906acdfa11e661b98af2c80b545a1e143.
Newer version is causing weird errors that I'm not able to fix quickly:
```
ERROR in ./packages/neos-ui/src/Containers/style.css
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module 'base64-js' in /home/dimaip/docker/sfi.ru/sfi20151230/data/www/releases/current/Packages/Application/Neos.Neos.Ui/node_modules/buffer
```
> Revert "chore(package): update css-loader to version 0.27.3 (#560)"

- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
- packages/neos-ui/src/Containers/ContentCanvas/Helpers/initializeCkEditorForDomNode.js
- packages/neos-ui/src/Containers/SecondaryToolbar/index.js
... makes working with inline-editable Document node properties a lot better; might fix breakage when a span is the wrapping element.
> Fix ckeditor details and secondary editable

- packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js
- packages/neos-ui/src/Containers/SecondaryToolbar/LoadingIndicator/style.css
Fixes some-times-broken loading indicator positioning and issues #597 & #595 where it would not stop loading if the current page was clicked again.
> Bugfix: loading indicator

- packages/neos-ui-containers/src/InsertModeSelector/index.js
If an insert position mode was preselected the component never
considered if that mode was actually enabled leading to modals
with empty groups being shown.
Fixes: #578
> BUGFIX: Switch insert mode depending on allowed positions

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractStructuralChange.php
- Classes/Neos/Neos/Ui/Fusion/RenderNonRenderedNodeMetadataImplementation.php
- Resources/Private/Fusion/Prototypes/Page.fusion
- packages/neos-ui/src/Sagas/CR/NodeOperations/helpers.js
Child nodes not rendered within the current document node used to disappear after creating new document nodes (after first refresh). The behaviour for inserted child nodes was also fixed (before it was possible that the fusion rendering path was not available).
> BUGFIX: Fix structure tree ouput and ``insert inside`` behaviour for non rendered nodes

- packages/neos-ui-editors/src/Image/index.js
The preview image in the inspector was not shown, unless another element has been selected before.
Fixes: #542
> BUGFIX: Show preview image in inspector on first selection

- Classes/Neos/Neos/Ui/Controller/BackendServiceController.php
- Classes/Neos/Neos/Ui/Domain/Model/ChangeCollection.php
- Classes/Neos/Neos/Ui/Domain/Model/ChangeInterface.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractCopy.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractCreate.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractMove.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/Property.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/Remove.php
- Classes/Neos/Neos/Ui/TypeConverter/ChangeCollectionConverter.php
Before this change an type conversion exception was thrown when trying to change the image inside the image inspector.
> BUGFIX: Apply new images in the inspector without throwing exceptions

- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractCreate.php
Without this change, the ContentCanvas stayed empty because the node was not
yet loaded, and thus no URL could be determined.
> BUGFIX: when creating new documents, directly show the newly created document

- packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/model.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/RefreshPageTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
- packages/react-ui-components/src/Frame/frame.js
- packages/react-ui-components/src/SelectBox/searchableSelectBox.js
- packages/react-ui-components/src/Tree/node.js
One last error in the console is from prop validation for `icon-folder-open-alt` icon, which got removed from Fontawesome.
> BUGFIX: make console clean AGAIN

- packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/index.js
- packages/neos-ui/src/Containers/SecondaryToolbar/DimensionSwitcher/style.css
- packages/react-ui-components/src/DropDown/header.js
- packages/react-ui-components/src/DropDown/index.story.js
- packages/react-ui-components/src/DropDown/style.css
- packages/react-ui-components/src/DropDown/wrapper.js
Now the DropDown component accept a new style attributes. The default rendering is not touched. You can use ```darker``` to have the color styling used in the DimensionSwitcher. The ```padded``` attributes is added to add padding around the content area of the DropDown.
The change on the DropDown make it more self contains and allow us to remove most of the styling from the DimensionSwitcher. 
Lerna story is updated so you can test the different rendering.
Fixes: #587
> TASK: Fix color contrast issue in DimensionSwitcher

- packages/neos-ui-editors/src/Image/index.js
Before an exception was thrown, now empty string will be used for removed images within the inspector (the empty string is consistent with how removed images are handled in the current UI).
> BUGFIX: Set removed image to empty string

- packages/neos-ui-inspector/src/SecondaryInspector/style.css
Codemirror sets z-index 1 for codelines which are not empty (in some cases it gets up to z-index 6), this lays over the close button and it is not clickable
see #671
> BUGFIX: Close button in codemirror

- package.json
- yarn.lock
This is a leftover after the migration to jest
This will also close #678
> TASK: Remove ava from toplevel package

- packages/react-ui-components/src/reset.css
Otherwise I get issues like this when the site's styles override our styles:
> BUGFIX: make CSS reset more robust by resetting the spacings

- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui-contentrepository/src/registry/getNormalizedDeepStructureFromNodeType.js
- packages/neos-ui-contentrepository/src/registry/getNormalizedDeepStructureFromNodeType.spec.js
Currently the sorter doesn't sort unpositioned elements correctly. They should retain the order defined in source code.
Also I extracted the logic to make it more clear and easier to test, and actually written a test for this sorting behavior.
> BUGFIX: sorting messes up order for not positioned properties

- EXTENSIBILITY.md
- packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
- packages/neos-ui-extensibility/src/shims/vendor/react-dom/index.js
- packages/neos-ui/src/apiExposureMap.js
The error without this line was ` Module not found: Error: Cannot resolve module 'react-dom'` when trying to compile https://github.com/cvette/neos-ui-location-editor.
This change fixes the issue.
for reference, the full error message was as follows:
```
> @ build /Users/sebastian/src/neosdev_3.0/Packages/Application/Vette.Location/Resources/Private/LocationEditor
> neos-react-scripts build
;@@@@@@@@#                +@@@@@@@+
@#@       @'              @@       +
'@, '#       @            .@.@       +
+    @'      ,@          #@  @       +
+     @       @:        @+   @       +
+     ,@       @      .@'    @       +
+      @,      '@     .:     @       +
+       @       #+    .:     @       +
+       '@       @    .:     @       +
+        #'       @   .:     @       +
+         @       ;# …
```
> BUGFIX: make react-dom accessible through extensibility API

- README.md
- package.json
When a file share is used (for example when developing on an VM), the webpack file watcher might not work reliable because of issues connected with inotify and Samba.
This command adds the `watch-poll` flag to the `npm run build:ui -- --watch`. The issue is resolved through the polling mechanism and the performance impact seems to be negligible.
> FEATURE: Enable polling for file watcher

- packages/neos-ui/src/System/index.js
By getting the JSON string from the backend page via ``innerHTML``
it was HTML escaped by JavaScript, turning ``&`` inside of strings
to ``&amp;`` entities. To avoid this, the JSON string should be
fetched by ``textContent`` from the HTML node which doesn't show
this behavior.
Fixes: #719
> BUGFIX: Avoid escaping of backend data while reading

- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractStructuralChange.php
- Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
This quick-fixes a pretty bad performance regression when inserting nodes on
top levels of the tree; leading to the problem that the full node tree
was sent to the client.
Generally, we still send way too much nodes to the client as the result
of a change operation; but that should be optimized in separate steps.
> BUGFIX: ensure node info is only updated non-recursively in most cases

- packages/neos-ui/src/Containers/EditModePanel/Panel/index.js
- packages/neos-ui/src/Containers/EditModePanel/style.css
Currently the slider component produces a lot of property validation errors by overriding the style property of its children. Wrapping the buttons inside the slider prevents those errors.
> TASK: Wrap button inslide slider to prevent slick-slider to override the style property

- packages/neos-ui-redux-store/src/CR/Nodes/helpers.js
- packages/neos-ui/src/Sagas/UI/ContentTree/index.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
When selecting a content node within a page that node should be auto expanded and revealed in the content tree.
> TASK: uncollapse content tree rootline when a node is focused

- packages/neos-ui-editors/src/Boolean/index.js
- packages/neos-ui-editors/src/Boolean/style.css
- packages/react-ui-components/src/CheckBox/checkBox.js
- packages/react-ui-components/src/CheckBox/style.css
A boolean property can be set to disabled [Documentation](http://neos.readthedocs.io/en/3.1.3/References/PropertyEditorReference.html#property-type-boolean-booleaneditor-checkbox-editor)
> TASK: Add option disabled to the CheckBox component

- packages/neos-ui/src/Containers/PrimaryToolbar/style.css
Because Codemirror does something with it's z-index to do some stuff this is necessary
> BUGFIX: Let the userdropdown be over the codemirror editor

- Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
- Resources/Private/Fusion/Backend/Root.fusion
- packages/neos-ui-redux-store/src/CR/Nodes/helpers.js
- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
- packages/neos-ui-redux-store/src/UI/ContentTree/index.js
- packages/neos-ui-redux-store/src/UI/ContentTree/index.spec.js
- packages/neos-ui-redux-store/src/UI/ContentTree/selectors.js
- packages/neos-ui-redux-store/src/UI/PageTree/index.js
- packages/neos-ui-redux-store/src/UI/PageTree/index.spec.js
- packages/neos-ui-redux-store/src/UI/PageTree/selectors.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
- packages/neos-ui/src/Sagas/UI/ContentTree/index.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
This PR switches from keeping track of uncollapsed nodes to tracking toggled nodes and XOR'ing them with the default collapsed state based on the loadingDepth configuration from the settings.
> TASK: respect loadingDepth in the trees

- packages/react-ui-components/src/_lib/fontAwesome.js
- packages/react-ui-components/src/_lib/fontAwesome.spec.js
Introduce a list of backward compatible icons to allow using icons from the old FontAwesome versions that the old UI still uses.
> BUGFIX: Reintroduce backward compatible icons

- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
- packages/neos-ui-guest-frame/src/style.css
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
What to test:
- select any editable, there should be no additional tiny blue outline
- when you unfocus, the main blue outline should be removed
- focused node in content tree should always be active
> BUGFIX: multiple styling improvements

- packages/neos-ui-editors/src/Boolean/index.js
- packages/neos-ui-editors/src/TextArea/index.js
- packages/neos-ui-editors/src/TextField/index.js
to eliminate sideeffects
like mentioned in #787
> BUGFIX: Use empty object to assign options to

- Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
No need to load filtered out document nodes into the state.
This change drastically improves performance if there are a lot of filtered nodes.
> BUGFIX: respect baseNodeType when rendering child nodes

- packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
> BUGFIX: display inspector tabs that have only views and no properties

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui-guest-frame/src/InlineUI/index.js
- packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js
- packages/neos-ui-redux-store/src/UI/ContentCanvas/selectors.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
Fixes #835.
I couldn't think of a nicer way to do it. We imperatively request to scroll the node into view when selecting a node from the tree.
> BUGFIX: scroll inline node into view only when requested from the tree

- packages/react-ui-components/src/Tabs/tabs.js
> BUGFIX: fallback to the first tab when tab index is out of bounds

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
Please just merge this and save me from embarrassment.
> BUGFIX: don't fire requestScrollIntoView in document node tree

- packages/debug-reason-for-rendering/package.json
- packages/debug-reason-for-rendering/src/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
Also fixes the `debug-reason-for-rendering` helper to support pure components by refactoring to HOC. 
It drastically improves performance! Before all nodes were rerendered on each update.
Before it used inheritance, which didn't work and in general is not a good idea with React components.
> BUGFIX: fix performance of trees by fixing makeChildrenOfSelector

- Classes/Neos/Neos/Ui/Domain/Service/NodePropertyConversionService.php
- packages/neos-ui-backend-connector/src/Endpoints/index.js
- packages/neos-ui-editors/package.json
- packages/neos-ui-editors/src/SelectBox/DataSourceBasedSelectBoxEditor.js
- packages/neos-ui-editors/src/SelectBox/SelectBoxHelpers.js
- packages/neos-ui-editors/src/SelectBox/SimpleSelectBoxEditor.js
- packages/neos-ui-editors/src/SelectBox/index.js
- packages/neos-ui-editors/src/SelectBox/index.spec.js
- packages/neos-ui-editors/src/_lib/testUtils.js
- packages/neos-ui-i18n/src/index.js
- packages/neos-ui-i18n/src/registry/I18nRegistry.js
- packages/neos-ui/src/manifest.dataloaders.js
- packages/react-ui-components/src/MultiSelectBox/index.story.js
- packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js
- packages/react-ui-components/src/MultiSelectBox/style.css
- packages/react-ui-components/src/SelectBox/index.story.js
- packages/react-ui-components/src/SelectBox/selectBox.js
> FEATURE: Full select editor (with data providers and multiselect support)

- Build/TravisCi/composer.json
For some reason currently it's installing the wrong branch.
> BUGFIX: force dev-master version of Neos.Demo

- packages/neos-ui/src/Sagas/UI/PageTree/index.js
We have to wait before the node is loaded into the state, before deciding if it is collapsed or not.
Fixes: #891
> BUGFIX: load nodes to state before expanding

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
> BUGFIX: load metadata for all direct children of document node

- packages/neos-ui-redux-store/src/UI/PageTree/index.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
FIxes: #878 
We move the logic from the reducer to the saga because we need access to configuration to calculate the toggled state, but also because it makes sense to keep reducers more atomic and simple.
> BUGFIX: make search correctly calculate the isToggled state

- packages/neos-ui-guest-frame/src/style.css
This change add width 100% for the class addEmptyContentCollectionOverlay
in certain situation, like if the parent node has display flex, the overlay
can collapse to a one pixel wide block on the left (or right) of the parent
> TASK: addEmptyContentCollectionOverlay should use the full width of the container

- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
> BUGFIX: only allow to create nodes of the same role as the reference node

- packages/neos-ui-editors/src/Image/Components/Secondary/ImageCropper/index.js
Fixes: #917 
I didn't find a way to fix it in CSS: `max-height` won't work within absolute div; `object-fit: contain` breaks the cropper. 
So I fixed it via direct DOM manipulations.
> BUGFIX: limit height for the cropped image

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Without this fix, if you clicked on expanding a tree node, the tree would rewind to the focused node.
> BUGFIX: don't scroll the tree unless focused node has changed

- Classes/Neos/Neos/Ui/Controller/BackendServiceController.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractStructuralChange.php
- Tests/IntegrationTests/contentModule.js
- Tests/IntegrationTests/pageModel.js
- package.json
- packages/neos-ui-guest-frame/src/manifest.js
- packages/neos-ui/src/Containers/Modals/DeleteNode/index.js
- packages/neos-ui/src/manifest.js
Fixes: #794
Fixes: #791 
- Move intialization of all serverFeedbackHandlers into one place, so they
don't override each other by accident, fixes redirect on node removal
- Allow discarding of removed nodes
- Correctly remove or re-create discarded nodes from UI
TODO:
> BUGFIX: misc bugs related to discarding and removing nodes

- README.md
Shells will otherwise treat the arguments separately
> BUGFIX: escape space in package identifier

- packages/react-ui-components/src/DropDown/style.css
I propose to make scrollable dropdowns to take up 80% of viewport. E.g. for links editor 320px is not enough.
> TASK: make scrollable dropdown taller

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Previously, if the label was not given, the decode function
crashed with a NULL value.
> BUGFIX: make decodeLabel() in node tree more robust

- packages/neos-ui-editors/src/Reference/index.js
- packages/neos-ui-editors/src/References/index.js
The nodetpye option in ReferenceEditor props can be a strig with a
single nodetype as well as an array
> TASK: Adjust proptype validation for ReferenceEditor

- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.spec.js
When moving a node we immediately move it into the children of the target node, without changing its contextPath. Then we the action is performed, the new feedback arrives that updates the nodes with new contextPaths.
> TASK: optimistically move a node to its new location

- packages/neos-ui/src/Sagas/Browser/index.js
- packages/neos-ui/src/Sagas/Browser/index.spec.js
- packages/neos-ui/src/Sagas/index.js
History is written on ifame url changes, so setting it again would cause
duplicate entries.
My previous attempt to fix it removed the url handling altogether...
> BUGFIX: replace history instead of pushing new entry

- Classes/Neos/Neos/Ui/Fusion/Helper/WorkspaceHelper.php
- packages/neos-ui-redux-store/src/CR/Workspaces/selectors.js
- packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
Before it was possible to publish to live workspace for restricted editors, which would lead to an exception.
This change forbids publishing and indicates early on that the workspace is locked.
> BUGFIX: forbid publishing to read-only workspaces

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Currently on first render the tree is not scrolled to reveal the focused node. This fixes it.
> BUGFIX: scroll tree into view on first render

- packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeFilter.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/style.css
- packages/react-ui-components/package.json
If you have a lot of content nodetypes it can be complex to find the correct nodetype in our new node dialog. Therefore this change adds a possibility to filter nodetypes.
> FEATURE: Filter nodetypes in SelectNodeTypeDialog

- Configuration/Settings.yaml
- Resources/Private/Fusion/Backend/Root.fusion
- packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js
- packages/neos-ui/src/Containers/ContentCanvas/index.js
This feature introduces a new Setting `Neos.Neos.Ui.configuration.contentCanvas.backgroundColor`. It can be set to any valid string for the css property `background` and defaults to a white color. With this setting set the background of the content canvas can be set to prevent it flickering on a page load.
Resolves #863
> FEATURE: Set background color for the content canvas

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
When clicking a node in the content tree, the smooth-scroll animation didn't work for me. After some debugging I saw, that animating `scrollTop` doesn't seem to work.
So, I tried to come up with a more compatible alternative.
> BUGFIX: Fix smooth-scroll to element in guest frame

- packages/neos-ui-views/src/NodeInfoView/index.js
This was bugging me for a while, since all I ever do with this information is copy&paste :smile: 
But this is of course just a nice-to-have feature. Not important for 1.0.0
> FEATURE: Auto-select contents of metadata view on click

- packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js
- packages/react-ui-components/src/TextInput/textInput.js
This makes it possible to trigger submit via the enter key.
It also enables the textinput to receive 3 new props.
onEnterKey - which triggers a function when enter is pressed
type - like password
setFocus = to focus this input element when it is mounted.
I get a console warning: `Warning: Unknown prop `0` on <input> tag.` even I am omitting the `onEnterKey` prop. The warning is triggered from the searchinput. If anyone know why this happens please ping me.
fixes #1011
> BUGFIX: Relogin Submit on Enter

- Classes/Neos/Neos/Ui/ContentRepository/Service/NodeService.php
- Classes/Neos/Neos/Ui/Controller/BackendServiceController.php
- Tests/IntegrationTests/contentModule.js
- packages/neos-ui-redux-store/src/UI/PageTree/selectors.js
- packages/neos-ui-redux-store/src/UI/PageTree/selectors.spec.js
- packages/neos-ui/src/Sagas/Publish/index.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
- packages/neos-ui/src/manifest.js
I recognized that the e2e-Tests are currently false-positive. All of the test-scenarios run through immediately without executing any assertions, because the `section` function itself is not asynchronous.
I fixed that and immediately found this one thanks to the tests: #999
**Update**
This now includes a fix for #999, so that the e2e tests should be green now.
Fixes: #999
> BUGFIX: Make e2e section helper function async

- packages/neos-ui-ckeditor-bindings/src/ckeditor/neosPlaceholder.js
This is a workaround for the focus issue that occurs, if you click on an empty inline editable.
Since it is unclear at which point the event propagation is stopped (looks like CK internals), I just simulate another click on the editable element after the neosPlaceholder is removed.
Fixes: #940
> BUGFIX: Simulate click after placeholder removal (CKEditor)

- packages/neos-ui-ckeditor-bindings/src/manifest.formattingRules.js
- packages/neos-ui-ckeditor-bindings/src/manifest.richtextToolbar.js
- packages/neos-ui-ckeditor-bindings/src/registry/RichTextToolbarRegistry.js
- packages/neos-ui/src/Registry/RichTextToolbarRegistry.js
This enables the `left`, `right`, `center` and `justify` alignment options for CKEditor.
**Attention when testing:** I recognized that by default, none of the alignment options is enabled for Text nodes on the demo page - although the old UI is showing them anyway. So, when you're testing this with the Demo page, you have to explicitly enable the options via:
```yaml
properties:
text:
ui:
aloha:
alignment:
'left': TRUE
'center': TRUE
'right': TRUE
'justify': TRUE
```
Resolves: #829
> FEATURE: Enable alignment options for CKEditor

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/style.css
Here's another nice-to-have feature. With this change, the inline toolbar becomes sticky, before it scrolls off-screen. This helps to improve usability if you have to deal with large content elements (like the Text Nodes in the Chapter documents on the demo page).
> FEATURE: Make inline toolbar sticky while scrolling over large elements

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui-guest-frame/src/dom.js
This also comes with an abstraction of the determination of guest frame elements' positioning, as well as an abstraction for the scroll animation to have all of it in a central place.
Fixes: #1017
> BUGFIX: Fix positioning of inline node toolbar

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
Follow-up to #1004, respects the case when the user has "Use system locale" as a language preference.
> BUGFIX: respect the "Use system locale" user setting

- Tests/IntegrationTests/contentModule.js
I split the test cases via a native testcafe mechanism instead of our own custom `section` helper.
PROS:
- Less hackish, native way
- Tests are more isolated from each other thus more reliable
CONS:
- Slower, as for every test case the UI is reloaded (~5s extra time per each test)
- Will not catch stateful side-effects, when one test may cause other to fail.
> TASK: split the tests

- packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
- packages/neos-ui-extensibility/src/shims/vendor/prop-types/index.js
- packages/neos-ui/src/apiExposureMap.js
Since it has been split from the react main package and we've adopted the change, the prop-types package should be exposed as a shim via our extensibility package.
> TASK: Expose prop-types package via extensibility

- Classes/Neos/Neos/Ui/ContentRepository/Service/WorkspaceService.php
- Classes/Neos/Neos/Ui/View/BackendFusionView.php
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Every node has been asked to be scrolled into view on initial render, which caused the page tree to scroll till the last node on first load.
Fixes: #1027
> BUGFIX: fix scrollIntoView in the trees

- packages/neos-ui/src/Containers/Drawer/MenuItem/index.js
- packages/neos-ui/src/Containers/Drawer/MenuItemGroup/index.js
- packages/neos-ui/src/Containers/Drawer/index.js
Currently URIs  for menu items are required, but in some cases these can be `null`. The old UI would just disable the item in that case. 
This PR replicates that behavior.
> BUGFIX: Disable drawer menu items that have no uri

- packages/neos-ui-editors/src/DateTime/index.js
- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui-editors/src/TextArea/index.js
- packages/neos-ui-editors/src/TextField/index.js
- packages/react-ui-components/src/DateInput/dateInput.js
Fixes: #1026 
Doesn't work with SelectBox-derived editors since they have no native input inside, but it never worked in the old ui either.
> BUGFIX: focus editors on label click

- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/Helpers/renderToolbarComponents.js
- packages/neos-ui-ckeditor-bindings/src/registry/CkEditorFormattingRulesRegistry.js
This fixes 2 problems that are currently preventing our CKEditor integration to allow custom style definitions.
1. When `formattingUnderCursor` for a custom formattingRule evaluates to `true`, the corresponding Element in the Toolbar is now considered active. Before this only applied for `TRISTATE_ON`, although `true` is a perfectly valid answer as well.
2. Defining styles like this:
```js
formattingRules.add('red', {
style: {
element: 'span',
attributes: {
style: 'color: red;'
}
}
});
```
appearently is not sufficient. It'll work, as long as the editor doesn't re-initialize. So at the next reload, the formatting is gone. The given methods to whitelist elements for ACF did not help. After a while of research, I stumbled upon this: https://stackoverflow.com/a/13194812 - and it works.
So, I …
> TASK: Enable custom styles

- Classes/Neos/Neos/Ui/FlowQueryOperations/NeosUiDefaultNodesOperation.php
- Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
- packages/neos-ui-backend-connector/src/Endpoints/index.js
- packages/neos-ui-backend-connector/src/FlowQuery/Operations/NeosUiDefaultNodes/index.js
- packages/neos-ui-backend-connector/src/FlowQuery/Operations/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui/src/Sagas/CR/ContentDimensions/index.js
So, this is a larger change.
Basically what it does is:
* Creating a new FlowQuery operation that allows to load the default nodes for the backend
* Exposing that FlowQuery operation to the UI
* <s>Replace the entire node state, whenever a dimension is switched, before the content canvas loads the new document state.</s>
* Load all default nodes of the target dimension into the store
<s>This is still crazy slow, but at least it works.</s>
I was able to parallelize loading the default nodes and the guest frame. Now it feels quite fast.
Fixes: #1042
> BUGFIX: Replace node state on dimension switch

- Resources/Private/Fusion/Prototypes/Page.fusion
I re-added the `neos-backend` class to the body tag of the currently edited document, since a lot of sites depend on this to optimize their styles for editing.
This is needed for one of the core feature sponsors.
> TASK: Add .neos-backend class

- Configuration/NodeTypes.yaml
- packages/neos-ui-guest-frame/src/initializeContentDomNode.js
... And assume all nodes that have children to be inline editable as well.
This replicates the behavior in the old UI.
> BUGFIX: Make Content Collection editable by default

- Classes/Neos/Neos/Ui/Aspects/BackendRedirectionServiceAspect.php
- Classes/Neos/Neos/Ui/Cache/ContentCacheStringFrontend.php
- Classes/Neos/Neos/Ui/Controller/BackendController.php
- Configuration/Caches.yaml
When logged into the backend, the old and new UI have different rendering
behavior - the old UI renders the node metadata in a different way than
the new UI. That's why we cannot let the new UI run on cached segments
which were generated on the old UI (happens when switching between old
and new UI), and vice versa.
We now prepend the content cache entries with "neos-ui" if we are in the
new UI, to prevent clashes.
NOTE: Cache flushing still works properly in *both* UIs (when modifying 
content), because tags are not touched or namespaced at all.
> !!! BUGFIX: Do not flush the full content cache when switching UIs

- packages/neos-ui-redux-store/src/CR/Nodes/index.js
Imagine what happens when children would change from these:
```
[0: {contextPath: 'a'}, 1: {contextPath: 'b'}, 2: {contextPath: 'c'}]
```
Into these:
```
[0: {contextPath: 'a'}, 2: {contextPath: 'c'}]
```
Currently our deep merge would just merge them like this:
```
[0: {contextPath: 'a'}, 1: {contextPath: 'c'}, 2: {contextPath: 'c'}]
```
Which causes a duplicate child, and React would complain about it.
Even better solution would be to create a new kind of deep $merge, that
would only deep merge objects, but override the arrays. But I'm scared to touch @grebaldi's Plow and just need to fix the tests right now.
> BUGFIX: override children in merge action, instead of deep merging

- packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js
- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/neos-ui/src/Containers/ContentCanvas/style.css
- packages/neos-ui/src/Sagas/UI/ContentCanvas/index.js
- packages/react-ui-components/src/Frame/frame.js
As described in #811 it is currently possible, that our UI loses access to the content canvas iframe, when its location changes to some external URI.
This change prevents this scenario, by testing the access to the frame after it has been loaded and, if it fails, seamlessly reloading the previous page and printing an error message that informs the user, that his/her navigation attempt failed.
To the user, this looks like this:
> FEATURE: Handle access to content canvas iframe

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CopySelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CutSelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/PasteClipBoardNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui-guest-frame/src/InlineUI/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CopySelectedNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CutSelectedNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
- packages/neos-ui/src/Sagas/CR/NodeOperations/copyAndPasteNode.js
- packages/neos-ui/src/Sagas/CR/NodeOperations/cutAndPasteNode.js
- packages/react-ui-components/src/Tree/node.js
Fixes: #1075
Fixes: #1092
Fixes: #817
Fix multiple bugs related to the logic of moving nodes:
- DragAndDrop of autoCreated nodes should be disallowed
- Moving into descendants of the node itself should be disallowed
- Before and after dropzones should not be highlighted when can't drop into them
- Cut/Copy buttons should reflect their state
> BUGFIX: misc cut/paste logic fixes

- Tests/IntegrationTests/contentModule.js
- package.json
- packages/neos-ui/src/manifest.js
Steps to reproduce: Create a document node. Create another document node inside of it. Discard all and see all sorts of errors.
This change recursively looks for the parent node that still exists, and redirects to it.
> BUGFIX: correctly redirect on removal of nested nodes

- Classes/Neos/Neos/Ui/Controller/BackendController.php
- Resources/Private/Fusion/Prototypes/Page.fusion
The loading error occurred exactly if the *standard* dimension contained multiple
dimension values. That's what is fixed here.
Resolves: #755
Important: After applying this patch, clear your caches and start by visiting the FRONTEND (such that the last-visited node can be properly memoized ,*including* dimension infos)
> BUGFIX: fix loading of node with dimensions, use lastVisitedNode logic

- package.json
- packages/react-ui-components/src/SelectBox/selectBox.js
- packages/react-ui-components/src/SelectBox/style.css
- yarn.lock
In this implementation it is possible to use the arrow keys to navigate
up and down and to chose one item via the enter key.
This replicates the behaviour of the old UI.
This doesn't work for SelectBoxes with a search box currently.
closes #1036
> FEATURE: Support keyboard navigation in SelectBox

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
Steps to reproduce: e.g. go to Multiple columns page in demo site. Switch language to Latvian. Label for content collection that is not rendered (footer) will be rendered in Larvian.
> BUGFIX: use UI locale when rendering nodes via getNonRenderedContentNodeMetadata

- packages/neos-ui-editors/src/SecondaryEditors/CodeMirrorWrap/index.js
Fixes: #832 
Before, sometimes not all lines were rendered in the editor because the setting the height manually did not trigger a rerender of the lines.
When setting the height with the [`setSize()`-method from codemirror](https://github.com/codemirror/CodeMirror/blob/0ea666fe3db9cd68dd951cc9178944cccdd9276d/src/edit/methods.js#L392), the number of displayed lines is newly calculated.
Setting the height this way seems to be advised with codemirror, as it mentioned here:
https://github.com/JedWatson/react-codemirror/issues/57#issuecomment-274236854
> BUGFIX: set height of codemirror instance with ref callback

- packages/neos-ui-guest-frame/src/style.css
Fixes #1064: Highlight inline editable elements on hover by adding a dashed border.
On inline editable elements the classes `neos-inline-editable cke_editable cke_editable_inline` (and some other ones) are applied. By choosing `neos-inline-editable:hover` instead of the `cke`-prefixed ones, the CSS is independent of the text editor.
> FEATURE: indicate inline editable elements

- Classes/Neos/Neos/Ui/Domain/Service/ConfigurationRenderingService.php
- Classes/Neos/Neos/Ui/Domain/Service/StyleAndJavascriptInclusionService.php
- Classes/Neos/Neos/Ui/Fusion/RenderConfigurationImplementation.php
- Classes/Neos/Neos/Ui/Fusion/RenderStateImplementation.php
- Configuration/Settings.yaml
- Resources/Private/Fusion/Backend/Root.fusion
- Resources/Private/Fusion/Prototypes/Page.fusion
- Resources/Private/Fusion/Prototypes/RenderConfiguration.fusion
- Resources/Private/Fusion/Prototypes/RenderState.fusion
- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/neos-ui/src/Containers/EditModePanel/index.js
- packages/neos-ui/src/Containers/PrimaryToolbar/EditModePanelToggler/index.js
- packages/neos-ui/src/index.js
- packages/neos-ui/src/manifest.js
This change introduces a place in settings which allows to transfer some configuration to UI components, including 3rd-party components.
E.g.:
```
Neos:
Neos:
Ui:
frontendConfiguration:
'Your.Own:Package':
someKey: someValue
```
Then it may be accessed as:
```js
globalRegistry.get('frontendConfiguration').get('Your.Own:Package').someKey
```
I guess we should declare it as an experimental API that may change in the future in a breaking way.
TODO:
> FEATURE: Frontend configuration API

- Resources/Private/Fusion/Prototypes/Page.fusion
- create a document node A underneath root node R
- navigate back to root node R
- the node A disappears from the document node tree.
After a cache flush OR a modification on root node R, the node stays visible.
However, on the demo page, the cache is flushed nevertheless because of the tag
`NodeType_Neos.Neos:Document`, which the Menu Cache Segment listens to. If you
place a Menu on the page, then this menu has its own cache segment, which gets
flushed on ANY Document change -- and then we re-render the full page, because
ContentCache::replaceCachePlaceholders returns FALSE as soon as it cannot find
a single sub-entry.
In order to test the issue on the Demo page, you need to:
- remove all Menu and DimensionMenu elements from Fusion
- remove the Neos.Seo package (because that internally …
> BUGFIX: ensure JS backend information is not stale (fixes node tree after node creation)

- packages/react-ui-components/src/SelectBox/selectBox.js
Steps to reproduce:
1. Create a link in CKE. Start typing something to find a node.
2. Collapse the search results by clicking the arrow
3. From this moment if you start typing, or even create another link, the search results will always stayed collapsed
Desired behavior: on typing new search term the SelectBox should always open.
> BUGFIX: open SelectBox on searchTerm change

- packages/neos-ui-guest-frame/src/dom.js
For custom rendering cases of Content Collections, is is weird
to have the "empty placeholder" rendered even though the content
collection is perfectly visible and selectable.
We now determine additionally based on the visual height of the collection 
whether the placeholder should be rendered or not.
Fixes: #1150
> BUGFIX: If a content collection is rendered too big, do not display empty-collection-overlay

- Classes/Neos/Neos/Ui/Controller/BackendServiceController.php
- Configuration/Routes.Service.yaml
- Tests/IntegrationTests/contentModule.js
- packages/neos-ui-backend-connector/src/Endpoints/index.js
- packages/neos-ui/src/Sagas/CR/ContentDimensions/index.js
Fixes: #1114 
I'm not happy about how this is fixed architecture-wise, but I couldn't think of anything better without spending too much time redesigning the whole thing.
Besides being ugly and ad-hoc, it requires an extra ajax request when adopting a node.
In the future I see such data fetching needs be put in order via the upcoming GraphQL integration.
> BUGFIX: refresh workspace info when adopting a node to other dimension

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
to fix top position of toolbar after the page reloads
Fixes: #1073
> BUGFIX: Add 'load' eventListener to NodeToolbar

- Configuration/Settings.yaml
- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
- packages/neos-ui-redux-store/src/UI/ContentCanvas/index.js
- packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
- packages/react-ui-components/src/Frame/frame.js
- Go to page A in document tree
- navigate to page B in content area
- select page A in document tree again
- expected: selection to page A works
- actual: no navigation is triggered to PageA
- ensure the redux state is always up to date
- do not trigger page refreshes if the URL is already correct in the iFrame
Additionally, the loading indicator does not need to be handled through SET_SRC
anymore, as this is now implemented differently (so that's a code cleanup).
> BUGFIX: Fix navigation in tree after an in-page navigation

- Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
In a project, we had the bug that the node tree search broke with an
exception because the /sites node did not have an URI path segment (which
is fine).
After debugging, I did the following two changes:
- display an error indicator if the document tree search returned with an
exception
- in the logic which builds the rootline for the document tree, ensure we
are always underneath the /sites node; and do not traverse upwards
otherwise
> BUGFIX: make document tree search more robust

- packages/react-ui-components/src/SelectBox/selectBox.js
- packages/react-ui-components/src/SelectBox/style.css
This fixes the double 'selected hover state' (it was possible to, at least visual, select 2 items when using mouse and keyboard in a specific way) and resets the selectbox after closing
Edit: This currently doesn't work for searchable selectboxes and also breaks  their hover state.
But I'm on it while implementing keyboard navigation along the way https://github.com/neos/neos-ui/issues/1162
> TASK: Make Keyboard Navigation in SelectBox more robust

- packages/neos-ui-backend-connector/src/Endpoints/index.js
Without this if you pick an image from media browser, the endpoint
request would be prefixed with the path of the media module, e.g.:
`/neos/media/browser/neos/content/image-with-metadata?image=***`
For some reason that happened only in Firefox for me.
> BUGFIX: change all endpoint uris to start from root

- Classes/Neos/Neos/Ui/ContentRepository/Service/WorkspaceService.php
Otherwise if some entries were filtered out publishableNodes will get rendered as object to JSON, and not an array, which will break publishing.
> BUGFIX: reset keys of publishableNodes after filtering

- packages/neos-ui-backend-connector/src/index.js
- packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
- packages/neos-ui/src/apiExposureMap.js
- packages/neos-ui/src/index.js
I'm working on a prototype for an extension of the UI and found those two important to be generally available.
Currently there's no general way to access the redux store - only mechanisms like Feedback Handlers that expect it as a parameter. This thoroughly limits the possibilities for extensions. With this PR it is exposed as a second parameter to the manifest bootstrap function.
`fetchWithErrorHandling` is required to make Backend requests using the current CSRF token - which is inaccessible otherwise.
> FEATURE: Expose fetchWithErrorHandling and redux store for extensibility

- packages/neos-ui-guest-frame/package.json
- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
- packages/utils-helpers/src/cancelIdleCallback.js
- packages/utils-helpers/src/index.js
- packages/utils-helpers/src/requestIdleCallback.js
This change removes the usage of `window.requestCallback()` as it is not supported in Safari right now.
> TASK: Remove usage of `window.requestCallback()`

- packages/neos-ui-ckeditor-bindings/src/boostrapCkEditorApi.js
- packages/neos-ui-ckeditor-bindings/src/ckeditor/index.js
- packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
- packages/neos-ui-ckeditor-bindings/src/guestFrameApi.js
- packages/neos-ui-ckeditor-bindings/src/manifest.js
- packages/neos-ui-ckeditor-bindings/src/manifest.plugins.js
- packages/neos-ui-ckeditor-bindings/src/registry/CkEditorPluginsRegistry.js
This PR implements a way to register custom CKeditor plugins via a registry.
THIS IS NOT A PUBLIC API YET!
May break as we migrate to CKE5 soon.
> FEATURE: pluginsRegistry

- packages/neos-ui-ckeditor-bindings/src/registry/CkEditorFormattingRulesRegistry.js
Space delimiter only works with tag names. If you have also attributes in the rule, they should be semicolon delimited.
> BUGFIX: use correct delimiter for extraAllowedContent rules

- Classes/Neos/Neos/Ui/Domain/Service/StyleAndJavascriptInclusionService.php
Resolves: #1143
I have experienced multiple times that the old interface version got heavily cached in the editor's browser, which caused some hard to debug bugs.
I think it makes sense to add cache bursting to all asset links.
> TASK: add md5 cache breaker to all resource urls

- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
After changing the aspect ratio of the crop area, we
should also trigger a refresh of values to make those
appliable immediately.
Fixes: #1204
> TASK: Apply new area also after aspect ratio change

- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui-editors/src/EditorEnvelope/style.css
With React 16 error boundaries were introduced to limit the effect
of errors on an react app. The EditorEnvelope is now a natural
error boundary and so effectively keeps errors in inspector editors
to the editor.
Fixes: #1137
> TASK: Inspector editors have error boundary

- packages/neos-ui-editors/src/Editors/CodeMirror/index.js
- packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/index.js
- packages/neos-ui-editors/src/Editors/Image/index.js
- packages/neos-ui-editors/src/SecondaryEditors/CodeMirrorWrap/index.js
- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/AspectRatioDropDown/index.js
- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
This removes constructors from all components in the `neos-ui-editors`
package and uses arrow functions as class properties instead
of binding. This makes the code a bit more concise.
Related: #979
> TASK: Remove constructors from the neos-ui-editors package

- Tests/IntegrationTests/contentModule.js
- packages/neos-ui/src/Containers/EditModePanel/index.js
- packages/neos-ui/src/Containers/PrimaryToolbar/EditModePanelToggler/index.js
- packages/neos-ui/src/Containers/PrimaryToolbar/LeftSideBarToggler/index.js
- packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
closes #1210
It is currently not possible to translate `User Settings` in the user dropdown.
The id is: `userSettings.label` and in the code is this line: https://github.com/neos/neos-ui/blob/master/packages/neos-ui-i18n/src/registry/I18nRegistry.js#L75 which replaces every `.` with an `_`.
Don't have time to fix it now so I will open an issue.
> TASK: Add missing translations

- Resources/Private/Templates/Backend/Index.html
- packages/neos-ui/src/System/index.js
This exports the initial backend data as JSON directly instead
as HTML strings. This prevents double escaping (and potential issues
related to that) as well as parsing in our JS.
Values are stored in global JS variables until read and then deleted.
> TASK: Export data as JSON

- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/neos-ui/src/Containers/LeftSideBar/index.js
- packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeItem.js
This removes constructors from all components in the neos-ui
package and uses arrow functions as class properties instead
of binding. This makes the code a bit more concise.
Related: #979
> TASK: Remove contructors from neos-ui

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
Prevents rendering of additional metadata via script tags
when rendering in live context.
Fixes: #1200
> TASK: Do not render backend data in live context

- packages/neos-ui/src/Containers/ContentCanvas/index.js
Re-fix #863 - this was broken by one of the changes in the meantime.
> BUGFIX: fix background color for content canvas

- packages/neos-ui-editors/src/Editors/Reference/index.js
- packages/neos-ui-editors/src/Editors/References/index.js
- packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js
- packages/neos-ui-editors/src/Editors/SelectBox/SimpleSelectBoxEditor.js
This has never worked before because the defaultOptions are static; so we
need to reference them statically as well.
> BUGFIX: correctly use default options in Select Boxes and Reference(s) editors

- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/Helpers/hideDisallowedToolbarComponents.js
- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/Helpers/renderToolbarComponents.js
- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/StyleSelect.js
- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/index.js
- packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
- packages/neos-ui-ckeditor-bindings/src/manifest.formattingRules.js
- packages/neos-ui-ckeditor-bindings/src/manifest.js
- packages/neos-ui-ckeditor-bindings/src/manifest.richtextToolbar.js
- packages/neos-ui-ckeditor-bindings/src/registry/RichTextToolbarRegistry.js
- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui/src/index.js
While building https://github.com/sandstorm/BlockStyles, I found the internal
API for configuring the RTE lacking some features. Specifically, the following
has changed with this PR:
The old format looked like this:
```
ui.aloha:
[…]
h2: true
h1: false
```
This was then server-side transformed to:
```
aloha:
[…]: h2
```
-> i.e. false values were removed automatically.
Now, I wanted to make it possible to add specific options to the inline
editor instance (more than the "TRUE/FALSE" from above).
Thus, I created a new format:
```
ui.inline.editorOptions:
formatting:
h2: true
h1: false
placeholder: "placeholder string"
autoparagraph: true
```
… which is used internally throughout the codebase; and the old "aloha"
format is converted to the new format.
This enables to pass in arbitrary …
> FEATURE: Improve ckeditor configurability

- packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
This (re-) enables basic HTML entity encoding, to avoid
for example opening HTML comments breaking the site.
Fixes: #1257
> BUGFIX: Enable basic entities encoding

- packages/react-ui-components/src/SelectBox/style.css
The load indicator rotates and when the background is black a square is rotating. Which looks weird.
Fixes #1187
> BUGFIX: Remove black background of load indicator

- Classes/Neos/Neos/Ui/NodeCreationHandler/DocumentTitleNodeCreationHandler.php
URI path segment was md5-hash, when something other than the title-property was used in the creation dialog of a document. Using the nodeUriPathSegmentGenerator to allow label or name as URI path segment
> BUGFIX: Use URI path segment generate on document creation

- packages/neos-ui/src/Containers/EditModePanel/index.js
The EditModePanel component used the I18n component for the Panel title.
The proptype of the title was string so this not match with the component type.
Replaced the component with the i18nRegistry to just get a string.
Fixes: #1301
> BUGFIX: Resolve issue with proptype checker

- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/model.js
If a default aspect ratio setting is unset  by using ‘~’ a js exception is thrown when you open the cropping editor. In order to avoid this issue, “null" values have to be filtered for using the presets.
> BUGFIX: filter unused aspectRatio crop presets in ImageCropper editor

- packages/react-ui-components/src/DropDown/style.css
- packages/react-ui-components/src/SelectBox/style.css
The selectBox has a dropdown chevron icon and can
have also a loading indicator or a reset button.
The rendered separator should be optional so that the dropdown without
additional button has no separator.
Fixes: #1319
> TASK: Render separator of chevron only with additional button

- packages/react-ui-components/src/ToggablePanel/__snapshots__/toggablePanel.spec.js.snap
- packages/react-ui-components/src/ToggablePanel/toggablePanel.js
- packages/react-ui-components/src/ToggablePanel/toggablePanel.spec.js
The most ToggablePanel components does not provide the `onPanelToggle` prop and if the prop is provided, the component will not use the internal state, instead it will be controlled by the props.
The default state is false and so the most ToggablePanel does not open on default.
Therefore the default is changed to true.
Fixes: #1323
> TASK: Set isOpen default state to true

- packages/react-ui-components/src/ToggablePanel/index.story.js
The storybook of ToggablePanel still uses togglePanel,
but this property has been renamed.
Fixes: #1327
> BUGFIX: Use onTogglePanel instead of togglePanel

- packages/react-ui-components/src/Icon/__snapshots__/icon.spec.js.snap
- packages/react-ui-components/src/Icon/icon.js
- packages/react-ui-components/src/Tree/node.css
Currently it's not feasible to switch without major styles refactoring,
it's way too breaking
> BUGFIX: revert back to an unsemantical tag name for icons

- packages/neos-ui-views/src/ViewEnvelope/index.js
Otherwise label duplication happens:
> BUGFIX: fix has own label for inspector views

- packages/neos-ui-i18n/src/index.js
`null` does NOT trigger fallback parameters, `undefined` does!
Fixes: #1339
> BUGFIX: correctly trigger fallback parameters by not passing null in I18n component

- packages/react-ui-components/src/Button/__snapshots__/button.spec.js.snap
- packages/react-ui-components/src/Button/button.js
- packages/react-ui-components/src/Button/button.spec.js
default type is submit if not given. Thus browsers are supposed to submit the form with the button which breaks react onClick handlers. By giving a default type of type="button" browsers won't submit automagically while we wait for react to do something (testable in Firefox)
> TASK: set button default type to button

- packages/react-ui-components/src/SelectBox/selectBox.js
- packages/react-ui-components/src/SelectBox/style.css
Adds separator to own element.
Also show the separator depending on the amount of icons.
You can have a chevron when the options are available together with a loader or a reset or just a single loader or reset.
The chevron is of course always in the right. So with this PR we can now have the reset and the loader also on the right position if no chevron is visible and if the chevron is there the position is left to the chevron.
The following screen shows some possible options.
Fixes: #1336
> BUGFIX: Fix rotation of separator

- packages/neos-ui-editors/src/SecondaryEditors/MediaSelectionScreen/index.js
It's still the hard coded URL but it fixes this bug for now.
closes #1353
> BUGFIX: Filter all in asset editor

- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/react-ui-components/src/Frame/frame.js
This PR fixes a couple of issues with the frame origin control mechanism for the Content Canvas frame:
* Primarily, the `beforeunload` event handler in the `<ContentCanvas>` container is removed (This is what caused #1324). An unfortunate side effect of that is, that if a site like "spiegel.de", which has no proper X-Frame headers (like e.g. "google.com"), is loaded in the frame, the site will be visible as long as it takes for the `load` event to fire. Afterwards, the UI will recognize that it has lost control and will navigate the user back to the last page, just as intended by the original feature.
* The `<Frame>` component did not handle cross-origin situations correctly. This PR adds error handling to the `updateIframeUrlIfNecessary` method to set the Iframe source instead of …
> BUGFIX: Fix iframe control mechanism

- packages/react-ui-components/src/SelectBox/config.js
- packages/react-ui-components/src/SelectBox/selectBox.js
- packages/react-ui-components/src/SelectBox_HeaderWithSearchInput/selectBox_HeaderWithSearchInput.js
- yarn.lock
Arrow handling in searchable selectbox is working now.
The ESC button is working in a normal selectbox, in searchable selectboxes I have to press ESC two times because the first keypress got absorbed somewhere.
references #1388
> BUGFIX: Restore keyboard handling for selectBox

- packages/build-essentials/src/styles/styleConstants.js
- packages/neos-ui/src/Containers/App.js
- packages/neos-ui/src/Containers/SecondaryToolbar/LoadingIndicator/style.css
- packages/neos-ui/src/Containers/SecondaryToolbar/index.js
This change move the loading indicator from bellow the SecondaryToolbar to the top of the UI. 
This fix an issue when loading with the navigate component closed (wrong left position), but also make the loading indicator more global from the user perspective. We can use the loading indicator during publishing or any other action that require a bit of time. In the future, the loading a backend module can also use this indicator, or an action performed in a backend modules.
> TASK: Move the loading indicator on the top of the UI

- packages/react-ui-components/src/Tree/node.css
I had to reduce the top/bottom padding of the `node__header__data`
and increate the line-height of `header__labelWrapper`
All other methods I tried looked crappy.
Maybe someone else has a nicer way of solving this.
closes #1401
> BUGFIX: Don't cut letters in page tree

- packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/style.css
Resolves: #1406 
More or less how it looked in the old UI:
> TASK: better styling of AssetOption, with bigger image

- Resources/Private/Translations/en/Main.xlf
- packages/neos-ui-ckeditor-bindings/package.json
- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js
- packages/neos-ui-ckeditor-bindings/src/manifest.richtextToolbar.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/AddNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CopySelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CutSelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/DeleteSelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/HideSelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/PasteClipBoardNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/AddNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CopySelectedNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/CutSelectedNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/DeleteSelectedNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/HideSelectedNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/PasteClipBoardNode/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/RefreshPageTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
- packages/neos-ui/src/Containers/RightSideBar/index.js
- packages/react-ui-components/src/Tabs/tabs.js
This PR is based on the work of @janinadanger and @johannessteu here: #997 
It uses native tooltips for simple things like buttons. This has the advantage of better performance and native UX.
The custom tooltips will be ported in a separate PR and used for things like validation or help messages.
> TASK: add native tooltips to buttons

- packages/react-ui-components/src/reset.css
The publish button has a margin on the right hand side in safari. This bugfix sets the margin explicitly to 0.
Before: 
After:
> BUGFIX: remove margin from publish button

- packages/react-ui-components/src/reset.css
In Safari all search boxes looked like this:
Now they are looking fine:
It also fixes #1403.
> BUGIFX: remove Safaris webkit-apperance default

- packages/neos-ui-contentrepository/src/registry/getNormalizedDeepStructureFromNodeType.js
> BUGFIX: retain original sorting index in getNormalizedDeepStructureFromNodeType

- README.md
When you have a clean system without a chrome your end to end tests will fail. So we should add the information to the README to prevent frustration of the end users.
Resolves: #1420
> TASK: Extend README with integration tests section

- Classes/Neos/Neos/Ui/ContentRepository/Service/WorkspaceService.php
In the old UI code, this was done in TargetWorkspaceController.js#targetWorkspaces;
where a check of "isUserWorkspace" happened (which
in turn checked whether the workspace name started
with "user-").
We now replicate this logic in the backend.
I am not 100% sure why this is needed, as this might
only occur when the "OWNER" of the user workspace is NULL
(and I am not sure how this can happen - maybe when a user
is deleted but the corresponding workspace prevails?)
> BUGFIX: ensure other people's personal workspaces are never shown in workspace selector

- packages/neos-ui-redux-store/src/UI/LeftSideBar/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/style.css
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/style.css
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/ToggleContentTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/ToggleContentTree/index.spec.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/style.css
- packages/neos-ui/src/Containers/LeftSideBar/index.js
- packages/neos-ui/src/Containers/LeftSideBar/style.css
This removes magic numbers from CSS; and fixes styling bugs
when new components are rendered in the Navigate Component using
unplanned extensibility (e.g. like https://github.com/sandstorm/FulltextSearchInNodeTree).
It should not have any UI/style implications; I checked the old
and new UI side-by-side and took screenshots of both of them, and
I think they match pixel-perfect.
By not relying on ToggablePanel and the inner logic thereof for
auto-sizing and animation; and instead using flexbox, the robustness
of the CSS in the navigate component could be improved and the logic
simplified.
> BUGFIX: rework Navigate component CSS to use flexbox

- Build/TravisCi/composer.json
We are having some issues with autoload on master: https://neos-project.slack.com/archives/C050KKBEB/p1513598394000259
> TASK: pin Neos to 3.2 for Travis E2E tests

- packages/neos-ui-backend-connector/src/Endpoints/Helpers.js
Without this change, the URL path part of the UI is
completely discarded if not having absolute URLs.
On Neos.io, this is fixing various issues related to data
providers, serialization, ...
I am unsure why this does not happen locally.
> BUGFIX: urlWithParams must take urlString into account

- Configuration/Settings.yaml
Without this change, the Preview button always points to the
Live workspace (which is of course wrong when using nested
workspaces).
> BUGFIX: Workspace preview should point to base workspace

- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js
To reproduce:
- create an external link in some text
- place the cursor after the text
- navigate using the arrow keys into the linked text
actual behavior (bug):
- focus jumps into the Link-Text-Box
expected behavior:
- focus stays in the main text
> BUGFIX: Do not focus link editor when navigating through text

- packages/neos-ui/src/Containers/Drawer/style.css
so that the chars of the MenuItems are starting all
at the same place
closes #1470
> BUGFIX: Set an explicit width for the icons

- package.json
- yarn.lock
The current used version 2.14.1 is marked as insecure.
Therefore it would be good to upgrade the package.
It turns out that testcafe has issues with the current momentjs and therefore Is submitted some patches to them.
Hope that they get merged soonish and find the way into a new release.
Otherwise this is blocked for a while ;)
https://github.com/DevExpress/testcafe-reporter-spec/pull/4
https://github.com/DevExpress/testcafe-reporter-list/pull/4
Fixes: #1359
> Update to latest moment js version 2.20.1

- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractCreate.php
Node creation handlers are a new way to react on node creation triggered by a front-end action. One implementation is the node template package, which makes it possible to add arbitrary child nodes to the created node. We only have signals for nodeCreation of a single node, but none to react on the completion of the complete node creation process.
Usage Example: 
1. A node is created, a news node for example.
2. [Node templates](https://github.com/Flowpack/Flowpack.NodeTemplates) create a structure of nested nodes beneath the news node, including one that contains the date of the news.
3. After all nodes are created, the news node now needs to be moved into a date hierarchy using [archivist](https://github.com/punktDe/archivist) using this date.
> FEATURE: Add a signal after node creation handles are applied

- packages/react-ui-components/src/Icon/icon.js
- packages/react-ui-components/src/Icon/icon.spec.js
Removes the FontAwesome warning and allows custom icon classnames.
Fixes 1572
> TASK: Allow custom icon classnames

- Configuration/NodeTypes.yaml
Depends on this change: neos/neos-development-collection#1871
Fixes: #1539
> TASK: Change node title label in creation dialog to i18n

- packages/neos-ui/src/index.js
When loading the Neos UI, a text "Loading..." appears that is not
localized. It is displayed at a very early stage of UI initialization
when the language labels have not been fetched yet.
This change makes use of a spinning icon instead of text.
Fixes: #1459
> TASK: Use loading spinner instead of (non-localized) text

- packages/neos-ui/src/Containers/EditModePanel/Panel/slick-styles.vanilla-css
The width of the slick slider was not set, so not all modes were displayed.
Fixes: #1589
> BUGFIX: Show all modes in Preview Central

- packages/build-essentials/src/webpack.config.js
UglifyJs disables sourcemaps by default: https://github.com/webpack/webpack/issues/2704
We need sourcemaps to be enabled, right now it's next to impossible to debug issues in production.
> TASK: enable sourceMaps in production build

- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js
- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/style.css
- packages/react-ui-components/src/SelectBox/selectBox.js
Fixes: #1527
This behavior fully replicates the one from the old UI:
>  TASK: better editing of external links

- Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
Fixes `Call to undefined method Neos\Neos\Ui\Domain\Model\Feedback\Operations\ReloadContentOutOfBand::getReferenceData()`
> BUGFIX: fix ReloadContentOutOfBand feedback

- Classes/Neos/Neos/Ui/Domain/Model/Changes/Property.php
- packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
Fixes: #1366
Also fixes this when editing a property inline:
```
Exception in line 36 of /Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Neos_Ui_Domain_Model_ChangeCollection.php: Call to a member function getFusionPath() on null
37 Neos\Neos\Ui\Domain\Model\Changes\Property_Original::apply()
36 Neos\Neos\Ui\Domain\Model\ChangeCollection_Original::apply()
35 Neos\Neos\Ui\Controller\BackendServiceController_Original::changeAction(Neos\Neos\Ui\Domain\Model\ChangeCollection)
```
> BUGFIX: fixes inline editable property triggering page reload on each change

- README.md
The README is not up2date in the currently used node version.
The UI does not work anymore with node 6.10
Resolves: #1628
> TASK: Update node version in README

- lerna.json
- packages/react-ui-components/package.json
This is autogenerated by `node_modules/.bin/lerna publish --skip-git --exact --repo-version=1.0.5 --yes --force-publish --skip-npm
` so the empty dependency object should remain in the react-ui-components package I think.
> TAKS: Adjust lerna version after publishing the extensibility package

- .editorconfig
- Build/Jenkins/update-neos-ui-compiled.sh
- Build/TravisCi/InstallScripts/IntegrationTests.sh
- Build/TravisCi/Scripts/CodeStyle.sh
- Build/TravisCi/Scripts/IntegrationTests.sh
- Build/TravisCi/Scripts/UnitTests.sh
- Makefile
- README.md
- package.json
references #1629 
I would update the docs if we decide to merge it.
I would love to hear what you people think of this.
> TASK: Exchange yarn with make as build tool

- Classes/Neos/Neos/Ui/Domain/Model/Changes/AbstractMove.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveAfter.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveBefore.php
- Classes/Neos/Neos/Ui/Domain/Model/Changes/MoveInto.php
when moving nodes, it sometimes happened that the node
on the original location was not removed.
It turned out that the "Remove" Feedback (which is part
of the feedbacks returned on move) got transmitted
with the wrong contextNodePath (e.g. where the node was
*already moved*); thus it could not be removed in the UI.
For me in some cases it correctly worked; though I was
not able to track the issue down to specific cases. In
90% of the cases it did NOT work. I tested with a custom
4-column element; where moving in the columns 2-4 reliably
triggered the error. Interestingly, moving from Column1
mostly worked...
the "clone" only clones the node; without cloning the
corresponding NodeData object. The fix is to additionally
clone the NodeData object itself; thus we detach it
from persistence, …
> BUGFIX: make moving of nodes more robust

- Classes/Neos/Neos/Ui/Aspects/NodeTypeSchemaCacheHeaderAspect.php
- Classes/Neos/Neos/Ui/Controller/BackendServiceController.php
- Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/Redirect.php
- Classes/Neos/Neos/Ui/FlowQueryOperations/NeosUiDefaultNodesOperation.php
- Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
- packages/neos-ui-backend-connector/src/Endpoints/index.js
- packages/neos-ui-backend-connector/src/FlowQuery/Operations/NeosUiDefaultNodes/index.js
- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui-redux-store/src/UI/PageTree/index.js
- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/neos-ui/src/Containers/Drawer/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
- packages/neos-ui/src/Containers/LeftSideBar/index.js
- packages/neos-ui/src/Containers/RightSideBar/index.js
- packages/neos-ui/src/Sagas/CR/ContentDimensions/index.js
- packages/neos-ui/src/Sagas/CR/NodeOperations/index.js
- packages/neos-ui/src/Sagas/CR/NodeOperations/reloadState.js
- packages/neos-ui/src/Sagas/Publish/index.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
- packages/neos-ui/src/index.js
- packages/neos-ui/src/manifest.js
- packages/neos-ui/src/manifest.sagas.js
- packages/react-ui-components/src/DropDown/contents.js
- packages/react-ui-components/src/Tabs/tabs.js
- packages/react-ui-components/src/Tree/node.js
- Eases the pain of slow nodes state rendering by fetching default nodes asynchronously (#1579)
- Unify logic for re-fetching nodes state
- Reload nodes when switching workspaces, redirect to correct node if it doesn't exist in target (Fixes: #1464)
- Reloads the tree in one gulp, without extra requests
- Fixes loading indicator
- Loads default nodes + toggled nodes + nodes up to the current document node in one request
- Parallelizes JSON fetch requests for translations and other stuff (Improves #1020)
- Don't render hidden elements (improves render time from 1100ms down to 120-360ms!) (Fixes: #887 )
> TASK: refactor nodes loading

- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
Steps to reproduce:
1. focus the document node in content tree
2. see the dimension switcher dissapear
> BUGFIX: dimension switcher shouldn't disappear when focusing document node in content tree

- .travis.yml
- Classes/Neos/Neos/Ui/Controller/BackendServiceController.php
- Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/Redirect.php
Removes incompatible return type annotations (`void`) and adds PHP 7.0
to Travis CI to catch bugs for PHP 7.0.
> BUGFIX: Fix PHP 7.0 compatibility

- packages/neos-ui/src/styleHostOnly.css
closes #1202
Google reverted this change so this isn't needed anymore.
Can anyone with a Mac test if this is really the case?
> TASK: Remove quickfix for chrome border radius

- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/style.css
The border is 8px top and bottom so I think it is correct
that the height of this is xx + 16px (spacing-Full)
closes #1609
> BUGFIX: Let the SelectboxInput look good in firefox

- packages/neos-ui-editors/src/Editors/TextArea/index.js
- packages/react-ui-components/src/TextArea/textArea.js
The Placeholder option wasn't not correctly passed to the textarea
This also passes the expandedRows and minRows to the texarea
closes #1660
closes #1487
> BUGFIX: Pass placeholder to TextArea

- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/react-ui-components/src/Frame/frame.js
* Setting width and height on the html element led to false behaviour by using the media queries referring to the browser window not the (preview) viewport size. 
* Elements with fixed or absolute position had the wrong reference container (like on the Neos.Demo) 
* animation of the Preview Frame was broken.
Reverted #1662 and added overflow: auto to surrounding container if width or height are set to keep scrollbars in small browser windows.
> Fix: preview mode with scrollbars

- packages/neos-ui-editors/src/Editors/PluginView/index.js
The PluginView used a state that is not really set. The wrong property was used.
Fixes: #1495
> BUGFIX: Use correct state property in PluginView editor

- packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
Hiding empty groups in inspector view
Added not empty condition to view that got lost in d4f8a09
> BUGFIX: Hide empty groups in inspector

- packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
Fixes: #1683
We need to prevent closing the dropdown, otherwise it'd remove the form from DOM before it actually gets submited.
> BUGFIX: fix logout

- packages/neos-ui/src/Containers/Modals/DeleteNode/index.js
Fixes the translation in the Delete Confirmation Dialog by using the right identifier
> BUGFIX: set correct translation value to delete confirmation

- Classes/Neos/Neos/Ui/Fusion/Helper/NodeInfoHelper.php
If nodes for tree are loaded after contentCanvas nodes, the `isFullyLoaded` flag would be merged as false, infinitely showing the spinner in inspector.
> BUGFIX: fix race condition when merging tree nodes

- packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
Currently it's possible to publish/discard twice, while another publish is in progress. That lead to corruption of CR sometimes (which should be a separate issue actually).
> BUGFIX: don't allow to publish/discard while publishing/discarding/saving

- package.json
- yarn.lock
Updates the node js version to the latest 8.x release. The latest release was a security release and guess we should use it.
Resolves: #1731
> TASK: Update nodejs dependecy to version 8.11.0

- Classes/Neos/Neos/Ui/Aspects/PolicyAspect.php
With this change, we are actually checking whether there are policies configured for the given PrivilegeTargets; and if not, we skip these code blocks.
For a node tree with 1000 nodes, this improves the node tree loading time from 15 to 5 seconds (AJAX request time)
> BUGFIX: improve performance for PolicyAspect

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
without this fix, all nodes in the node tree get redrawn everytime
the user selects a different node; which leads to prohibitive performance
when switching nodes.
> BUGFIX: Improve performance of switching between nodes in NodeTree

- Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
- Classes/Neos/Neos/Ui/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
This extends the `try/catch` block in `ReloadContentOutOfBand` and
`RenderContentOutOfBand` so that if falls back to reloading the whole
document when a Fusion exception occurs.
Previously only the more specific `MissingFusionObjectException` was
caught.
Note: This is a follow up to #1693
> BUGFIX: Catch all fusion exceptions when rendering content "out of band"

- packages/neos-ui-ckeditor-bindings/src/manifest.richtextToolbar.js
**What I did**
Indent & outdent buttons of CKEditor show:
* only if they are possible (outdent only if indented)
* if cursor is in `ol` or `ul` OR
* if configured to `true`
Adjusted `isVisibleWhen` condition.
> BUGFIX: In- & outdent can be disabled outside of lists

- packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
**What I did**
In one instance I had the problem not being able to open up the property groups once closed.
In the other instance the "Additional Info" (node metadata) group starts up opened.
Using explicit typecast to bool instead of relying on implicit typecasting.
Close & open property groups, check status of "Additional Info" property group.
> BUGFIX: PropertyGroup (un)collapsing

- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/model.js
Partially fixes https://github.com/neos/neos-ui/issues/1525#issuecomment-376122477
It respects the default crop option, but does not enforce it by default yet.
> BUGFIX: respect default option in cropping

- Makefile
The `PHONY`-target was wrong. 
This change correctly marks every target as the special phony target and therefore shouldn't make any problems with case-insensitive filesystems now.  (make build and the folder Build didn't work well together)
For everyone who didn't know: 
`make build` is the target build `make test` would be the target test and so on.
Make can remember when it performed a task and doesn't retrigger it if nothing has changed since then.
The target is usually a file or folder and make compares the timestamp from the last run of this target and the last changed time the file was changed on disk and don't rerun the target if file/folder >= last run.
PHONY tells make to re-run the target everytime without comparing timestamps and stuff.
> BUGFIX: Correct the phony target

- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/model.js
Uses plow.js to be sure that the value is defined for the default option.
Fixes: #1759
> BUGFIX: Prevent error when no defaultOptions are defined

- packages/build-essentials/src/styles/styleConstants.js
The secondary inspector has two constants for z index. The close
button needs to be incresed to value higher than 3. And the
possible iFrame has not z index yet. So we define a iframe zindex constant and so we also increase the close button constant.
Fixes: #1748
> BUGFIX: Increase close button z- index

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
This is a follow-up to #1648 that adds a safeguard to `AugmentationAspect::contentElementAugmentation()` hopefully fixing the CI
Related: #1647
> BUGFIX: Add safeguard to AugumentationAspect

- packages/neos-ui-editors/src/Editors/DateTime/index.js
- packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
- packages/react-ui-components/src/DateInput/dateInput.js
- packages/react-ui-components/src/DateInput/index.js
- packages/react-ui-components/src/DateInput/style.css
The createDialog apply button now will be not disabled anymore
and validates all elements in the dialog. Even if the element
has not been edited yet.
Fixes: #1320
> TASK: Validate editor elements on apply

- packages/react-ui-components/src/DateInput/style.css
The datetime form field does not render the invalid border
color red when the input field is in the right inspector bar.
In the create dialog it works without important!
Fixes: #1780
> BUGFIX: Fix red borders for invalid datetimes

- packages/react-ui-components/src/Button/style.css
- packages/react-ui-components/src/DropDown/style.css
I tried this today and it seems firefox isn't really set the focus selector properly when navigating with the keyboard.
But when toggling the pseudoselector via dev-tools I can see that it is applied correctly to that element.
Maybe anyone has an idea?
closes #1600
> TASK: Define a global outline to be the same in all browsers

- packages/neos-ui/src/Containers/ContentCanvas/index.js
Before the loading indicator would only show when the iframe started to unload. For pages with long TTFB that could be quite a while.
> BUGFIX: show the loading indicator as soon as the src has changed

- Classes/Neos/Neos/Ui/Domain/Dto/LoadTreeDto.php
Remove var_dump and die() that has been added in commit
a67a8bd4071e149156a5503e6468f7822e996b79.
It looks like an accidental leftover from the early beta phase.
> TASK: Remove debug statements

- package.json
- yarn.lock
Resolve warnings in the yarn install process.
Relates: #877 
Resolves: #1801
> TASK: Update react-slick to version 0.23.1

- package.json
- packages/react-ui-components/package.json
- yarn.lock
Fixes two things:
* warning while install process with yarn
* lot off bugs in the library and get closer to the green dependency bar :)
Relates: #877 
Resolves: #1799
> TASK: Update react-collapse to version 4.0.3

- package.json
- packages/neos-ui/package.json
- yarn.lock
Issue #877 is more or less a collection of tasks ... so i started here with the removal of 2 warnings.
The package redux-saga-test-plan uses the packages that leads to the warnings and they solved this in version 3.4.
The latest is 3.6 so i upgraded to the latests one.
Resolves: #1797
> TASK: Update redux-saga-test-plan to 3.6.0

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
The quickfix for ContentElementWrapping for neos 3.2 could be
remove. The handling has been adjusted. So that the
ContentElementWrappingImplementation of fusion already take
care of it.
> TASK: Remove quickfix for ContentElementWrapping

- package.json
- yarn.lock
The uuid package is some versions behind. This updates the package to the latest version 3.2.1.
Resolves: #1810
> TASK: Update uuid to version 3.2.1

- composer.json
Since we are technically compatible with Neos 3.3, let's allow the UI to run there, without requiring extra branches.
> TASK: allow the UI to run on Neos 3.3

- Configuration/Settings.yaml
- packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
This introduces a new Setting to control whether the switch to old UI button should be shown or not.
```
Neos:
Neos:
Ui:
frontendConfiguration:
legacy:
enableUiSwitch: <bool>
```
related https://github.com/neos/neos-development-collection/pull/2021
> TASK: Optionally disable old UI button

- packages/neos-ui-editors/src/Editors/Image/index.js
- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
Resolves: #1525 
Adds an option to the Image editor to force showing the crop dialog on image upload. Could be especially useful for image editors with locked crop aspect ratio.
TODO: add documentation
```
properties:
teaserImage:
ui:
inspector:
editorOptions:
crop:
aspectRatio:
forceCrop: TRUE
```
> FEATURE: implement forceCrop option for Image editor

- Classes/Neos/Neos/Ui/Aspects/AugmentationAspect.php
- Classes/Neos/Neos/Ui/Aspects/NodeTypeSchemaCacheHeaderAspect.php
- Classes/Neos/Neos/Ui/Aspects/XliffConfigurationCacheHeaderAspect.php
- Classes/Neos/Neos/Ui/Controller/BackendController.php
- Classes/Neos/Neos/Ui/Fusion/Helper/ActivationHelper.php
Fixes: #1729 
With this change we invert the behavior of the session parameter and make the new UI activated by default, and storing `__neosLegacyUiEnabled__` into the session with the user clicks "Switch to old UI".
Obviously it won't alter the behavior of old systems without the neos-ui package installed.
> BUGFIX: prevent "backend in backend" behavior after session expires

- packages/neos-ui-editors/src/Editors/Image/index.js
Before the fix, if you had `forceCrop` enabled for image editor, and had a property configured to reload the page, after page reload you would see the image cropper again.
> BUGFIX: fix forceCrop mode on auto-reloaded properties

- package.json
- packages/neos-ui-editors/src/SecondaryEditors/CodeMirrorWrap/index.js
- yarn.lock
The react-codemirror package is more or less unmaintained and
so we switch to the fork react-codemirror2.
So this replaces the package and adjusts the SecondaryEditor.
Resolves: #1814
> TASK: Replace  react-codemirror with  react-codemirror2

- package.json
- packages/build-essentials/src/webpack.config.js
- packages/react-ui-components/src/Icon/index.js
- yarn.lock
This PR does a few things:
- Prefixes FA CSS classes with `neos-` namespace to avoid conflicts
- Disables automatic injection of FA styles into head (as they will not affect the guest frame)
- Loads FA styles together with the rest of 3rd-party vanilla CSS
> TASK: bundle fonte-awesome styles in a safer way

- packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
Fixes #1832 
InspectorEditorEnvelope sets now onEnterKey={handleInspectorApply}, so that now every Editor can use onEnterKey directly to apply the inspector changes.
> TASK: Apply Inspector changes by pressing the enter key in TextFields

- packages/neos-ui/src/Containers/ContentCanvas/index.js
This enables the user to configure the backgroundColor of an `editPreviewMode` via `Settings.yaml`
```
Neos:
Neos:
userInterface:
editPreviewModes:
myPrev:
isEditingMode: false
isPreviewMode: true
title: 'My Preview'
position: 200
width: 500px
backgroundColor: '#000000'
```
closes #1700
> FEATURE: Make EditPreviewMode backgroundColor configurable

- package.json
- packages/react-ui-components/package.json
- yarn.lock
Without updating to 5x version there's this bug with overflow text inputs in Firefox:
> BUGFIX: update react-collapse, fixes overflow of text inputs

- packages/neos-ui-validators/src/index.js
> BUGFIX: do not validate elements if no element configuration exists

- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js
- packages/neos-ui-ckeditor-bindings/src/EditorToolbar/style.css
- packages/react-ui-components/src/SelectBox/style.css
Resolves: #1820 
This PR allows to paste asset and node links into the CKE link editor.
Also it allows node links to have a hash, in that case it would stop resolving them and allow to be editable manually
> TASK: allow to paste asset:// and node:// links and gracefully treat anchor links

- Classes/Fusion/Helper/NodeInfoHelper.php
- packages/neos-ui-guest-frame/src/initializeContentDomNode.js
**What I did**
Added reference to old Node.php, now the elements get a class called "neos-contentelement-shine-through" like in the old one if they are not matching with the current dimension.
Added a reference in NodeInfoHelper.php -> renderNode() and created a const in initializeContentDomeNode.js -> called: matchesCurrentDimensions.
You need to take a look at the html object of your UI, if the dimension shines trough the css-class is added.
solves #1715
> TASK: Legacy class for content shining through

- packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
- packages/neos-ui-extensibility/src/shims/neosProjectPackages/neos-ui-views/index.js
- packages/neos-ui-views/package.json
- packages/neos-ui-views/src/index.js
- packages/neos-ui/src/apiExposureMap.js
- packages/neos-ui/src/index.js
**What I did**
I exposed neos-ui-views so the dataLoader can be used in custom DataSource Views
I added a shim in neos-ui-extensibility, a webpack alias and added that to the apiExposureMap.js.
> FEATURE: Expose neos-ui-views

- packages/neos-ui/src/Sagas/Changes/index.js
In order to make behavior slightly more predictable and
avoid race conditions on the server the changes are now
sent in order and with only one request at a time.
We collect changes from change actions until one of the
following happens:
* we have taken 3 actions (to avoid too many unpersisted changes)
* 2 seconds have passed
If at that point another request is still running, the wait is
prolonged until that request has finished at which point the
new batch of changes will be persisted.
> TASK: Improve "Changes" saga

- packages/neos-ui/src/Containers/Drawer/index.js
- packages/neos-ui/src/Containers/Drawer/style.css
The version number needs to be sticky at the bottom of the drawer.
So we use now flexbox to align the menu item groups and the version number.
If the List of menu items become to long we now get a scrollbar.
Fixes: #1890
> BUGFIX: Use flexbox to align the drawer menu

- Classes/Fusion/Helper/NodeInfoHelper.php
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/react-ui-components/src/Icon/icon.js
- packages/react-ui-components/src/Icon/style.css
- packages/react-ui-components/src/Tree/node.css
- packages/react-ui-components/src/Tree/node.js
This change will add some icons on top of the nodetype icon in the tree to visualize a `hidden` and `hiddenBefore/After` status.
Resolves #1500 
Resolves #1895
> TASK: Render custom icon component to visualize node status

- packages/neos-ui/src/Containers/EditModePanel/Panel/index.js
- packages/neos-ui/src/Containers/EditModePanel/style.css
The buttons in the edit pane always overrides the margin-right.
So we now define a lastItem class that only resets the margin-right
for the last button in the edit pane.
Fixes: #1906
> BUGFIX: Take care that the button margin is visible

- package.json
- yarn.lock
Fixes the bug mentioned in https://github.com/neos/neos-ui/pull/1896
**What I did**
removed `flow-mono-cli` from dependencies
`yarn remove flow-mono-cli`
use an older node version (6 for example) together with a globally installed yarn (which is the recommend way since a while) and try to install the node_modules.
/cc @grebaldi @johannessteu @beheist
> TASK: Remove not needed flow-mono-cli

- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui-editors/src/EditorEnvelope/style.css
- packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeItem.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/style.css
- packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorEditorEnvelope/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js
- packages/react-ui-components/src/Tooltip/style.css
- packages/react-ui-components/src/Tooltip/tooltip.js
This currently shows a help icon in the NodeCreateionDialog and inspector property if a help definition exists in the yaml file and sets the title of this element to the help message.
Thus means if you hover this item you will see the help message.
closes  #1694
New:
Old:
> FEATURE: Render help message from yaml file

- packages/neos-ui/src/Sagas/Changes/index.js
The previous behavior left a window in which a change could be lost
(up to 1.5sec) due to waiting for the next opportunity to save.
Now pending changes are submitted to the server as soon as the last
save request finished. This should minimize the risk especially
in conjunction with disabling the publish button while chnages
are being persisted.
Fixes: #1933
> BUGFIX: Prevent data loss in change saga

- Classes/Controller/BackendServiceController.php
- Classes/Service/NodePolicyService.php
- Configuration/Routes.Service.yaml
- Resources/Private/Fusion/Backend/Root.fusion
- packages/neos-ui-backend-connector/src/Endpoints/index.js
- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
- packages/neos-ui/src/Sagas/CR/Policies/index.js
- packages/neos-ui/src/Sagas/CR/Policies/index.spec.js
- packages/neos-ui/src/Sagas/UI/ContentTree/index.js
- packages/neos-ui/src/Sagas/UI/PageTree/index.js
- packages/neos-ui/src/manifest.js
- packages/neos-ui/src/manifest.sagas.js
Avoid evaluating policies when fetching node information from
server in order to improve performance of loading/display of nodes.
Policies for Documents are only fetched when the respective node is
selected in the tree. Policies for content nodes are fetched after
the page is loaded in the iframe.
Related: #1579
Fixes: #1646
> FEATURE: Asynchronously load policy information for nodes

- packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js
Currently, an error is thrown when a Nodetype property definition has no label.
This PR prevents this.
> BUGFIX: Dont throw a console.error when a label is not defined

- packages/neos-ui/src/Containers/EditModePanel/Panel/index.js
- webpack.config.js
The slick slider styles should no longer affect sliders within the guest frame
resolves: #1538
> BUGFIX: Move slick vanilla styles to HostOnlyStyles

- packages/neos-ui/src/Sagas/CR/Policies/index.js
Due to the property mapping the request would fail for
removed nodes but we actually don't even need the policies
for those so I just filter them before requesting.
> BUGFIX: Don't try to get policies for removed nodes

- Resources/Private/Fusion/Backend/Root.fusion
The helper needs the full module path to check availability,
interestingly it apparently returns true for wrong paths,
that should be fixed in the future.
> BUGFIX: Use submodule path to check for availability

- Classes/Service/NodePolicyService.php
The filter should make sure that the collection of NodeTypes or
Node properties only contains those that are not allowed in the
end, which means the condition must be reversed to get the right
result.
> BUGFIX: Correctly check for allowed NodeTypes and properties

- packages/neos-ui/src/manifest.js
We cannot use add as that would override policy information or
in general already loaded data. Merging the information results
in working inserts right after adding a node again.
Fixes: #1988
> BUGFIX: Should not overwrite policy information on node add

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/style.css
The border seems a bit out of place IMHO
> Border on inline toolbar

- packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
- packages/neos-ui-ckeditor5-bindings/src/manifest.config.js
- packages/neos-ui-ckeditor5-bindings/src/plugins/inlineMode.js
- packages/neos-ui-ckeditor5-bindings/src/plugins/neosPlaceholder.js
This feature disables creation of paragraphs for span and heading elements. Also it configures [enter] key to produce soft line breaks.
It's also possible to enable this mode with this config:
```
formatting:
paragraph: false
```
Under the hood it works a bit hackishly: it re-maps paragraph model elements to `<span>` tags, and then removes the wrapping span in post-processing. There are other ways to do it, but this one is the most reliable one.
> TASK: support span-like editable mode for CKE5

- package.json
- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
- yarn.lock
I added the [react-markdown](https://github.com/rexxars/react-markdown) library to convert Markdown into a React-Component and wrapped the `helpMessage` output with this component.
closes #1944
> TASK: Render markdown in help messages

- packages/neos-ui-ckeditor-bindings/src/guestFrameApi.js
- packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
Before this change, we had typing throttled to 1.5s, so if the editor would close or reload the page within that interval, the change would get lost.
This change replaces throttle+debounce with just debounce + maxWait to 5s to make sure that editors who type really fast without stopping would still have their content saved periodically.
The potential problem with this change is that if editor types one keystroke per 350ms for a long time, and if the backend for some reason would take longer than 350ms to process that change, a lot of changes would line up in the changes saga (but thanks to @kitsunet's change server would still not get spammed with requests, so that should be fine).
>  BUGFIX: disable throttle on typing

- packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
- packages/neos-ui-extensibility/src/shims/vendor/ckeditor5-exports/index.js
- packages/neos-ui/src/apiExposureMap.js
We can't just install CKE5 in parallel inside the plugin, as in that case `instaceof` checks inside CKE5 would stop working, so we need to expose the key CKE5 model classes.
Some less important utils can still be installed from npm, should be safe to duplicate them.
Usage example:
```
import {Command, Plugin, UpcastConverters, DowncastConverters, ModelRange as Range, ModelPosition as Position} from 'ckeditor5-exports';
```
> TASK: export CKE5 in extensibility package

- packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js
**What I did**
Declared the `defaultProps`  of the `MultiSelectBox` as static properties
with style
Declare a nodeype property e.g.
```
test:
type: array
ui:
label: 'test'
inspector:
group: 'general'
editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
editorOptions:
values:
test1:
label: 'test1'
test2:
label: 'test2'
test3:
label: 'test3'
test4:
label: 'test4'
```
and try to choose an element in the select box
closes #2042
> BUGFIX: Declare defaultProps as static

- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
`.setState` on `PureComponent` doesn't force a component update in case if some deep configuration value has changed.
This causes a bug, that the dependant(i.e. client-processed) properties don't get calculated correctly.
> BUGFIX: force re-render correcly when processing configuration

- Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
- packages/neos-ui-backend-connector/src/FlowQuery/Operations/NeosUiDefaultNodes/index.js
- packages/neos-ui/src/Sagas/CR/NodeOperations/reloadState.js
Fixes: #2000
It's necessary to have clipboard node in store in order to be able to paste it in different dimensions.
> BUGFIX: fix copy&pasting nodes across dimensions

- Resources/Private/Fusion/Backend/Root.fusion
**What I did**
Using [neos-multisitehelper](http://github.com/flownative/neos-multisitehelper), I can limit users to certain sites in a single Neos installation. This then leads to a problem in the backend.
The left-side menu contains the "Content" entry. This header, by default, links to the first available site in the installation. If, however, the current user does not have access to this first site, an error is thrown.
This pull request fixes this issue.
Use the `sitesForMenu` variable instead of a FlowQuery operation.
1. Create a multisite setup (using [neos-multisitehelper](http://github.com/flownative/neos-multisitehelper) and [neos-multisitekickstarter](http://github.com/flownative/neos-multisitekickstarter)).
2. Create two sites.
3. Assign …
> BUGFIX: Fix content menu item link in backend

- packages/neos-ui-extensibility/src/registry/SynchronousRegistry.js
- packages/neos-ui/src/Containers/SecondaryToolbar/index.js
Fixes: #2057 #1898
We shouldn't be so strict about reading from registries (writing is a different topic), especially since we don't have a proper type system at our disposal.
That causes all sort of runtime exceptions that hit the editors on the head (surrounding them with error boundaries is another topic).
We, the developers would still see that something is wrong just by looking at the console output.
> BUGFIX: replace some exceptions with console errors to make UI feel more robust

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
Way to reproduce:
- after the UI has freshly loaded, select in the content tree a node that is at the bottom of the page
- no scrolling occurs
- if you select some other node then scrolling would start working
> BUGFIX: scrollIntoView not fired on first render

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/style.css
- packages/neos-ui/src/Sagas/CR/ContentDimensions/index.js
- packages/neos-ui/src/manifest.sagas.js
If user switched dimensions through inline navigation (and not dimensions selector), then switching dimensions with creating new nodes would be broken.
**Steps to reproduce**
1. Go to front page of the demo site, switch to Latvian via dimensions selector
2. Switch back to English via the site's language menu
3. Go to some other page, e.g. Downloads and switch language to Latvian via dimensions selector, click "Create and copy" (or whatever it's called)
That would end up with a failing ajax request + console errors, and nothing happening.
Also this PR fixes another problem:
1. Navigate to a different dimension via the site's language menu
2. State is not reloaded, e.g. tree doesn't have all needed nodes
> BUGFIX: fix various edgecases regarding switching dimensions

- packages/neos-ui-editors/src/EditorEnvelope/index.js
fixes: #1947
**What I did**
see title
Used i18nRegistry to translate given help message
Create a property with
ui:
help:
message: 'i18n'
Neos should show the translated value in the tool tip.
> TASK: Make help tooltips translatable

- packages/react-ui-components/src/Icon/mapper.js
Fixes: #1994 
**What I did**
Removed the custom className from the icon in the mapper method.
.split(' ')[0]
Create a node with the icon 'fas fa-tag super-important'
> BUGFIX: Make custom icon classNames possible again

- Classes/Fusion/Helper/NodeInfoHelper.php
We should check if a Node actually has a parent, which might
not be the case for a multitude of reasons, but we should catch
that case and not error out if the parentNode was NULL.
> BUGFIX: Make sure tree search/filter behaves gracefully

- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui-editors/src/EditorEnvelope/style.css
fixes: #1948
**What I did**
I added a helper Method which checks if the thumbnail is on a resource path and in case resolves it.
In addition I added a class to the image with style max-width: 100%
Create a property with a help thumbnail.
Absolute URI and resource path should work now
> TASK: Render resource paths images in help tooltips

- Makefile
The command ```make lint-editorconfig``` throws an error:
```
make: editorconfig-checker: No such file or directory
make: *** [lint-editorconfig] Error 1
```
Had this problem already in the past with lerna. So I choose the same approach to fix it.
Fixes: #2096
> BUGFIX: Execute make lint-editorconfig also on mac

- Classes/Fusion/ExceptionHandler/PageExceptionHandler.php
- Resources/Private/Fusion/Prototypes/Page.fusion
- Resources/Private/Fusion/Root.fusion
- Resources/Private/Templates/Error/ErrorMessage.html
The old backend would show up inside the client frame in case a
rendering exception happened. The reason is the PageHandler in Neos
which just renders a (legacy) backend around the error message because
that was the only way the legacy backend could still work in case
of an error. This leads to the backend in backend problem and can be
avoided by a custom error handler for the new UI that replaces the
old one.
> BUGFIX: Prevent backend inside of client frame in error case

- package.json
- packages/react-ui-components/package.json
- yarn.lock
Now using version 3.3.2 for possible typescript usage.
The issue #2102 needs the TS compatible version of @friendsofreactjs/react-css-themr. So this updates to the latest version.
Resolves: #2103
> TASK: Update @friendsofreactjs/react-css-themr

- packages/build-essentials/src/styles/styleConstants.js
- packages/neos-ui/src/Containers/LeftSideBar/style.css
- packages/neos-ui/src/Containers/SecondaryToolbar/style.css
- packages/react-ui-components/src/ToggablePanel/style.css
- packages/react-ui-components/src/ToggablePanel/toggablePanel.js
**What I did**
Increases the transition speed of a couple animations to make the UI feel more responsive and avoid waiting on animations to finish.
Toggle collapsed state of inspector panels, menu groups and content tree.
> TASK: Adjust animation speed to make UI feel more responsive

- Classes/Fusion/Helper/NodeInfoHelper.php
Fixes: #1995
This checks NodeTreePrivilege synchronously, as it would look strange, if the UI first loads the nodes, and then they disappear once the policy is loaded...
> BUGFIX: enable NodeTreePrivilege checking

- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
Fixes: #1934
See the issue for description.
Alternative solution would be to stop using event delegation of click event, and attach it on actual editable dom nodes, but then we'd need to bind and unbind those events all the time, which is a mess.
> BUGFIX: use mousedown event instead of click when focusing a node inline

- packages/neos-ui-redux-store/src/UI/Drawer/index.js
- packages/neos-ui-redux-store/src/UI/Drawer/index.spec.js
- packages/neos-ui/src/Containers/Drawer/MenuItemGroup/index.js
- packages/neos-ui/src/Containers/Drawer/index.js
- packages/neos-ui/src/localStorageMiddleware.js
**What I did**
Implemented state handling with local storage persisting for menu group collapsed states.
Check that the collapsed state of the menu groups is kept after re-opening the menu, even after reloading the UI.
> FEATURE: Remember collapsed state of menu groups

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui-guest-frame/src/InlineUI/index.js
If the document node was changed and the old focused element was still in the store (it is a racing condition between set_src and set_context_path actions), the NodeToolbar crashed because it could not find the old elements dimensions.
I added conditions to the InlineUI to check if the focused element is in the GuestframeWindow and also to the NodeToolbar to check if the nodeElement is set. I also updated the forceUpdate- and setState-calls to be cancelled if the component was unmounted during the debounce-delay
> BUGFIX: Prevent NodeToolbar from crashing if focused node not in DOM

- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
For some weird reason FF returns empty composedPath for event which happened in the past and were stored in a closure.
Let's be safe and just use all parents, it's super quick anyways.
> BUGFIX: fix focusing nodes in FF

- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js
Resolves: #1682
**What I did**
Added a property `hidden` to the inspector configuration for dynamically hiding editors in the inspector. See issue #1682.
For example add two properties to a Node Type, e.g.:
```
foo:
type: boolean
defaultValue: true
ui:
label: 'A totally unnecessary property'
inspector:
group: 'image'
image:
type: 'Neos\Media\Domain\Model\ImageInterface'
ui:
label: 'Image'
inspector:
group: 'image'
hidden: 'ClientEval:node.properties.foo ? true : true'
```
The editor for the property image will only be shown if `foo` ist set to `true`:
> FEATURE: Dynamically hide properties in the inspector

- Classes/Domain/Model/Changes/AbstractMove.php
- Classes/Domain/Model/Changes/MoveAfter.php
- Classes/Domain/Model/Changes/MoveBefore.php
- Classes/Domain/Model/Changes/MoveInto.php
Like in https://github.com/neos/neos-ui/pull/2078 / https://github.com/neos/neos-ui/pull/2091 the problem exists in move actions too, but I've never seen it in real life.
**Important**: Before this PR's changes takes effect, the ContentRepository PR https://github.com/neos/neos-development-collection/pull/2161 needs to be merged too.
Without it does not break, but it changes nothing on the current behaviour if there is really a collision.
> BUGFIX: Force re generation of moved node names

- packages/neos-ui-editors/src/Editors/Image/index.js
- packages/neos-ui-editors/src/Library/AssetUpload.js
- packages/neos-ui-editors/src/SecondaryEditors/MediaSelectionScreen/index.js
There were two faulty scenarios:
- from some Image editor, go to media library and pick a .pdf (or other non-image file). A scary exception would be thrown.
- from some Image editor, click upload button, change allowed file extension in file picker to all files, pick pdf file: the spinner would be infinitely loading.
With this change:
- if you go to media library from Image editor, it would only be possible to pick images, and not just any assets.
- if you fool the file picker to picking a wrong filetype, it will be rejected correctly.
> BUGFIX: prevent selecting or uploading wrong image types in Image editor

- Migrations/Code/Version20180907103800.php
- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
This PR provides a core migration from old Aloha NodeTypes.yaml format to the new one, but also allows both formats to exist at the same time.
The old aloha format and the new format are supported at the same time, the new format takes precedence.
> TASK: add legacy aloha format migration and support both formats at the same time

- packages/react-ui-components/src/DateInput/__snapshots__/dateInput.spec.js.snap
- yarn.lock
Tests are currently broken becuase the jest snapshot wasn't updated after latest changes.
> BUGFIX: Add timeConstraints to snapshot 

- Classes/Fusion/Helper/NodeInfoHelper.php
The indexes of an array must be reset after filtering. This caused the result to be casted into object in JS, which broke the tree in effect.
> BUGFIX: reset index after filter when checking for policies

- packages/neos-ui-redux-store/src/UI/Inspector/selectors.js
Transient values were not taken into account for validation, because they were not correctly set.
> BUGFIX: fix propertiesForValidationSelector

- packages/neos-ui-editors/src/EditorEnvelope/index.js
Current:
With this patch applied:
> TASK: Render help message below editor component

- packages/neos-ui-validators/src/Integer/index.js
- packages/neos-ui-validators/src/Integer/index.spec.js
closes #2080
So - the error should be somewhere else, not in the validator itself as the test is running through.
Edit:
There is a paradox test case, can someone explain this behaviour?
Ok found it, tests are running but doesn't think these are tests, tests-runner think's tests should be one level deeper:
```
$ yarn jest -- -w 2 --coverage                                                                                                                                                                                                               
$ NODE_ENV=test jest -w 2 --coverage                                                                                                                                                                                                         
No tests …
```
> BUGFIX: Integer validator with trailing chars

- packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeItem.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/style.css
- packages/react-ui-components/src/Dialog/dialog.js
**What I did**
- Added support for translation
- Moved the help message from the bottom of the dialog to the bottom of the NodeType Groups
- Added support for thumbnails (currently just absolute paths - resource path resolving has to be done inside the neos package)
- Removed the fixed height of the message to improve display of thumbnails
- Moved the help message part from index.js to nodeTypeGroupPanel.js
- Added an additional class to the Dialog component to query select the dialog body
- modified help css
- add help properties to a nodeType in your yaml (message + thumbnail with absolute path)
This fixes: #2086
and partly: #2088
> TASK: Rework Help Message in SelectNodeType Dialog

- packages/react-ui-components/src/Dialog/__snapshots__/dialog.spec.js.snap
- packages/react-ui-components/src/Dialog/dialog.js
and only add theme class if it's not a faulty value - otherwise it will
be undefined.
Maybe there are some other places where this would be good to do.
Should repair master, failed since merge of 6eed65fc771b5f993d30bcb597e3ff80301659ba
> BUGFIX: Set css-class to snapshot

- tslint.json
**What I did**
I configured TSLint so that it prohibits `console.x` and `debugger`.
I set the corresponding setting to true:
* `no-console: true`
* `no-debugger: true`
Use `console.log` in `.ts(x)` file and run `make lint`. It should fail with an error msg.
It should _not_ fail when running `make build-watch`. So you can still use `console` and `debugger` while developing.
> TASK: tslint now prohibits console.x and debugger

- packages/utils-helpers/src/stripTags.js
- packages/utils-helpers/src/stripTags.spec.js
- packages/utils-helpers/src/stripTags.ts
This converts the `stripTags` helper to Typescript and adds testcases.
> TASK: Convert stripTags to Typescript

- packages/utils-helpers/src/isEmail.ts
This adds a return type to the `isEmail` function. 
As we are using Typescript there it should be done is as many places as possible to give us the whole power of TS.
> TAKS: Add return type to is email

- packages/utils-helpers/src/isEmail.spec.js
This adds some test-cases for the `isEmail` function.
I needed to wrap the function call into in anonymous function, see: https://stackoverflow.com/questions/46042613/how-to-test-type-of-thrown-exception-in-jest
> TASK: Add some test cases for `isEmail`

- Makefile
The original Makefile did not work for me, since webpack and cross-env
could not be found.
This change fixes it, calling those binaries like it is done for lerna.
> BUGFIX: Make make work on macOS

- packages/neos-ui-ckeditor5-bindings/src/plugins/neosPlaceholder.vanilla-css
Ensures placeholder text for inline editable properties are aligned similar to inserted text.
Fixes #2166
> BUGFIX: Inline editable placeholder text misaligned

- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js
- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.spec.js
**What I did**
If an abstract NodeType was allowed to be created as to another nodes constraints, but disallowed due to other policies (mentioned below), the "create node" buttons weren't deactivated.
Add a check to `NodeTypesRegistry`s `getAllowedChildNodeTypes` and `getAllowedGrandChildNodeTypes` which checks if the NodeType is valid (i.e. not abstract) by looking it up in its own collection (the registry).
* `Node` with `NodeMixin`
* Document `ParentNode` with `constraints.nodetypes: [NodeMixin: true]`
* `CreateNodePrivilege` with `matcher: createdNodeIsOfType('Node')`, abstaining or denying
Now try to create a child node under the `ParentNode`. `Node` is theoretically allowed as child node due to being a NodeMixin, but blocked for the user due to …
> BUGFIX: getAllowed(Grand)ChildNodeTypes won't return abstract NodeTypes anymore

- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeItem.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/style.css
In the SelectNodeType dialog (that comes up when adding a document or content node), the icons in the list were not properly aligned. This PR fixes it, see screenshots.
Before:
After:
> Add fixed-width alignment for icons in SelectNodeType dialog

- package.json
- packages/build-essentials/package.json
- packages/neos-ui/src/Containers/Modals/index.js
The modals are now automatically loaded from the registry, which allows to create custom modals from 3rd-party plugins.
Can be used like this: https://github.com/Flowpack/restrict-creation/blob/master/Resources/Private/RestrictCreation/src/manifest.js#L17
>  TASK: load all modals from the registry automatically

- packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/LinkButton.js
- packages/neos-ui-editors/src/Library/LinkInput.js
How to test: go to the advanced options palette of the CKE5 link editor and try to toggle options.
> BUGFIX: fix options pallete of the LinkEditor

- Classes/Controller/BackendController.php
- Classes/Domain/Service/StyleAndJavascriptInclusionService.php
- Configuration/Settings.yaml
- Resources/Private/Fusion/Backend/Root.fusion
- Resources/Private/Templates/Backend/Index.html
- Resources/Private/Templates/Backend/Partials/SplashScreen.html
- packages/neos-ui/src/index.js
**What I did**
While developing I noticed the rather stale loading experience of the Neos frontend.
I built a pretty simple animation for the Neos logo.
Also I noticed, that the user spends most of the time in front of a white screen while downloading, parsing and initially running the rather huge script files (I know, I am running the dev build, not production, but still..).
So I thought it would be nice to see this loading splash screen even before the scripts are being loaded.
The splash screen is a partial that is rendered inside the `app-container` wich will be overridden by React once the UI is ready to be rendered.
It is configurable in `Settings.yaml` of the Package:
```yaml
Neos:
Neos:
Ui:
splashScreen:
partial: 'SplashPartial'
```
Added a splash screen to …
> WIP: FEATURE: add a splash-like loading experience & allow customization

- packages/neos-ui-sagas/src/UI/PageTree/index.js
Solves #2130: page tree is not properly reset after clearing filter or search.
> BUGFIX: Properly reload the page tree if filter or search is reset #2130

- Configuration/Settings.yaml
We can't defer those, since currently our extensibility layer relies on JS code being loaded in the right order
> BUGFIX: remove defer from core JS assets

- Classes/Service/NodePolicyService.php
The $parentPrivilege is just class name here, so
is_a always returns false. Setting the third parameter
to true also accepts class names as object.
> BUGFIX: Fix priviege class inheritance check

- packages/neos-ui-editors/src/index.js
- packages/neos-ui-editors/src/manifest.js
- packages/neos-ui/src/apiExposureMap.js
Makes sure the editors and their parts are exported to be used by
UI extensions.
Fixes: #2250
> BUGFIX: Correctly export all editors for extensibility

- packages/neos-ui-redux-store/src/CR/Nodes/index.js
- packages/neos-ui-redux-store/src/UI/SelectNodeTypeModal/index.js
- packages/neos-ui-sagas/src/CR/NodeOperations/addNode.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
This feature adds two more (optional) arguments to `commenceNodeCreation` action creator, which allow to specify the desired insertion mode and allow to skip the step of nodetype selection completely.
E.g. `commenceNodeCreation(contextPath, fusionPath, 'into', 'Vendor:News');`.
Usage example: https://github.com/psmb/Psmb.FlatNav/pull/13/commits/0c869ba05cd783a9396891f694577178c1eec539
> FEATURE: make nodeCreationWorkflow more extensible

- Classes/Domain/Model/Changes/AbstractMove.php
- Classes/Domain/Model/Changes/MoveAfter.php
- Classes/Domain/Model/Changes/MoveBefore.php
- Classes/Domain/Model/Changes/MoveInto.php
- yarn.lock
Partially rolling back changes from #2098 because of issues like #2258, neos/neos-development-collection#2284 and neos/neos-development-collection#2282.
> BUGFIX: Don't re-generate nodeNames on move if not needed.

- packages/react-ui-components/src/DateInput/__snapshots__/dateInput.spec.js.snap
- packages/react-ui-components/src/DateInput/dateInput.js
- packages/react-ui-components/src/DateInput/dateInput.spec.js
- packages/react-ui-components/src/DateInput/index.story.js
**What I did**
* Add utc prop to react-datetime if dateOnly is set
* Today button will use start of day in UTC if dateOnly is set
* Open storybook and test the DateInput stories
* Run tests
Relates #2147
> BUGFIX: Use UTC date for dateOnly DateInput

- packages/neos-ui-redux-store/src/CR/Nodes/selectors.js
**What I did**
Adding childNodes to a node which is not editable is allowed. So the UI has to respect that.
Removed the check for `policy.canEdit`.
Add a child node to a node which is not editable (for you).
> BUGFIX: Remove canEdit from allowedChildTypesSelector

- packages/neos-ui-sagas/src/Publish/index.js
On publishing, generate preview link and update ContentCanvas by setting new preview url. Before, the preview button has not been updates, see: https://github.com/neos/neos-ui/issues/2173
I am not sure if this is the correct way to do it and I am open for your feedback.
> BUGFIX: Update preview link on node creation and publishing #2173

- Classes/Domain/Model/Changes/Property.php
If a property with `reloadIfChanged` is used on document level an error occured when the ui tried out of band rendering on the root page in a non-default dimension. The configuration is strange but can occur easily via Mixins and Neos should behave better.
The reason for the error was that the ui checks the type of the parentNode as beeing a `ContentCollection` but did not validate wether the current node is `Content`. That lead to trying accessing the parentNode of the site-node which fails for the site-document in no default dimension because '/sites'  does not exist in all dimensions.
The solution is tho check wether the node is of type `Content` before checking the type of the parentNode beeing a `ContentCollection`.
> BUGFIX: Limit out of band reloading to content-nodetypes

- packages/react-ui-components/.editorconfig
The components have their own `.ediorconfig` which sets everything to 4
spaces by default but the `package.json` uses two spaces indentation.
The fallback to `[*]` overwrites the global one two space indentation
for `*.json`-files.
**What I did**
Added the `json`-glob to the `.editorconfig` for the `react-ui-components`-package.
With style.
Setup your editor to read the `.editorconfig` correctly and try to indent something in the `package.json` from the `react-ui-components`-package.
> TASK: Use correct json indentation in `react-ui-components`

- Configuration/Settings.yaml
This PR marks CKeditor 4 integration as deprecated and makes CKeditor 5 the default editor.
You can still use CKeditor 4, but it will get removed with the next major release, perhaps in Neos 5.0.
In order to switch back to CKE4, add this to Settings.yaml:
```
Neos:
Neos:
Ui:
defaultInlineEditor: 'ckeditor'
```
Known issues:
- custom CKE4 plugins won't work in CKE5, please get in touch with us for help how to rewrite then for CKE5
- https://github.com/neos/neos-ui/issues/2288
> !!! TASK: make CKE5 the default editor

- Classes/Service/NodePolicyService.php
The UI expects the ``disallowedNodeTypes`` in policy information
as a simple array of strings. Due to the way `array_map` works in
PHP the keys of the array could be strings which would result in
a JSON object representation, breaking the UI.
> BUGFIX: Disallowed NodeTypes should be delivered as array

- packages/neos-ui-validators/src/index.ts
Example of faulty configuration:
```
validation:
Neos.Neos/Validation/IntegerValidator: null
```
> BUGFIX: don't break on validators with null configuration

- packages/react-ui-components/src/Icon/style.css
The image editor icon was too small and the css class for the bigger icon (5x) did not work.
This patch extracts the font-size from the combined font style and make it work.
Fixes: #2313
> Bugfix: Icon overlay in Image editor is too small

- packages/react-ui-components/src/Icon/style.css
Has been already fixed in master but did not get the point with the branches so here the change for 2.x.
related: https://github.com/neos/neos-ui/pull/2331
fixes: #2331
> BUGFIX: Icon overlay in Image editor is too small for 2.x

- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui-editors/src/Editors/Boolean/index.js
- packages/neos-ui-editors/src/Editors/Boolean/style.css
- packages/neos-ui-editors/src/Editors/CodeMirror/index.js
- packages/neos-ui-editors/src/Editors/CodeMirror/style.css
**What I did**
This PR adds help icons that toggle the help messages to `BooleanEditor` and `CodeMirrorEditor` as outlined in #2249 
The `renderHelpIcon` method of the `EditorEnvelope` is passed to the components.
This way inconsistencies between components is prevented since `EditorEnvelope` is always in charge of rendering the help icon.
Create a node type that uses a boolean property and a help message.
The following was used by me during development:
```yaml
'J6s.NeosPlayground:Test':
superTypes:
'Neos.Neos:Content': true
ui:
label: 'J6s.NeosPlayground:Test'
inspector:
groups:
test:
label: 'Testing'
icon: 'icon-question'
properties:
string:
type: string
ui:
label: String
inspector:
group: test
help:
message: string help
checkbox:
type: boolean
ui: …
```
> FEATURE: Render help icon in BooleanEditor and CodeMirrorEditor

- packages/neos-ui/src/Containers/SecondaryToolbar/FullScreenButton/index.js
- packages/neos-ui/src/Containers/SecondaryToolbar/KeyboardShortcutButton/index.js
- packages/neos-ui/src/Containers/SecondaryToolbar/PreviewButton/index.js
There are no title attributes on the secondary toolbar buttons so no description on hover.
> TASK: Add title attributes to secondarytoolbar components

- Classes/Domain/Model/Changes/Property.php
- Classes/Service/NodePolicyService.php
- Classes/Service/NodePropertyValidationService.php
- Tests/Functional/Service/NodePropertyValidationServiceTest.php
This change resolves the according flow validator to a configured
property validator. If it exists, it validates the result.
This is non braking, as it returns true, if the validator is not
found so custom validators are not affected.
Resolves: #2349, #2348
> BUGFIX: Use backend validators if available

- packages/neos-ui/src/apiExposureMap.js
In the bugfix PR #2257 it was planned to expose all editors to the
extensibility layer as was planned originally. Unfortunately the
import path for components was not changed resulting in a totally
broken state at the moment. This change tries to rectify the situation
by adjusting the path. It has been tried in a project that uses the
``LinkOption`` component in a custom editor, which would fail without
this change.
> BUGFIX: Actually import and expose all editors for extensibility

- packages/neos-ui-guest-frame/src/style.css
- packages/neos-ui/src/Containers/ContentCanvas/style.css
- packages/neos-ui/src/Containers/style.css
Styled the scrollbars in a slim, unobtrusive way. Hard to capture in a screenshot, but makes everything look a bit more elegant.
Tried the primary blue before, and while it certainly looked cool, it made them to catchy visually.
On the left: the small bar is part of the scrollbar of the content canvas
On the right: scrollbar of the inspector panel
> TASK: Style scrollbars

- Configuration/Settings.yaml
- packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
Remove legacy UI switch, closes #2321 as it is no longer needed.
> TASK: Remove legacy UI switch

- Classes/Controller/BackendController.php
**What I did**
Remove the error resulting from invalid node paths, closes #2318.
Ignore validation in BackendController->indexAction() for $node, as $node is not necessarily a valid object.
Open the backend with invalid node paths. You should be redirect to the next editable node or the site root node.
> BUGFIX: Opening the Neos Backend with invalid node paths

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Show the blue planned icon only if hiddenBeforeDateTime is in the future, closes #2280.
> BUGFIX: Show the blue planned icon only if hiddenBeforeDateTime is in the future

- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
**What I did**
Disable editing in preview mode by checking current editing mode in guest frame initialization, closes #2316. 
Check current editing mode for "isEditingMode" in guest frame initialization. Hope this is the right place to do this.
Click on Edit / Preview and toggle the modes. You should not be able to inline edit your document in preview modes.
> BUGFIX: Editing in preview mode

- Classes/Controller/BackendServiceController.php
- Configuration/Routes.Service.yaml
- Resources/Private/Fusion/Backend/Root.fusion
- packages/neos-ts-interfaces/src/index.ts
- packages/neos-ui-backend-connector/src/Endpoints/index.ts
- packages/neos-ui-sagas/src/CR/Policies/index.js
Since #2164 got blocked, I extract the logic for loading node variant information into this PR, so it would be possible to experiment with node variants selector in a separate package.
I refactor `getPolicyInformationAction` into `getLazyNodeDataAction`, a place where we'd be able to fetch all node information, that is expensive to calculate and load, I'm sure it'd be useful in the future.
> TASK: lazily expose node variants information

- packages/neos-ui-editors/src/Editors/Image/index.js
Just close the secondary inspector if you select the same image twice, closes #2367.
> BUGFIX: Same image cannot be selected twice

- package.json
- yarn.lock
**What I did**
Prevent hotkeys from firing while editing a content editable or other editable element which is in the structure of a shadow dom.
Updated Mousetrap from 1.6.1 to 1.6.3 which contains the fix.
> BUGFIX: Stop hotkeys when editing shadow dom editables

- packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.ts
Feature switches for formating options del / u were not converted to their new names.
> BUGFIX: Add missing legacy formatting options

- packages/react-ui-components/src/Frame/frame.tsx
If we passed the original event to the constructor of MouseEvent, then this click event would be dispatched twice. It's enough to just set `iframeTarget`.
The bug that it sometimes caused was that if you click "+" icon from inline the add node dialog would get closed immediately.
> BUGFIX: fix dispatching of click events to host in Frame

- Migrations/Code/Version20180907103800.php
- Migrations/Code/Version20190319094900.php
Migrates `u => underline` and `del => strikethrough`
> TASK: Add a core migration for legacy RTE formatting options

- packages/neos-ui-editors/src/Editors/TextArea/index.js
This also needed some refactoring of the component
to a class to support the injection of the i18nRegistry.
This will also only work when https://github.com/neos/neos-development-collection/pull/2404 is merged.
Have https://github.com/neos/neos-development-collection/pull/2404 applied and use i18n in the placeholder for a textareaeditor like for the meta description of the Neos.Seo package.
> BUGFIX: Translate textareaeditor placeholder

- packages/react-ui-components/src/Dialog/style.css
- packages/react-ui-components/src/SelectBox/style.css
This PR continues the change from https://github.com/neos/neos-ui/pull/2221
After discussing the issue with some UI people we now define a viewport driven height for the drop down. The content can now also fly out.
If you configure a create dialog with a select box. The select box options are cutted and you need to find out that you are able to scroll down.
example:
```
'Neos.Neos:Document':
ui:
group: 'general'
creationDialog:
elements:
title:
type: string
ui:
label: i18n
editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
validation:
'Neos.Neos/Validation/NotEmptyValidator': []
country:
type: string
ui:
label: 'Country'
editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
editorOptions:
values:
italy:
label: 'Italy'
group: 'Southern Europe'
austria:
label: 'Austria'
group: 'Central …
```
> Makes the select box content fly out

- packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
The recently introduced Feature https://github.com/neos/neos-ui/pull/2223/files led to irritations on editors side. Let's remove this and someday replace it with other optimizations like: https://github.com/neos/guild-ux/issues/10
> TASK: Rollback the FEATURE: Skip 'new element' dialog if there is only one

- packages/neos-ui-backend-connector/src/Endpoints/index.ts
The node-frontend-uri is fetched from a html response and contains tabs and newlines, which at least on macos leads to visual issues if it's directly used as title attribute.
> TASK: Trim node-frontend-uri

- packages/neos-ui-editors/src/Editors/Image/index.js
In the media browser `ImageVariant`s are hidden, so we won't show them here either (but the original `Image`).
This may have a side effect on custom `AssetVariant`s. They will be turned into their original asset counterpart too. But since it is just for the `MediaDetailsScreen`, I think this won't be an issue for nearly everyone.
> BUGFIX: MediaDetailsScreen shows original asset

- packages/neos-ui-redux-store/src/index.ts
Currently the combineReducers function in `neos-ui-redux-store` 
will reset the structure of the global state after each action.
With this change extensions to the ui can store
their own values in `plugins.myExtension.myValue`
without it getting lost after any action.
**What I did**
Add a separate `plugins` reducer that just returns itself without
checking or changing anything.
The naming can be changed of course and it will need documentation.
Add another reducer in your extensions manifest which writes a value that does not exist yet inside the `plugins` namespace.
Trigger any action in the Neos backend and check if the value is still there.
> FEATURE: Allow redux store extensibility

- package.json
- yarn.lock
We actually use it as wrapper to be able to use fetch also in IE 11 and other older browsers.
Resolves: #2417
> TASK: Updates whatwg-fetch to version 3.0

- packages/react-ui-components/src/Tabs/tabs.tsx
Keeps API compatibility with previous 2.x and 3.x versions of the UI.
> BUGFIX: Make tabs work without setting ids

- packages/react-ui-components/src/Dialog/style.css
- packages/react-ui-components/src/SelectBox/style.css
This reverts commit d52b7ffc93f020f7f01343d2110e657ad7238409.
In the Pull Request https://github.com/neos/neos-ui/pull/2398 we changed the handling of the select box. So that the content of the select box could fly out of the create dialog. This also leads the issue #2429
Because this is a critical issue, we revert the PR and search for another solution later on.
Fixes: #2429
> Revert "Makes the select box content fly out"

- packages/react-ui-components/src/IconButton/iconButton.tsx
Added `disabled` attribute to `IconButton` component. Fixes: https://github.com/neos/neos-ui/issues/2437
> BUGFIX: fix disabled state on IconButton

- Tests/IntegrationTests/e2e.sh
The end to end test fail on master because the prune command can not be executed without
a defined site node.
> BUGFIX: prune all sites before importing test site

- README.md
The `neos/neos-ui-compiled` is a transitive dependency of `neos/ui`. As such,
it does not need to be required explicitly. This change removes it from the
installation instructions, to simplify things.
> TASK: Remove neos/neos-ui-compiled from instructions

- Classes/Fusion/Helper/ApiHelper.php
- Configuration/Settings.yaml
For now only used for `contentDimensions.allowedPresets`.
It is probably needed in other places too.
This fixes a problem when the backend outputs an empty array and the frontend expects it to be an object. This is due to PHP arrays being converted by `json_encode()` to JS objects when they are associative and to arrays when not. Empty arrays are interpreted as non-associative (unless `JSON_FORCE_OBJECT` is used).
In many cases we don't want the whole array/object which gets json_encoded to be forced to an object, so we must catch this edge case sooner.
> BUGFIX: fix JSON encoding of empty `allowedPresets`

- packages/neos-ui/src/Containers/LeftSideBar/index.js
- packages/neos-ui/src/Containers/LeftSideBar/style.css
This divider is no longer needed and adds a weird margin
Before:
After:
> TASK: remove <hr> divider between the trees

- Classes/Domain/Model/Changes/Property.php
It can happen that validators does not have additional configuration
like a maximum or minimum.
The exception is kind of eval that you get for the label validator. So we should check this here and prevent the hard exception.
Fixes: #2452
> BUGFIX: Check for validators w/o configuration

- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
When a preview mode was selected, the guest frame initialization returned too early which resulted in guest frame reloading indefinitely.
Fixes: #2458
**What I did**
Moves the code introduced by #2373 to after the document meta data is initialized.
> BUGFIX: Fix preview mode

- packages/neos-ui-editors/src/Editors/AssetEditor/index.js
**What I did**
Fixed the bug that did not allow to add additional assets to asset lists, once created.
Use getValues() instead of directly accessing this.props.value, as then the mapping of asset identifiers is missing.
Add a node with an asset list (array of assets) and add some files. Apply your changes and reload the page. Then select the node again and add more assets – it now works. Before, a JavaScript error was thrown and the Media Browser loaded the asset detail view.
> BUGFIX: Adding assets in asset lists not working

- packages/neos-ui/src/manifest.js
The ui uses since ck editor 5 a wrapping element to
detect the element that should be created in the canvas.
This element was always a div and that does not work for
tables for instance.
Fixes: #2365
> BUGFIX: Change element type of wrapper

- packages/react-ui-components/src/MultiSelectBox_ListPreviewSortable_DraggableListPreviewElement/multiSelectBox_ListPreviewSortable_DraggableListPreviewElement.js
Thanks to @maya-shines update of FontAwesome, we can now use the proper "grip lines" icon for the dragging bars, see screenshots:
Before:
After:
> TASK: Change icon to actual "grip lines" icon

- Classes/Domain/Service/ConfigurationRenderingService.php
- Classes/Domain/Service/StyleAndJavascriptInclusionService.php
- Configuration/Settings.yaml
The neos master registers `q` as a static function which is not compatible with later versions of neos where `q` is a magic name. Since some of the services in the ui rely on flowQuery and use a custom defaultConfiguration this causes trouble when running on latest master.
As backwards compatible solution this change includes the eel default context from `Neos.Fusion.defaultContext` and merge those with `Neos.Neos.Ui.configurationDefaultEelContext` before evaluating the expressions.
This also allows to remove the default Eel helpers from the configuration and only register the
additional helpers of the ui itself needs.
This is related to: https://github.com/neos/flow-development-collection/pull/1580
> BUGFIX: Fix missing q helper on latest master in backend

- packages/neos-ui-guest-frame/src/style.css
The global `td` style is not resticted to any subject within the guest frame. Moreover it affects the styles of users.
> Restrict style for td's in guest frame to CKE content

- Classes/View/BackendFusionView.php
The `@package` placeholder gets replaced by the package name, so you are able to add your own Fusion code for Neos UI backend in your own packages in path `/Private/Fusion/Backend/`.
> FEATURE: Allow adding and overriding fusion code for Neos UI backend in all packages

- packages/neos-ui-editors/src/Library/AssetUpload.js
The asset list throws an error when you change the ordering
of asset nodes. This commit disables the preview mode
and so we don`t have the error anymore.
Fixes: #2491
> BUGFIX: Disable preview mode in assetlist dropzone

- packages/neos-ui/src/Containers/Modals/KeyboardShortcutModal/index.js
- packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js
- packages/neos-ui/src/Containers/Modals/ReloginDialog/style.css
- packages/react-ui-components/src/Dialog/__snapshots__/dialog.spec.tsx.snap
- packages/react-ui-components/src/Dialog/dialog.spec.tsx
- packages/react-ui-components/src/Dialog/dialog.tsx
Former behavior:
When the backend session expires, the relogin dialog forces the user to login again.
This relogin dialog has an "x"-Button to close it, but the button does nothing.
New behavior:
The relogin dialog still opens, but now no longer has the useless "x"-Button:
Sidenote: The dialog.tsx already checks, if the "onRequestClose" is set to something. However, "{emptyFn}" seems to evaluate as not empty, thus rendering the button, despite it not having a function. All I did was to replace the empty function with an empty string.
> TASK: Remove close button for relogin dialog

- package.json
- yarn.lock
This package is used in the nodes for HTML. So if you want to test this you just need to create an HTML node in the demo side and click around :)
> TASK: Upgrade react-codemirror2 to version 6.0.0

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/react-ui-components/src/Frame/frame.tsx
- packages/react-ui-components/src/enhanceWithClickOutside/index.tsx
After creating a new node with an empty renderedContent
payload from RenderContentOutOfBand lead to an issue with
the NodeToolBar.
So it was not possible to create, delete, copy or cut a node.
This patch prevent the clickOutside handling for the NodeToolBar. So we don`t close the dialog by accident.
Fixes: #2489
> BUGFIX: Fix content operations after empty outOfBandRendering

- packages/positional-array-sorter/src/positionalArraySorter.spec.js
- packages/positional-array-sorter/src/positionalArraySorter.ts
**What I did**
Adjust the ordering in the positional-array-sorter to behave more like the implementation in neos/utility-arrays (#2379): `before` and `after` positions may now be weighted, `start` and `after` positions will now be sorted appropriately according to descending weight. Positions like `after start` are no longer matched as `start` key.
Mending the existing implementation did not prove easy as features like weighted `before` or `after` positions were not implemented, so I implemented the function anew.
I developed against the test cases (mostly ported from the php version). As a lot of parts in the UI use this functionality, I can't really tell how to best verify this in the actual UI.
> TASK: rewrite positional array sorter to behave like the php implementation

- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeSearchInput/style.css
Color constant was used wrong and sadly no that did not popped up earlier.
Thanks to @johannessteu for reporting that.
Fixes: #2504
> BUGFIX: Use correct color constant for search input

- packages/build-essentials/src/webpack.config.js
The webpack config in neos-extensibility expects the key „use“ to exist.
This was a regression in a634cf1d and therefore affects 2.4 & 2.5 & 3.4 & 3.5
> BUGFIX: Allow compiling ui plugins again

- .circleci/config.yml
The circle ci tests are running only on branch changes by default.
So when a new tag has been pushed the build chain will not run.
This is now enabled for tags that follow the scheme x.x.x
> TASK: Adds filter to trigger circle ci build

- packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/TableStyles.vanilla-css
This change adapts the css again to the changed
classnames of the ck table plugin.
Resolves: #2518
> BUGFIX: Table icon was to big when selected

- packages/neos-ui-ckeditor5-bindings/package.json
- packages/neos-ui/src/apiExposureMap.js
- yarn.lock
This allows using them in custom packages without getting
errors and warning for duplicate plugins & modules.
The widget plugin allows creating inline widgets for
placeholders, icons etc…
The highlight plugins allows marking text with custom
classes and styles.
The class list is reformatted to see future diffs better
and get a faster overview of available classes.
These additional classes have to be imported like this:
`import {toWidget, Widget, HighlightEditing} from 'ckeditor5-exports';`
> FEATURE: Expose CK widget and highlight plugins

- packages/neos-ui/src/apiExposureMap.js
This is needed to correctly compute selectable widgets
without causing errors when doing different kinds of selections on them like right-clicking.
> TASK: Add positioning helper to ckeditor api exposure

- packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js
This is needed when using e.g. ClientEval, to dynamically evaluate DataSource options.
> BUGFIX: DataSource SelectBoxEditor must re-load data if options change

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CopySelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/CutSelectedNode/index.js
- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui-guest-frame/src/manifest.js
With this change, the Inline UI buttons are configurable; so that they can be extended properly.
> FEATURE: Make Inline UI Buttons configurable by placing them in manifest

- packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/LinkButton.js
- packages/neos-ui-editors/src/Library/LinkInput.js
- packages/neos-ui-editors/src/Library/LinkInputOptions.js
- packages/neos-ui-editors/src/manifest.js
This PR makes LinkInput options extendable by putting them into a registry.
This is useful when you'd want to add some custom options there, e.g.:
Usage example: https://github.com/di-unternehmer/DIU.Neos.Linkeditor.Extension/blob/master/Resources/Private/LinkEditor/src/manifest.js#L24
> FEATURE: make LinkInput options extendable

- packages/neos-ui-editors/src/Library/LinkInputOptions.js
This commit broke the standard editor options of the link input: https://github.com/neos/neos-ui/pull/2534/commits/f8436887e147fdff7d9f5537e3bd529f379aa077
Here's the fix.
> BUGFIX: make LinkInputOptions work after refactoring

- packages/build-essentials/.browserslistrc
- packages/build-essentials/src/postcss.config.js
Use own configuration file for browserlist to prevent error message.
Fixes: #2539
> BUGFIX: Prevent browserlist error on build

- packages/build-essentials/src/styles/styleConstants.js
As `2147483647` is the absolute maximum for `z-index`, it is not possible to have content over the toolbar. But in some special cases, it can be very useful to show some HTML over a toolbar (`<dialog>`, e. g. )
> BUGFIX: Reduce z-index from toolbar by 1

- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Content.Headline.yaml
- packages/neos-ui-ckeditor-bindings/src/createCkEditor.js
- packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
- packages/neos-ui-guest-frame/src/InlineUI/InlineValidationErrors/index.js
- packages/neos-ui-guest-frame/src/InlineUI/InlineValidationErrors/style.css
- packages/neos-ui-guest-frame/src/InlineUI/index.js
- packages/neos-ui-guest-frame/src/dom.js
- packages/neos-ui-guest-frame/src/initializePropertyDomNode.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.spec.js
- packages/neos-ui-redux-store/src/CR/Nodes/index.ts
- packages/neos-ui-redux-store/src/CR/Nodes/selectors.ts
- packages/neos-ui-validators/src/index.ts
- packages/neos-ui/src/manifest.js
Takes existing property validators configuration (`properties.propertyName.validation`) and applies it inline.
If property value is not valid, it will not be persisted until it becomes valid again.
TODO:
> FEATURE: validate inline properties

- Migrations/Code/Version20190319094900.php
Thanks @baschny for reporting!
> BUGFIX: make Aloha config migration handle multiple nodetypes per file correctly

- Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestNodeTypes/composer.json
- Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestSite/composer.json
- Tests/IntegrationTests/TestDistribution/composer.json
This pulls in only `neos/neos-ui` as `^5.0`. That in turn pulls in
`neos/neos` as `^5.0`, which in turn requires it's own dependencies.
That _should_ suffice. If it needs to be more pinned down, we could
add `"neos/neos": "~5.0.0"` as well, to limit it to 5.0.x.
> TASK: Pull in ^5.0 only

- packages/build-essentials/src/styles/styleConstants.js
The loading bar was hidden underneath the primary toolbar.
fixes: #2567
> BUGFIX: Make loading bar visible

- Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php
- Configuration/NodeTypes.yaml
The title set in references editor wasn't used for creating the new content node.
Fixes #1764
> BUGFIX: createNew doesn't set title of new node

- Classes/Fusion/ExceptionHandler/PageExceptionHandler.php
- Resources/Private/Templates/Error/ErrorMessage.html
- packages/neos-ui-guest-frame/src/initializeGuestFrame.js
Prevent infinite reloading if the content inside the guest frame is a Neos exception. This does not occur on initial load, but when switching to a page that throws an exception (for example when
navigating in the node tree).
fixes: #2358
> BUGFIX: Prevent infinite refresh loop

- packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/TableStyles.vanilla-css
**What I did**
Fix bug where text in table cells created using the inline editor is centered in backend. 
This potentially results in different text alignment in front- and backend.
Fixes: #2260
Removed `text-align: center` in backend css.
* Create a text node in the backend
* Add a table using the inline editor
* write some text in a cell
* the text should be left aligned in the front- and backend (if no site specific stylesheet overwrites the alignment).
> BUGFIX: Backend tables center text

- packages/neos-ui-ckeditor5-bindings/src/manifest.richtextToolbar.js
Fixes: #2480 
Steps to reproduce:
You'd see an empty selectbox when no heading is allowed, e.g.:
```
"Neos.TestNodeTypes:Content.Text":
superTypes:
"Neos.Neos:Content": true
ui:
label: Text
icon: icon-file-text
position: 200
inlineEditable: true
properties:
text:
type: string
ui:
inlineEditable: true
inline:
editorOptions:
formatting:
h1: false
h2: false
h3: false
h4: false
h5: false
p: true
```
> BUGFIX: fix empty CKE5 StyleSelect when no headings are allowed

- Classes/Controller/BackendController.php
- Tests/IntegrationTests/TestDistribution/composer.json
This allows the `redirectToAction` to receive invisible nodes to redirect
to.
See #2500 - this is part of a solution
> BUGFIX: Allow redirect to invisible nodes for preview

- Classes/Controller/BackendController.php
This fixes an error with the UI on earlier Neos versions that lack a
constant introduced to fix #2500.
See #2557
> BUGFIX: Avoid use of undefined constant

- packages/neos-ui/src/index.js
**What I did**
Switched from deprecated `window.devToolsExtension` to its replacer `window.__REDUX_DEVTOOLS_EXTENSION__`
1. The deprecation warning is gone.
2. Devtools still works.
3. Still passes all tests.
**Before**
**After**
> TASK: Remove deprecation warning

- packages/neos-ui-validators/src/StringLength/index.spec.js
- packages/neos-ui-validators/src/StringLength/index.tsx
Adds an option `ignoreHtml` to the StringLengthValidator
Usage:
validation:
'Neos.Neos/Validation/StringLengthValidator':
maximum: 10
ignoreHtml: true
Resolves: #2579
> FEATURE: Allow StringLengthValidator to ignore HTML tags

- package.json
- yarn.lock
Updates the library react-close-on-escape to version 3.|
This is used in the dialogs of the UI
> TASK: Upgrade react-close-on-escape to version 3

- packages/neos-ui/src/index.js
**What I did**
Show human readable output instead of code in the error flash messages.
Check what kind of text we have in a backend flash message error and parse it.
Go to the Forms example in the Demo site and then:
Force JSON error: Rename the form nodetype datasource in yaml to something else.
Force 500 HTML error: break PHP code in form datasource. F.e. by adding `$foo = $forms * $formDefinitions;`
JSON error before:
JSON error after:
HTML error before:
HTML error after:
> FEATURE: Parse backend errors instead of showing raw code

- Classes/NodeCreationHandler/CreationDialogPropertiesCreationHandler.php
Since the interface for creation handlers is defined in the Neos.Neos.Ui
package this change is required for neos/neos-development-collection#2785
to work properly.
Related: neos/neos-development-collection#2173
> FEATURE: Node Creation Handler for the "CreationDialogProperties"

- packages/neos-ui-i18n/src/registry/I18nRegistry.js
The method substitutePlaceholders replaces the markers in language
labels with the given variables. For that all substrings will be saved in an
array and the array will be returned.
This patch concats the array items to a string. Because the translate method returns
strings in general and not arrays.
**What I did**
Just concat the array items to a string so that the return of the translate is consistent.
Use a label in JS like that.
```javascript
const label = i18nRegistry.translate(
'labelId',
'Default',
{
paramA: foo,
paramB: bar
},
'Neos.Neos.Ui'
);
```
Create your label like
```xml
<trans-unit id="labelId" xml:space="preserve">
<source>{paramA}: Don't be a fool, {paramB}</source>
</trans-unit>
```
Without the params the translate method will just return `{paramA}: …
> BUGFIX: Concat the label parts of the param replacement

- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/ToggleContentTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/Buttons/ToggleContentTree/style.css
- packages/neos-ui/src/Containers/LeftSideBar/index.js
- packages/neos-ui/src/Containers/LeftSideBar/style.css
- packages/react-ui-components/src/ToggablePanel/__snapshots__/toggablePanel.spec.js.snap
- packages/react-ui-components/src/ToggablePanel/style.css
- packages/react-ui-components/src/ToggablePanel/toggablePanel.js
**What I did**
Allow toggling groups in the sidebar / inspector by clicking on the whole group header
instead of just the icon.
Move the onClick handler to the wrap instead of the button and adjust the pointer via CSS.
Click the "Content tree", "Document tree" or any inspector group header.
resolves #2601
> FEATURE: Increase hitarea to toggle groups in sidebar and inspector

- Classes/Domain/Model/Changes/Property.php
**What I did**
Instead of telling the UI to force a reload on the whole document when a node is changed that is not child of a `ContentCollection` now the server looks for a node that can be safely reloaded in the list of parents of the node.
Traverse the parents and fusion path of the node until we find a good spot to reload.
Add a node like the following to the demo site and edit the TextWithImage node.
Without this change the document reloads. With the change only the `FixedChildren` node.
```
'My.Site:Content.FixedChildren':
superTypes:
'Neos.Neos:Content': true
ui:
label: 'Node with fixed children'
icon: columns
childNodes:
text:
type: 'Neos.Demo:Content.Text'
textWithImage:
type: 'Neos.Demo:Content.TextWithImage'
```
``` …
```
> FEATURE: Prevent page reload when editing fixed childnodes

- Configuration/Settings.yaml
- Tests/IntegrationTests/Fixtures/1Dimension/treeSearch.e2e.js
- packages/neos-ui-redux-store/src/UI/LeftSideBar/index.ts
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/index.js
- packages/neos-ui/src/localStorageMiddleware.js
- packages/neos-ui/src/manifest.hotkeys.js
**What I did**
Replaced the local state of the component with a redux persited state.
So that the state of the searchbar is stored in the local storage like the left sidebar or right sidebar.
So the users don`t need to open it over and over again.
Open or close the search bar in the left sidebar and reload. The state should be the same.
Resolves: #2606
> FEATURE: Save searchbar state in persitedState

- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
There was a call within the render method that contained `this.forceUpdate()`, which led to a warning in the console only visible for dev builds.
Moving the call to the `componentDidUpdate` lifecycle function resolves the issue while keeping the same functionality (`ClientEval` annotations are still evaluated).
> BUGFIX: Do not force update within render method

- packages/neos-ui-sagas/src/CR/ContentDimensions/index.js
Previously, the focused node was not updated after switching,
leading to unexpected behaviour when hiding/deleting nodes from the
NodeTreeToolbar.
**What I did**
Focus new target node after switching dimensions from the DimensionSwitcher.
1. Select page in tree
2. Switch content dimensions
3. Hide or delete node from the toolbar
Old behaviour:
The node from the source dimension would be hidden/deleted.
New behaviour:
The node in the new dimension is hidden/deleted.
> BUGFIX: Focus node in tree after switching dimensions

- packages/neos-ui-backend-connector/src/Endpoints/Helpers.ts
- packages/neos-ui-backend-connector/src/Endpoints/index.ts
It can happen that the URI is encoded and then the context
string could not be extracted. It seems to be a change from
the preview urls.
(https://github.com/neos/neos-development-collection/pull/2654)
(https://github.com/neos/neos-ui/pull/2604)
This patch now decodes the frontend URI and checks if the
URI contains an @ part.
> BUGFIX: Prevent exception on missing context string

- packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/index.js
- packages/neos-ui-guest-frame/src/dom.js
- packages/neos-ui-guest-frame/src/dom.spec.js
Without this change, scrolling could happen outside the viewport boundaries,
if e.g. the to-be-scrolled-to-element is placed outside the main document
boundaries (as it happens in a slider component, for example).
This change:
- fixes the bug by clamping the return value of
`getAbsolutePositionOfElementInGuestFrame` to the document dimensions
- adds lots of test cases for the specifics of clamping
- cleans up a minor detail in InlineUi/NodeToolbar
Resolves: #2040
> BUGFIX: ensure scrolling in guest frame is limited to document dimensions

- package.json
- yarn.lock
Normally this upgrade has breaking changes but we don't use this functions.
It is by the way a bit confusion that we ```import {action as createAction, ActionType} from 'typesafe-actions';``` because createAction is also part of the general API of `typesafe-actions`.
It is not a problem, more a naming thing because when you want to use the createAction you need to rename the import.
> TASK: Upgrade typesafe-actions to version 5.1

- packages/neos-ui-editors/src/Editors/AssetEditor/index.js
The AssetEditor changes to fix functionality for asset proxies sadly contained some code erorrs in the path for single usage editors. This breaks uploads with type errors. The change fixes that by adapting to similar code as is used in the multiple code path.
Fixes: #2642
> BUGFIX: Fix single AssetEditor uploads #2642

- Resources/Private/Translations/da/Main.xlf
Simple fix, which makes the danish language XML valid again (just removing double closing tag).
Solves #2646
> BUGFIX: Remove duplicate closing tag

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/index.js
With this change it’s possible to change the rootNode via a prop of the page and content tree for extensibility.
Example:
```
const PageTree = containerRegistry.get('LeftSideBar/Top/PageTree');
const ModifiedTree = () => (
<PageTree rootNode={aRootNodeThatIsNotTheSite} />
);
containerRegistry.set('LeftSideBar/Top/PageTree', ModifiedTree);
```
**What I did**
The `connect` method allows to define the order of how a components props are merged. By allowing outside props to override the state props it's now possible to change props like `rootNode` from the outside.
The current behaviour is unchanged.
> FEATURE: Allow override of rootnodes in node trees

- Makefile
- packages/react-ui-components/.gitignore
- packages/react-ui-components/README.md
- packages/react-ui-components/package.json
- packages/react-ui-components/scripts/generate-standalone-postcssrc.js
- packages/react-ui-components/src/DateInput/dateInput.tsx
- packages/react-ui-components/src/DropDown/header.tsx
- packages/react-ui-components/src/DropDown/index.ts
- packages/react-ui-components/src/DropDown/wrapper.tsx
- packages/react-ui-components/src/IconButtonDropDown/iconButtonDropDown.tsx
- packages/react-ui-components/tsconfig.esm.json
- packages/react-ui-components/tsconfig.esmtypes.json
To make react-ui-components usable standalone, we
should publish a transpiled-to-es-modules version
of the code, in the same manner as many other projects
publish their library code.
This way, the react-ui-components are embeddable
e.g. using parcel.js, or via webpack; without setting
up typescript compilation of node_modules (which is
discouraged).
> FEATURE: publish transpiled (ES-Modules) version of react-ui-components

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
When node editing is forbidden using `EditNodePrivilege`, the user can still edit/modify it in the inspector or change its position in the node tree. As the backend forbids this behavior, he gets an exception on saving.
1. as an example, in the Demo page, use the following `Policy.yaml`:
```yaml
privilegeTargets:
'Neos\ContentRepository\Security\Authorization\Privilege\Node\EditNodePrivilege':
'Neos.Demo:EditPageNodes':
matcher: 'nodeIsOfType("Neos.Demo:Document.Chapter")'
'Neos.Demo:EditTextNodes':
matcher: 'nodeIsOfType("Neos.Demo:Content.Text")'
```
This policy forbids editing `Document.Chapter` nodes and `Text` nodes for *everybody*.
2. Log into the backend.
3. Select one of the following nodes:
- In the page tree, select a chapter node
- On a page, select a `Text` node through the …
> EditNodePrivilege not always respected in UI (Inspector loads; Drag&Drop in Tree works)

- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodeInContainer.e2e.js
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Content.Container.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Content/Container/Container.fusion
- packages/neos-ui/src/manifest.js
Before this change a new node was always inserted as direct child.
With this change there can be any number of dom nodes and one
can be defnied as anchor for insertion.
When multiple anchors exist, the first one will be used.
The primary use case is for me was to have a ContentCollection that is also a content element itself. Usually the content collection has its own wrapper and all the children are in there.
But when it's also a content with some custom markup it can have any structure and therefore we cannot just assume inserting the new node into the content nodes main tag is the right position.
**What I did**
Allow defining a subnode in the template of a content collection to be the parent of new nodes.
A tag can have a new attribute which marks it as an anchor.
When …
> FEATURE: Allow inserting nodes into any position inside an element

- packages/neos-ui-views/src/Data/DataLoader/index.js
This would reload the data when a config like this is used and the related property changes:
```
view: 'Content/Inspector/Views/Data/TableView'
viewOptions:
dataSource: 'my-data-source'
arguments:
myDataArgument: 'ClientEval: node.properties.foo‘
```
> BUGFIX: Refresh the dataloader when its arguments change

- packages/neos-ui/src/index.js
Internal server errors without the Flow stacktrace html
were not properly parsed and rendered.
Therefore the raw html was shown as error message.
> BUGFIX: Internal server errors were not parsed

- Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Content/Container/Container.fusion
- packages/neos-ui/src/manifest.js
This is a fix for #2609 
which now allows to add the insertion-anchor attribute to
Neos.Neos:ContentCollection by default and use it at any position in
AFX for rendering and adding nodes instead of adding
the ContentCollectionRenderer and adding the attribute to the
wrap manually.
Previously the contextpath attribute of a content collection
would break this mechanism as it was checking that only the
outest parent has the contextpath.
> BUGFIX: Allow a contentcollection to be the insertion anchor

- packages/react-ui-components/package.json
This caused an error when trying to build the library
> BUGFIX: logo.svg was missing in esm build

- packages/react-ui-components/src/Frame/frame.tsx
Most of the time `win.location.href` is not yet set and therefore
`componentDidUpdate` and `componentDidMount` both trigger
a load of the new page in the iframe.
Resolves: #2671
> BUGFIX: Prevent second page load

- Classes/Controller/BackendServiceController.php
- Resources/Private/Translations/de/Main.xlf
- Resources/Private/Translations/en/Main.xlf
**What I did**
Use translator for UI messages on workspace actions.
And use the workspace title instead of its technical name
which can be misleading when the title of a workspace
is changed, as the name is not changed in this case.
Use translator and also support plural/singular forms.
Publish & discard changes in the UI
> BUGFIX: Localize publish actions

- Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
$toggledNodes from the client side is an array of strings, each being a currently expanded NodeContextPath.
Thus, we cannot compare it based on the NodeAggregateIdentifier; because that's not what it is from the client side.
- In the Document tree, expand a few nodes which are not automatically loaded (i.e. below the default loadingDepth)
- then, press the "refresh" icon.
- EXPECTED: the full tree is refreshed
- ACTUAL: the tree is collapsed again.
Note: This is only broken since https://github.com/neos/neos-ui/pull/2178 - and only master is affected.
> BUGFIX: fix refreshing of page tree with expanded nodes

- packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
The function allowedSiblingsOrChildrenChanged was not in use anymore and it seems that an upmerge has failed.
This is related to the PR for neos 4.x
Take a look at https://github.com/neos/neos-ui/pull/2678
> BUGFIX: Resolve linting issue

- packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
Because of the way the webpack configs are merged the extensions list defined in build-essentials was overriden and later replaced by the webpack default which only contains normal js extensions.
> BUGFIX: Allow ts imports in plugins

- Resources/Private/Fusion/Prototypes/GlobalCacheIdentifiers.fusion
As the old UI is not usable anymore the special global cache identifier
can be removed.
> TASK: Remove global cache identifier as old Ui is not longer supported

- Resources/Private/Templates/Backend/Index.html
I added the missing <meta> charset attribute. This fix some encoding issues if the server is not set to UTF-8. 
You can already find `<meta charset="utf-8" />` on every Page that get printed by Neos but not in the Neos Content Backend.
Before:
After:
I use 4.0 as base branch because it is the lowest maintained branch but the bug exist since version 1.
> BUGFIX: added missing <meta> charset attribute

- packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
This partly reverts #2648 that completely disabled
the inspector for read-only nodes only removing
editor-properties.
Fixes: #2705
> BUGFIX: Don't disable views for read only nodes

- packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
- packages/react-ui-components/src/Dialog/__snapshots__/dialog.spec.tsx.snap
- packages/react-ui-components/src/Dialog/dialog.spec.tsx
- packages/react-ui-components/src/Dialog/dialog.tsx
- packages/react-ui-components/src/TextInput/textInput.tsx
**What I did**
The NodeCreationDialog always throws errors because the options are passed thru as array instead of an object. So I modified the data type here.
The already set autoFocus property did not work for the first element of the Creation Dialog.
So this patch also fixes the setting of the autofocus for the editor fields.
Another issue was that the dialog always gets the focus by default and therefore the first element was not focused.
Create a new page in the backend and the title field will be focused.
Fixes: #2696
> BUGFIX: Focus first form element in node creation dialog

- packages/neos-ui-backend-connector/src/Endpoints/index.ts
- packages/neos-ui-editors/src/Library/NodeOption.js
This removes some ancient hack that tried to determine the "uriInLiveWorkspace".
Background:
The code extracted the context path that was previously specified via
`@<context>` in the "backend URLs". Due to the dedicated preview routes
that were introduced with Neos 5.1 this no longer worked and led to the
preview URL rendered twice instead..
Related: neos/neos-development-collection#2965
> BUGFIX: Avoid URLs to be rendered twice in link- and reference editors

- Build/Jenkins/update-neos-ui-compiled.sh
This should solve the out of memory errors with 5.2.0 production build https://jenkins.neos.io/job/neos-build-minified/18450/console
> BUGFIX: Increase memory limit for node in jenkins build

- packages/neos-ui/src/Containers/Modals/InsertMode/index.js
The renderNodeLabel function returns a component instead of
a string. This is not usable as parameter for the I18n component.
So renderNodeLabel returns now a string.
Fixes: #2685
> BUGFIX: Render node labels in insert mode dialog

- packages/neos-ui-redux-store/src/CR/Nodes/index.ts
In #2578 the merge function was replaced
but the new one needs a different parameter
order as it merged from left to right instead
of right to left.
Resolves: #2665
> BUGFIX: Correctly merge nodedata after updates and update tree

- packages/neos-ui-sagas/src/Publish/index.js
The server response already supplies the correct
preview url for the backend incl. the dimensions
and target workspace.
Resolves: #2450
> BUGFIX: Use correct preview url after publishing

- packages/neos-ui-extensibility/package.json
The versions of build-essentials and positional-array-sorter are wrong and does not fit the version of the current release. That leads to the problem that in the upcoming release version will be not replaced. The new release only replaces the current version number with the new released version. So the two packages will never get updated.
This is a result of a wrong up merge so that we had not the latest version.
Fixes: #2742
> BUGFIX: Manually adjust versions

- packages/neos-ui-editors/src/Library/LinkInput.js
Make it possible to pass options to the inline link editor through configuration, so the inline link editor is fully configurable like the link editor within the inspector.
resolves: #2710
> BUGFIX: Allow additional options to inline link editor

- packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
This was a regression in 61d01af9
Also includes an optimisation to prevent repeated reassignment of the same state.
> BUGFIX: With some configurations the creation dialog was readonly

- Tests/IntegrationTests/Fixtures/1Dimension/refreshTree.e2e.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
The already loaded node data was overwritten
after the refresh and therefore lost all
stored data including the data required for
the inspector to show the node.
Resolves: #2652
> BUGFIX: Prevent endless spinner in inspector after tree refresh

- Classes/Domain/Model/Changes/AbstractCopy.php
- Classes/Domain/Model/Changes/AbstractCreate.php
- Classes/Domain/Model/Changes/AbstractMove.php
- Classes/Domain/Model/Changes/AbstractStructuralChange.php
- Classes/Domain/Model/Feedback/Operations/UpdateNodePath.php
- packages/neos-ui-redux-store/src/CR/Nodes/index.ts
- packages/neos-ui/src/manifest.js
**What I did**
WIth this change instead of returning the information for the moved node and all its
descendants only the changes to the new and old parent and the information
about the old and new context path are submitted.
The already stored nodes are then updated with this information instead of being replaced
completely with the new information from the server.
This improves the response time by ~50% and memory consumption by 25% - 80%.
Large move operations still need a lot of memory and some time to compute
the updated workspace information. This issue will be fixed in a future PR.
This change also has the side effect, that after a move action the moved node can be focused again, 
as the information is now available where it went.
Before the old was removed and a redirect to the …
> !!! BUGFIX: Speed up move actions to prevent timeouts

- Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestSite/composer.json
- Tests/IntegrationTests/TestDistribution/composer.json
With the current configuration the test distribution always installs the latest 5.x neos and that is not compatible since the preview url change.
So we should limit that to neos 5.0 and adapt that for the upcoming versions.
**What I did**
Changed version constraint from caret version to tilde version.
Check end to end tests of the PR.
> TASK: Limit dependencies to neos 5.0

- packages/neos-ui/src/manifest.js
When moving a node inside a content collection column for instance the node was rendered twice until the user reloads the page. As the move event work in general and we have just the issue that the out of band rendering renders the node two times. We (@Sebobo and me) decided to just remove the existing node and solve the glitch this way.
Fixes: #2773
**What I did**
Remove duplicate node on out of band rendering.
Move a node inside a content collection column. So if you have two nodes in one column, just move the second before the first element for instance.
Thanks to @patricekaufmann for reporting the issue and @Sebobo for fixing the issue in a pair programming session 💙
> BUGFIX: Remove existing element when moving node on same level

- packages/neos-ui-redux-store/src/CR/Nodes/index.ts
This fixes a regression introduced by #2578, and not fully fixed by #2743.
originally (see https://github.com/neos/neos-ui/pull/2578/files#diff-a1ae46b74f22675b47bfe28db766094fL393)
the code looked like:
mergedNode = mergeDeepRight(draft.byContextPath[contextPath], newNode);
NOT modifying any parameters; and parameters further to the right override
parameters on the left.
With https://github.com/neos/neos-ui/pull/2743/files, this was changed to:
mergedNode = defaultsDeep(newNode, draft.byContextPath[contextPath], {});
- defaultsDeep MODIFIES the first parameter AND returns it. (see https://lodash.com/docs#defaultsDeep).
Parameters are merged from right to left, so parameters further on the left override parameters further
to the right. EXCEPT the leftmost parameter, where everything is …
> [BUGFIX] really ;) correctly merge nodedata after updates and update tree

- Classes/Controller/BackendServiceController.php
- Classes/Domain/Model/Feedback/Operations/UpdateNodePreviewUrl.php
- Classes/Fusion/Helper/NodeInfoHelper.php
- Configuration/Settings.yaml
- packages/neos-ui-sagas/src/Publish/index.js
- packages/neos-ui-sagas/src/UI/Inspector/index.js
- packages/neos-ui/src/manifest.js
With this change the `PreviewButton` of the UI never links to a preview
of the node in the personal user workspace.
Instead it:
* Is disabled if the node is hidden/missing in the base workspace
* Points to a `/neos/redirect?<node-in-base-workspace>` URL that redirects to the current node
in its base workspace
For the "usual editing case" (personal workspace with target == `live`)
that means, that clicking the button will lead to the version in the live
workspace (i.e. `/the/final/url.html`).
For shared workspaces the redirect will point to a preview URL for that
workspace (i.e. `/neos/preview?node=<node-in-shared-workspace>`)
Fixes: neos/neos-development-collection#3019
> BUGFIX: Prevent preview button to link to the personal user workspace

- packages/neos-ui-redux-store/src/UI/PageTree/index.ts
- packages/neos-ui-sagas/src/CR/NodeOperations/reloadState.js
Fixes: https://github.com/neos/neos-ui/issues/2093
**What I did**
Currently if you reload the document tree nodes during searching or filtering by preset, it leads to very odd results. This PR fixes it.
I store the current query and filter preset inside redux state and do `commenceSearch` instead of reloading the default nodes when the refresh button is clicked.
Put this into Settings.yaml:
```yaml
Neos:
Neos:
userInterface:
navigateComponent:
nodeTree:
presets:
'default':
baseNodeType: 'Neos.Neos:Document,!Neos.Demo:Chapter'
'legalPages':
ui:
label: 'Test Preset'
baseNodeType: 'Neos.Demo:Chapter'
```
Toggle the preset and hit reload. Also try searching for something and hit reload.
> BUGFIX: fix reload when filtering or searching

- packages/neos-ui-redux-store/src/CR/Nodes/helpers.ts
- packages/neos-ui-redux-store/src/CR/Nodes/index.ts
Fixes: https://github.com/neos/neos-ui/issues/1691
**What I did**
When you toggle a custom tree preset and then navigate the tree, the children of the node missing in the default preset would disappear. I fixed it.
When we are navigating to some page, the node information about this node is being read from the script tags rendered on that page and merged into the redux state. Now it so happens that those inline script tags are rendered according to the default preset, and so the nodes that exist only in the preset get removed from the redux state.
The only way I could think of fixing it is to actually merge children instead of overwriting them. I first merge them, then make sure there are now duplicates left comparing them by context paths.
See the …
> BUGFIX: merge children instead of replacing them

- packages/react-ui-components/src/TextArea/textArea.tsx
**What I did**
Extend the TextArea props to inherit the HTML Textarea props to receive additional options from the TextArea inspector editor.
Similar to the TextInput component
Create a textfield property with a maxlength option:
```yaml
text:
ui:
inspector:
editor: 'Neos.Neos/Inspector/Editors/TextAreaEditor'
editorOptions:
maxlength: 100
```
Maybe the editor component should also support the additional options, that are listed in the [documentation](https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-string-textareaeditor-multi-line-text-editor), like `selectionDirection` or `spellcheck`.
> BUGFIX: pass missing props to TextArea react-ui-component

- Classes/Controller/BackendController.php
- Classes/Domain/Model/Changes/AbstractCreate.php
- Classes/Domain/Model/Changes/AbstractStructuralChange.php
- Classes/Domain/Model/Changes/MoveAfter.php
- Classes/Domain/Model/Changes/MoveBefore.php
- Classes/Domain/Model/Changes/MoveInto.php
- Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
- Classes/Fusion/Helper/NodeInfoHelper.php
- Resources/Private/Fusion/Prototypes/Page.fusion
- packages/neos-ui-backend-connector/src/Endpoints/Helpers.ts
- packages/neos-ui-redux-store/src/CR/Nodes/helpers.ts
- packages/neos-ui-redux-store/src/CR/Nodes/index.ts
- packages/neos-ui-sagas/src/CR/NodeOperations/addNode.js
- packages/neos-ui-sagas/src/CR/NodeOperations/moveDroppedNode.js
- packages/neos-ui-sagas/src/CR/NodeOperations/pasteNode.js
- packages/neos-ui-sagas/src/UI/PageTree/index.js
- packages/neos-ui/src/Containers/ContentCanvas/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
Fixes: https://github.com/neos/neos-ui/issues/1691
TODO:
**What I did**
Creating or moving nodes when tree preset was activated used to cause them to disappear from the tree.
That happened because the node information rendered with NodeInfo helper used to always use the default preset, and not the one that is currently active.
I'm passing the currently active tree preset along with create and copy/move change requests, and then use it server-side to render the correct child nodes with UpdateNodeInfo feedback.
1. Set up some tree presets, e.g.:
```yaml
Neos:
Neos:
userInterface:
navigateComponent:
nodeTree:
presets:
'default':
baseNodeType: 'Neos.Neos:Document,!Neos.Demo:Document.Chapter'
'legalPages':
ui:
label: 'Test Preset'
baseNodeType: …
```
> BUGFIX: fix creating and moving nodes with tree preset activated

- packages/react-ui-components/src/Button/button.tsx
**What I did**
Removed the property isDisabled from the button component.
The prop has beed deprecated two years ago.
Relates: #2798
> TASK: Remove deprecated isDisabled Button prop

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
- packages/utils-helpers/src/urlWithParams.spec.js
- packages/utils-helpers/src/urlWithParams.ts
Fixes a regression introduced with upmerging #2794 since
the new helper `urlWithParams` wasn't added.
Note:
Instead of adding the helper to the endpoint helpers, this
extends the already existing `urlWithParams` helper such that
it keeps existing query params.
Fixes: #2805
> BUGFIX: Fix NodeType filter regression

- Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
> BUGFIX: Make the baseNodeType optional in updateNodeInfo

- .circleci/config.yml
- Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestSite/composer.json
- Tests/IntegrationTests/TestDistribution/composer.json
**What I did**
Changed the base image for the circle ci pipeline to a php 7.4 based.
Also use the neos/neos master as we have changes there that are needed for the neos-ui master.
The old test suite installed neos 5.3.
> TASK: Adjust CircleCI config to run master tests with php 7.4

- Tests/IntegrationTests/Fixtures/1Dimension/treeMultiselect.e2e.js
It happens that we move nodes and then go to the moved side. But this side is not available when we discard the content change. So the following test willl fail.
**What I did**
Switch node tree at the end of the test to home, as we never move this node.
> BUGFIX: Switch back to home in the tree before discard the content

- .circleci/config.yml
Circle CI now uses node version 14 instead of our version 12 and fails on switchingh the version.
> TASK: Adapt circle ci config to use nvm node version

- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodeInContainer.e2e.js
- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
- Tests/IntegrationTests/Fixtures/1Dimension/treeMultiselect.e2e.js
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Content.Container.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Content.Headline.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Content.Image.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Content.Text.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Document.Page.yaml
It can happen that you have a neos distribution that uses the neos nodetypes and want to execute the neos-ui e2e tests. Then the own node types are not used because they have the same name as the basic neos nodetypes.
**What I did**
Add the _Test to the name of the nodetypes.
Run the tests
> TASK: Make testing distribution work with more neos installations

- packages/neos-ui-i18n/src/registry/I18nRegistry.js
- packages/neos-ui-i18n/src/registry/I18nRegistry.spec.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
Sometimes you are using language labels with arguments and it can happen that you need a singular and plural of a word depending on the argument. For instance for the amout of errors.
XLIFF supports that and the flow translator as well. But when you want to use that labels in the JS part of the neos-ui you have no possibility to get the plural. You always get the singular if this is the first value in the group.
The following PR extended the `XliffService` to create a response that also respects plurals, so that the UI is able to consume the plural labels as well. https://github.com/neos/neos-development-collection/issues/2786
This change is not breaking as it uses singular labels when no plural exists. Take a look at the unit tests for instance.
**What I did**
Added a quantity parameter …
> FEATURE: Use language plurals in I18n registry 

- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Content.Headline.yaml
It is possible to configure a context help for each nodetype. And you can use markdown for this help message.
As we sometime upgrade the Markdown library we should also have a test for that.
Resolves: #2825
> FEATURE: Add new e2e test for nodetype help with markdown

- Build/Docker/run.sh
- Makefile
- package.json
- yarn.lock
For security reasons we need to upgrade the webpack-cli because it uses  y18n with potential vulnerabilities.
@see https://snyk.io/vuln/SNYK-JS-Y18N-1021887
Fixes: #2842
> TASK: Upgrade webpack-cli to version 4.2

- packages/neos-ui-editors/src/Editors/UriPathSegment/index.js
The sync button did not respect the editorOption disabled and therefore the uriPathSegment could be updated even when the property was disabled.
Fixes: #2824
> BUGFIX: Add disabled property to sync button

- package.json
- yarn.lock
We are using regenerator-runtime for this pupose and as regenerator cam with a security vulnerability with y18n we remove it.
fix: #2844
> TASK: Remove unused regenerator

- Classes/Domain/Model/Feedback/Operations/Redirect.php
- Classes/Domain/Model/Feedback/Operations/ReloadDocument.php
- Classes/Domain/Service/NodeTreeBuilder.php
- Classes/Fusion/Helper/NodeInfoHelper.php
The LinkingService.createNodeUri() no longer uses/accepts this
parameter…
See https://github.com/neos/neos-development-collection/pull/3168
> TASK: Remove use of resolveShortcuts argument

- Resources/Private/Fusion/Prototypes/Page.fusion
The neosBackendContainer has been removed with the old emberjs content module. Because this container could not be found the container has been added to the beginning of the body tag.
Now we adjust the position to the end of the body section.
Thanks to @bwaidelich and @suffle for this hint 💙 
Fixes: #2828
> BUGFIX: Moves neos backend container

- Resources/Private/Fusion/Prototypes/Page.fusion
- Resources/Private/Templates/Error/ErrorMessage.html
- packages/neos-ui/src/Containers/ContentCanvas/index.js
Rename the container from `neos-new-backend-container` to `neos-backend-container`. The emberjs content module has been removed for 5.0 and now we rename the backend container as we have no old and new one anymore.
This can cause issues when the third party code rely on the neos-new-backend-container id.
Related: #2828
Fixes: #2849
> TASK: Rename neos backend container

- Tests/IntegrationTests/Fixtures/1Dimension/SitePackage/Resources/Private/Content/Sites.xml
- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
- Tests/IntegrationTests/Fixtures/1Dimension/selectBoxes.e2e.js
- Tests/IntegrationTests/Fixtures/1Dimension/treeSearch.e2e.js
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Document.SelectBoxTestPage.OpensAbove.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Document.SelectBoxTestPage.OpensAboveInInspector.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Document.SelectBoxTestPage.OpensBelowAndBreaksOut.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/Settings.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Document/SelectBoxTestPage/OpensAboveIn.fusion
- Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Document/SelectBoxTestPage/OpensAboveInInspector.fusion
- Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Root.fusion
- Tests/IntegrationTests/pageModel.js
- packages/build-essentials/src/styles/styleConstants.js
- packages/react-ui-components/src/DropDown/contents.spec.tsx
- packages/react-ui-components/src/DropDown/contents.tsx
- packages/react-ui-components/src/DropDown/style.css
- packages/react-ui-components/src/DropDown/wrapper.tsx
To backport the changes to Neos 5.3 as well I took the awesome PR from @grebaldi and target this to 5.3.
To see the discussions visit https://github.com/neos/neos-ui/pull/2799
**Description from Wilhelm:**
Hi there!
This PR enhances the DropDown component in two ways:
1. It allows drop down contents to break out of overflow-restricted areas like the content creation dialog.
2. It positions dropdown contents above the dropdown header, if there's not enough space below it.
All of the above are only effective if the DropDown is marked as `scrollable`. Otherwise, it is assumed that the call-site of the DropDown component is aware of any screen-related size-restrictions and reserves enough space below wherever the DropDown is placed.
|**Example:** Creation Dialog, breakout|**Example:** …
> BUGFIX: Allow dropdown contents to break out of overflow-restricted areas

- Resources/Private/Fusion/Prototypes/Page.fusion
The `head.javascriptDocumentInformation` path was renamed to  `...javascriptBackendInformation`
a long time ago (#98) but the `@position` of `head.guestFrameApplication` part was never updated accordingly.
With the current Flow version this led to an exception:
```
The positional string "after javascriptDocumentInformation" (defined for key "guestFrameApplication") references a non-existing key.
```
> BUGFIX: Fix position of guestFrameApplication in Page prototype

- Configuration/Routes.yaml
Removes the deprecated "Backend Login New UI Route" that was added
in order to explicitly switch between "classic" and "new" UI.
Related: #2360
> TASK: Remove legacy "neos!" route

- packages/neos-ui-editors/src/Library/LinkInput.js
Nowadays most of the URLs are or at least should be accessible through https, so this should be the better default.
> TASK: Change auto formatting to https

- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
- Tests/IntegrationTests/SharedNodeTypesPackage/Classes/NodeCreationHandler/ImagePropertyNodeCreationHandler.php
- Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/NodeTypes.Document.PageWithImage.yaml
- Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Document/PageWithImage/PageWithImage.fusion
- Tests/IntegrationTests/SharedNodeTypesPackage/composer.json
- Tests/IntegrationTests/e2e.sh
- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui-redux-store/src/UI/NodeCreationDialog/index.ts
- packages/neos-ui-sagas/src/CR/NodeOperations/addNode.js
- packages/neos-ui-sagas/src/Changes/saveHooks.spec.ts
- packages/neos-ui-sagas/src/Changes/saveHooks.ts
- packages/neos-ui-sagas/src/UI/Inspector/index.js
- packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
- packages/neos-ui/src/Containers/Modals/NodeCreationDialog/style.css
- packages/react-ui-components/src/Dialog/__snapshots__/dialog.spec.tsx.snap
- packages/react-ui-components/src/Dialog/dialog.spec.tsx
- packages/react-ui-components/src/Dialog/dialog.tsx
- packages/react-ui-components/src/Dialog/style.css
Hi there,
this PR is an attempt to finally allow secondary editors (like the media selection screen or the image cropper) to be used in the NodeCreationDialog.
The result looks like this:
https://user-images.githubusercontent.com/2522299/104287035-2a932700-54b6-11eb-9ce2-45f8724339f6.mp4
_**EDIT**: Updated video to better reflect the latest style changes._
- SaveHook-Logic was extracted from the inspector saga and put into "Changes" scope, so it could be shared between inspector and node creation dialog
- General overhaul of NodeCreationDialog to achieve support for SaveHooks and SecondaryInspector
- Additional "jumbo" style for Dialog component was added
- An `ImagePropertyNodeCreationHandler` was added to the Integration Test distribution to decouple this change from an additional …
> BUGFIX: Allow for rendering of secondary editors in NodeCreationDialog

- .circleci/config.yml
Sometimes it is helpful to be able to flush the circle ci caches manually instead of changing something in the composer.json.
So we add the CACHE_VERSION parameter in the cache identifier and this can be defined in the CircleCI environment settings.
> TASK: Add CACHE_VERSION parameter to CircleCI config

- Resources/Private/Fusion/Backend/Component/ModuleMenu.fusion
Fixes: https://github.com/neos/neos-development-collection/issues/3287
Needs the `Array.values()` Eel helper introduced with latest Neos 7.0 bugfix.
> BUGFIX: Render correct JSON when a module is hidden

- Classes/FlowQueryOperations/SearchOperation.php
Thanks to @dfeyer for creating the PR #2876
I was not able to change the PR so I created this one based on the 4.0 branch with @dfeyer commit.
Thanks for this bugfix ❤️
> BUGFIX: SearchOperation must use the NodeSearchServiceInterface

- packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js
**What I did**
The SelectBoxEditor in the Backend can be disabled as documented in https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-string-array-string-selectboxeditor-dropdown-select-editor 
This does not work if the SelectBox has a datasource configured, but it would be helpful in a specific case:
We want to show a required selectBox in the node creation dialog that gets it's data from a dataSource. This property should not be editable in the inspector afterwards, but we still want to show the selected Option so the editor knows what was selected during node creation. (We can not use a disabled input field, because it would show the selected value and not the selected label)
I added the disabled property in the …
> BUGFIX: enable "disabled"-property for DataSourceBasedSelectBoxEditor

- Classes/TypeConverter/ChangeCollectionConverter.php
The injected Persistence Manager is injected into the "changeClassInstance" during conversion. If `injectPersistenceManager` uses a `PersistenceManagerInterface` type hint, this injection will fail if `$this->persistenceManager` hasn't been used yet, because it will be a `DependencyInjectionProxy` instead of the real thing.
Therefore: Always disable lazy injection in these cases.
See also: https://github.com/neos/flow-development-collection/pull/2423
> Fix injection conf in ChangeCollectionConverter

- packages/react-ui-components/src/Label/style.css
Hi there,
this PR removes the width restriction from editor labels and also applies `text-overflow: ellipsis;` to the `<span>` tags that are usually rendered as their children. This allows for longer labels in the node creation dialog.
solves: #2889
> BUGFIX: Remove width restriction from editor labels

- packages/neos-ui/src/Containers/RightSideBar/Inspector/InspectorEditorEnvelope/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
Hello there,
this is a small fix to prevent auto-created child nodes from being hidden via the inspector and thus make that prevention consistent with the node tree toolbars.
**What I did**
I added an explicit check to the `InspectorEditorEnvelope` to see, whether we're currently looking at an auto-created child node and whether we're currently rendering the editor for the `_hidden` property. If so, the editor will be initialized with the option `disabled` set invariably to `true`.
That condition is also considered in the `isPropertyEnabled` method of the `Inspector` component (though I'm not sure about whether that makes sense).
Add this NodeType configuration to your setup:
```yaml
'Neos.Neos:ContentCollection':
superTypes:
'Neos.Neos:Hidable': true
```
And then …
> BUGFIX: Ensure that auto-created child nodes cannot be hidden via the inspector

- .circleci/config.yml
- Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
- Classes/Domain/Model/RenderedNodeDomAddress.php
- Tests/IntegrationTests/TestDistribution/composer.json
- Tests/Unit/Domain/Model/RenderedNodeDomAddressTest.php
Hi there,
out-of-band rendering in the UI works via so-called DomAddresses that contain the information what fusion path needs to be used to re-render a certain content element. That fusion path usually leads through a `Neos.Neos:ContentCase` ending up at a NodeType-specific fusion prototype.
Out-of-band rendering happens when a node properties change and a rendered content element needs to be updated. If the property that was changes was the NodeType of that content element, the behavior described above runs into a problem. The prototype used for rendering is no longer the prototype that `Neos.Neos:ContentCase` would lead to. This problem is described in issue  #2767.
This PR is an attempt at solving that problem by manipulating the above mentioned fusion path, so that it always tries to …
> BUGFIX: Always try to re-render content by re-evaluating its closest ContentCase

- packages/neos-ui-ckeditor5-bindings/package.json
- packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/Helpers/renderToolbarComponents.js
- packages/neos-ui-ckeditor5-bindings/src/manifest.config.js
- packages/neos-ui-ckeditor5-bindings/src/manifest.richtextToolbar.js
- yarn.lock
Hi there,
this PR adds `@ckeditor/ckeditor5-remove-format` to the dependencies of `@neos-project/neos-ui-ckeditor5-bindings` and uses it to realize the formerly non-functional `removeFormat` option for CK Editor.
solves #2878
> BUGFIX: Add removeFormat button to CKEditor5 toolbar

- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
- Tests/IntegrationTests/Fixtures/1Dimension/selectBoxes.e2e.js
- packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
Hi there,
this PR enables help messages and thumbnails for the Creation Dialog by passing both properties through to the respective EditorEnvelope.
https://user-images.githubusercontent.com/2522299/115356138-a4286880-a1bb-11eb-8705-8eba378b1852.mp4
This feature works out-of-the-box for properties that have the `showInCreationDialog` flag. For custom Creation Dialog elements a help message and/or thumbnail can be configured in the `ui` section like this:
```yaml
'Vendor.Site:SomeNode':
ui:
creationDialog:
elements:
'someElement':
type: string
ui:
label: 'Some Label'
editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
help:
thumbnail: resource://Vendor.Site/Images/help.jpg
message: >
This is a help message
```
resolves: #2862
> BUGFIX: Enable help messages and thumbnails in creation dialog

- packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/LinkButton.js
- packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
- packages/neos-ui-ckeditor5-bindings/src/manifest.js
- packages/neos-ui-redux-store/src/UI/ContentCanvas/index.ts
- packages/neos-ui-redux-store/src/UI/ContentCanvas/selectors.ts
Hi there,
as layed out in #2002, this PR adds a keyboard shortcut on Ctrl+K to toggle the Link Editor. For this, I moved the toggle state of the LinkButton component into the redux store.
solves #2002
> FEATURE: Open Link Editor when Ctrl+K is pressed

- packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Hi there,
this PR contains a small bugfix to prevent drag and drop across the Document and Content trees. This never actually worked in the first place, but the UI gave visual indication that this would be a valid operation.
**Before:**
https://user-images.githubusercontent.com/2522299/115692548-62382780-a35f-11eb-8936-f41082e5b067.mp4 
**After:**
https://user-images.githubusercontent.com/2522299/115692594-6bc18f80-a35f-11eb-8be9-50bd42ce4c86.mp4
fixes: #2741
> BUGFIX: Prevent drag and drop across trees

- Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
- Tests/IntegrationTests/Fixtures/1Dimension/inspector.e2e.js
- packages/neos-ui/src/Containers/App.js
- packages/neos-ui/src/Containers/Drawer/index.js
- packages/neos-ui/src/Containers/Modals/NodeVariantCreationDialog/index.js
- packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/index.js
- packages/neos-ui/src/Containers/Root.js
TODO
Failures were related to a Guzzle deprecation fixed in https://github.com/neos/neos-development-collection/pull/3368
An unfixed version of Neos.Fusion got stuck in the CircleCI cache. Resetting cache keys as described in https://github.com/neos/neos-ui#just-the-end-to-end-tests-fail fixed that.
> TASK: Fix e2e tests

- packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js
- packages/neos-ui-editors/src/Editors/SelectBox/index.spec.js
- packages/neos-ui-editors/src/Library/PreviewOption.js
**What I did**
Options returned from a datasource can now contain a `preview` with an absolute image uri which will then be shown in the dropdown.
Use new option component supporting previews for data source based selectboxeditor.
Works almost identically to the AssetOption of the AssetEditor.
Also added a test.
Resolves: #2914
> FEATURE: Support preview uris in datasource selectboxeditor

- packages/neos-ui-editors/src/Editors/AssetEditor/index.js
**What I did**
The AssetEditor receives the `propertyName` as in its `identifier` prop. This prop had to be forwarded to the `AssetUpload` component.
Resolves: #2867 
See #2867
> BUGFIX: Provide propertyname on asset upload

- packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
The option `allowCustom` hides the dropdown selection
for a custom ratio, but without this patch the controlls still
allowed setting a custom ratio by modifying the numbers.
Now the ratio controls are disabled if the custom ratio is disabled.
Resolves: #2909
> BUGFIX: Prevent custom image ratios when disabled

- package.json
- packages/neos-ui-editors/src/_lib/testUtils.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.spec.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
- yarn.lock
Relates: #2285
**What I did**
Inspector tabs and groups are now skipped during rendering if they don't contain visible items. Before three dots were rendered if `items` are null, or just the header for an empty item array.
There were already checks whether items were accessible, this was extended to also check whether the `hidden` prop is set (supports `ClientEval`).
Additionally before a tab or group is rendered a check was added whether the items array contains an item. 
The new implementation should also be slightly faster, as the check for visible items was optimised and the render function of 
PropertyGroups is not created dynamically all the time anymore.
A jest test was added for the groups.
To verify manually you can use this document type …
> BUGFIX: Hide empty tabs and groups

- packages/react-ui-components/src/Icon/mapper.ts
Show the hotel icon instead of the bed
Resolves: #2697
> BUGFIX: Use correct hotel icon mapping

- packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
- packages/neos-ui-extensibility/src/shims/neosProjectPackages/neos-ui-guest-frame/index.js
- packages/neos-ui/src/apiExposureMap.js
This makes it possible to reuse the guest iframe api for getting the guest iframe and fx. dispatching events.
you can then create a custom extension and import from '@neos-project/neos-ui-guest-frame' as if you have this file '@neos-project/neos-ui-guest-frame/src/dom' https://github.com/neos/neos-ui/blob/master/packages/neos-ui-guest-frame/src/dom.js installed.
```js
import {getGuestFrameDocument, dispatchCustomEvent} from '@neos-project/neos-ui-guest-frame'
```
slack discussion over here: https://neos-project.slack.com/archives/C0U0KEGDQ/p1629923508013600
> **Note:**
> 
> Internally it seems that to access the ./dom file of the @neos-project/neos-ui-guest-frame one need to import directly from it like:
> 
> ```js
> import {getGuestFrameDocument, dispatchCustomEvent} from …
```
> FEATURE: Consumer Api for @neos-project/neos-ui-guest-frame

- .circleci/config.yml
As the circle CI images has been updated to the current active node LTS (version 16) we need to stick our images to node version 14. So that the tests will still run for the older neos-ui versions.
> TASK: Change circleCI image to node:14.18-browsers

- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui-editors/src/Editors/Boolean/index.js
- packages/neos-ui-editors/src/Editors/Boolean/style.css
- packages/react-ui-components/src/CheckBox/style.css
- packages/react-ui-components/src/Label/style.css
**What I did**
I adjust the handling of long labels for the boolean editor
i adjusted the styling for the label, the checkbox and the boolean editor. I adjusted the rendering of the label and help message icon. I adjusted the toogleHelpMessage function.
Old:
New:
> BUGFIX: Issue #2976 adjust handling of long labels for boolean editor

- packages/neos-ui-editors/src/EditorEnvelope/style.css
- packages/neos-ui/src/Containers/Modals/SelectNodeType/style.css
Links in help messages are very hard to read, so I set the color.
> BUGFIX: Set color of links in help messages

- package.json
- packages/react-ui-components/package.json
- packages/react-ui-components/src/CheckBox/__snapshots__/checkBox.spec.tsx.snap
- packages/react-ui-components/src/DateInput/__snapshots__/dateInput.spec.tsx.snap
- packages/react-ui-components/src/DropDown/__snapshots__/header.spec.tsx.snap
- packages/react-ui-components/src/Icon/__snapshots__/fontAwesomeIcon.spec.tsx.snap
- packages/react-ui-components/src/Icon/__snapshots__/icon.spec.tsx.snap
- packages/react-ui-components/src/Icon/fontAwesomeIcon.spec.tsx
- packages/react-ui-components/src/Icon/fontAwesomeIcon.tsx
- packages/react-ui-components/src/Icon/icon.tsx
- packages/react-ui-components/src/Icon/index.ts
- packages/react-ui-components/src/Icon/resourceIcon.tsx
- packages/react-ui-components/src/Icon/style.css
- packages/react-ui-components/src/IconButton/__snapshots__/iconButton.spec.tsx.snap
- packages/react-ui-components/src/IconButtonDropDown/__snapshots__/iconButtonDropDown.spec.tsx.snap
- yarn.lock
With these change, the icon component from a font-awesome only version to a more flexible component.
The idea is to have the possibility to use all icons the integrator wants.
In the first step, this change extracts the current icon behavior to an own FontAwesomeIcon component and adds a new ResourceIcon component. The icon component acts then as a de facto factory that checks if the icon property contains a resource URI or just a regular icon string.
The font-awesome icons are the default, and Neos will come now with an additional resource based SVG Icon.
In future, it would be nice to have something like Icon Providers so that people are able to easily register another IconProvider. For instance, a MaterialUIIconProivder.
The regular icons will work like before, but we are able to use …
> FEATURE: Adds resource icon component 

- packages/neos-ui-editors/src/EditorEnvelope/index.js
- packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
When links are defined in the help message, they open currently always in the same window. With this fix, the will open in a new window
> BUGFIX: Open links in new window

- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
In some circumstances, we need to use ClientEval to hide a property, for instance. Actually it is just possible to use the current node data or some child information. But we have not much information about the parent.
As the neos-ui knows which node is the parent, it is quite helpful to use also parent node information in ClientEval. This PR adds the parent node to the context so that we have `node` and `parentNode` available in ClientEval.
**What I did**
Added the parentNode of the current focused node to the props, and therefore it is possible to use the parentNode also in the context of ClientEval.
If you have a node type property, you are able to use node and parentNode in the ClientEval.
```
'chapterImage':
type: 'Neos\Media\Domain\Model\ImageInterface'
ui: …
```
> FEATURE: Expose parentNode for ClientEval in right side bar

- packages/neos-ui-validators/src/Count/index.tsx
closes #2999 
**What I did**
Since passing null to the CountValidator makes the page go white, null should throw an error message that it cannot be counted 
If the value passed to the CountValidator is not an object or is null, an error message is shown. 
Validating a property of type integer does not make the page go white anymore, but shows an error message below the input field
> BUGFIX: Do not allow null in CountValidation

- packages/neos-ui-editors/src/Editors/Range/index.js
- packages/neos-ui-editors/src/Editors/Range/style.css
* Pass default options to the editor
* Remove transition of thumb (opacity gets never changed)
* Add more space between the unit and the input field
* Add border-radius (Similar to a text field)
* Remove border from thumb
* Use Neos constants
* Add hover and focus state to thumb
* Style disabled state
> BUGFIX: Range editor styling issues

- yarn.lock
To prevent the outdated message in the logs.
Browserslist: caniuse-lite is outdated.
**What I did**
Updated caniuse-lite to the latest version.
```npx browserslist@latest --update-db```
Run make build and check for the message ```Browserslist: caniuse-lite is outdated.```
There should be no output anymore.
> TASK: Update caniuse-lite

- packages/react-ui-components/src/SelectBox/__snapshots__/selectBox.spec.js.snap
- packages/react-ui-components/src/SelectBox/selectBox.js
- packages/react-ui-components/src/SelectBox/style.css
**What I did**
Adds an extra class of the select box contents section when the content is empty to reset the padding.
Resolves: #3005
> BUGFIX: Reset padding for empty dropdown contents

- packages/neos-ui-editors/src/Editors/Range/index.js
Before this change, the old value was not refelected in the UI if the discard button was pressed.
> BUGFIX: Reflect the old value if discard button is pressed

- packages/react-ui-components/src/Icon/style.css
closes #3017 
**What I did**
When using very wide Custom SVGs in the left sidebar, the svg does not overlay the Text anymore. 
I gave the svg a maximum width and a maximum height. 
When using a very wide SVG, the SVG does not overlay the text anymore (see issue)
> BUGFIX: Add maximum width to custom SVG icon in left sidebar

- packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/TableDropDown.css
- packages/react-ui-components/src/CheckBox/style.css
The dropdowns for the column and row settings of the CKEditor tables wrap the label after the checkbox. To prevent that, we now inline the checkbox. So that the text is in the same level.
fixes: #3035
> BUGFIX: Prevent label from wrapping

- packages/neos-ui-backend-connector/src/Endpoints/index.ts
- packages/neos-ui-editors/src/Library/LinkInput.js
- packages/neos-ui-redux-store/src/UI/Remote/index.ts
- packages/neos-ui/src/manifest.dataloaders.js
The inline link handing uses the LinkLookup data loader to fetch node and asset data.
The LinkLookup is a combination of the NodeLookup and NeosAssetLookup data loaders.
As the whole backend can work with asset proxies, the usage of NeosAssetLookup needs to be replaced by the AssetLookup data loader.
Replaced the NeosAssetLookUp with the AssetLookup in the LinkLookup data loader.
So that we not search only for local assets. Additionally, we need some adjustments to handle asset proxies for the link input component.
Activate an asset source that is not the local Neos source, Unsplash for instance.
When the asset source is working, you are able to find assets in the asset editor from Unsplash.
When you now create an inline link and search for an image, …
>  BUGFIX: Handle asset proxy for inline links

- packages/react-ui-components/src/Icon/style.css
**What I did**
When using an SVG icon without height or width as a custom icon in the sidebar, it is not show. 
Example SVG icon: 
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130 42" class="injected-svg" data-src="/_Resources/Static/Packages/Neos.Demo/Images/svg.svg" xmlns:xlink="http://www.w3.org/1999/xlink"><rect x="0.5" y="0.5" width="127" height="41" style="fill:none;stroke:#727272"></rect></svg>`
I have added a height to SVGs in the left Sidebar. With the maximum height and width the icon will not overflow but still show. 
When using the SVG icon above, it will still show in the Sidebar.
closes #3017
> BUGFIX: SVGs in Sidebar are not shown if they have no height or width

- Classes/Service/NodePolicyService.php
fixes #2784
**What I did**
In `getDisallowedNodeTypes(NodeInterface $node)` the list of configured NodeTypes is filtered using the NodeType constraints of the given `$node`. Abstract NodeTypes are still included which might be relevant for the policy check.
Before running the policy check, `array_filter` is called used on all NodeTypes (`$this->nodeTypeManager->getNodeTypes()`). The filter method then checks the constraints depending if `$node` is auto-created or if the NodeType to filter is a superType or the NodeType of the node itself.
One need to compare the runtime of of the /get-additional-node-metadata endpoint in the Neos Backend UI on a project with configured CreateNodePrivilege policy.
This is a screenshot for a Neos 4.3 project without the …
> BUGFIX: Reduce the number of NodeTypes to run policy check against #2784

- packages/react-ui-components/src/SelectBox/selectBox.js
With the introduction of `isNil()` the check for empty strings fail. So, we need to check also for empty strings and render the select box with search header.
> BUGFIX: Render search also for empty string

- package.json
- packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
- yarn.lock
We use `lodash.set` only for one case and as it has some security issues we should get rid of that.
**What I did**
- Replaced the usage with `plow-js`.
- removed the `lodash.set` package
-  should work like before
> TASK: Remove lodash.set

- package.json
- packages/build-essentials/package.json
- packages/build-essentials/src/styles/styleConstants.js
- packages/neos-ui-views/package.json
- packages/neos-ui/package.json
- yarn.lock
**What I did**
Removed `lodash.upperfirst` as dependency.
- removed the dependency `lodash.upperfirst`
- upgraded @neos-project/brand to 1.3.0 as it also used the `lodash.upperfirst`
Run the UI ;)
> TASK: Removes lodash.upperfirst

- packages/neos-ui-extensibility/package.json
- yarn.lock
As we use jest in version 23, we stick the dev-tools to a matching version and that is 7.0.0
> TASK: Update react-dev-utils to 7.0

- Resources/Private/Fusion/Backend/Root.fusion
- packages/neos-ui-backend-connector/src/Endpoints/index.ts
- packages/neos-ui-redux-store/src/User/Impersonate/index.ts
- packages/neos-ui-redux-store/src/User/index.ts
- packages/neos-ui-sagas/src/UI/Impersonate/index.js
- packages/neos-ui-sagas/src/index.js
- packages/neos-ui-sagas/src/manifest.js
- packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/RestoreButtonItem.js
- packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
- packages/neos-ui/src/index.js
With Neos 8.0 we introduce the impersonation feature. So, it is possible to impersonate as a different user from the user management module.
This change will add related endpoints to the neos-ui to be able to communicate with the Neos.Neos API. The impersonation state will be saved in the Redux store, and a saga handles the restore of the origin user.
Besides the data handling stuff, we also add a new button to the user menu.
Related Neos PR:
https://github.com/neos/neos-development-collection/pull/3648
https://user-images.githubusercontent.com/1014126/159938292-884a17d0-e138-40e0-83ea-65366000396e.mp4
> FEATURE: Adds restore button for user impersonation

- packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
**What I did**
Fix the copy & paste error by checking if a node is allowed to be edited instead of checking for the hidden property which was actually meant for the `visibilityToggleAllowed` check.
Create a `Policy.yaml` with the following content:
```yaml
privilegeTargets:
'Neos\ContentRepository\Security\Authorization\Privilege\Node\EditNodePropertyPrivilege':
'My.Site:DisableHidden':
matcher: nodeIsOfType("Neos.Neos:Document") && nodePropertyIsIn(["_hidden", "hidden"])
```
Without the fix, no actions are possible on the selected document node. With the fix, only the visibility is disabled.
> BUGFIX: Check canEdit policy instead of hidden property

- packages/neos-ui-backend-connector/src/Endpoints/index.ts
- packages/neos-ui-editors/src/Library/LinkInput.js
The link editor handles assets differently from the asset editor and doesn't correctly check if an asset is already available locally, this leads to unnecessary calls to import proxies and can lead to duplicates if a given proxy is implemented similarly to the Neos asset source. This change addresses the issue, and prevents duplicate imports.
A minor breaking change had to be made though to preserve the rest of the functionality. IF you use the asset proxy search or detail endpoints of our React UI the `loaderUri` (which is an internal implementation detail specifically for the link editor) has changed format and will now include only `assetProxy://<UUID>` for any asset that is already local (regardless if it comes from a proxy or not).
Further refactoring in this area is recommended in …
> !!!BUGFIX: AssetProxies wrongly reimport assets

- packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/RestoreButtonItem.js
The restore button has some props that are not used and can be removed.
**What I did**
Removed the unused props of `user` and `addFlashMessage`.
> BUGFIX: Remove unused props of RestoreButtonItem

- packages/neos-ui-editors/src/Library/PreviewOption.js
- packages/react-ui-components/src/ListPreviewElement/style.css
- packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/selectBox_Option_MultiLineWithThumbnail.js
- packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/style.css
If the secondary or tertiary label is not set the preview element wouldn’t cover the whole selectbox which will then show a graphical glitch.
This problem currently surfaces when using a custom data source as then the `PreviewOption` is used since Neos 7.3 to allow the display of custom icons.
This is not a problem when the secondary or tertiary label is set for the component because it will stretch the preview high enough.
**What I did**
Introduce a class to unset the reduced line-height if the secondary and tertiary label are not set.
Then the 40px line-height of the parent element will be used and therefore the box filled.
Use a select box editor with a custom data source.
Before:
After:
> BUGFIX: Use full height in selectbox preview element

- Resources/Private/Fusion/Prototypes/Page.fusion
Only apply a 'descendantOf' cache tag when we are in backend context.
This fixes unnecessary clearing of the cache of all parent nodes in frontend context
whenever some content in child nodes is modified.
Fixes #3107
> BUGFIX: Prevent cache clearing of backend info in frontend context

- Classes/Controller/BackendController.php
- Resources/Private/Fusion/Backend/Root.fusion
The fusion path is now dynamically determined by controller / action
This enables additional actions with separate templates for that controller.
The path `Neos.Neos.Ui.BackendController.index` is used instead and the `initializeView` hook with `$view->setFusionPath('backend');` was removed.
> TASK: Refactor controller to not use static fusion path
